###### Imports and Settings

In [1]:
import pandas as pd
#import geopandas as gpd
import numpy as np
import requests
import io
import pickle
import matplotlib.pyplot as plt
from collections import deque
from functools import reduce
%matplotlib inline
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

In [7]:
def percent(x, y):
    return (x/y)*100

## Calculations

# ALL:

## Population + Projections Summary:  
## Household Summary:  
### Households by Household Type (Only dropping - From SF1)
+ Total Households  
+ Family Households  
+ Family Households: Married-Couple Family  
+ Family Households: Other Family  
+ Family Households: Other Family: Male Householder no Wife Present  
+ Family Households: Other Family: Female Householder no Husband Present  
+ Nonfamily Households  
+ Nonfamily Household: Male Householder  
+ Nonfamily Household: Female Householder  
*They don't have the nonfamily male or female - replaced by Householder alone or not alone*  
### Average Household Size (also only dropping)
Median - drop for incorporated and unincorporated  
###  Median Household Income  
Median - drop for incorporated and unincorporated  
### Households by Household Income  
+ Less than 10,000  
+ 10,000 to 14,999  
+ 15,000 to 19,999  
+ 20,000 to 24,999 
+ 25,000 to 29,999  
+ 30,000 to 34,999  
+ 35,000 to 39,999  
+ 40,000 to 44,999  
+ 50,000 to 59,999  
+ 60,000 to 74,999  
+ 75,000 to 99,999  
+ 100,000 to 124,999  
+ 125,000 to 149,999  
+ 150,000 to 199,999  
+ 200,000 or More  
## Education and Work Summary:  
### Educational Attainment Population 25+, and Percentages
+ Population 25+  
+ Less than High School 25+  
+ High School Graduate or Equivalency 25+  
+ Some College 25+  
+ Associates  
+ Bachelor's Degree 25+  
+ Master's Degree 25+  
+ Professional School Degree 25+  
+ Doctorate Degree 25+  
### Industry Employment 16+, and Percentages  
+ Employed Civilians 16+  
+ Agriculture, forestry, fishing and hunting, and mining  
+ Construction  
+ Manufacturing  
+ Wholesale Trade  
+ Retail Trade  
+ Transportation and warehousing, and utilities  
+ Information  
+ Finance, insurance, real estate and rental and leasing  
+ Professional, scientific, management, administrative, and waste management services  
+ Educational, health and social services  
+ Arts, entertainment, recreation, accommodation and food services  
+ Other services (except public administration)  
+ Public administration  
### Occupational Employment 16+, and Percentages  
+ Employed Civilians 16+  
+ Management, Business, and Financial Operations 
+ Professional and Related Occupations  
+ Healthcare Support Operations  
+ Protective Services Occupations  
+ Food Preparation and Serving Related Occupations  
+ Building and Grounds Cleaning and Maintenance Occupations  
+ Personal Care and Service Occupations  
+ Sales and Related Occupations  
+ Office and Administrative Support Occupations  
+ Farming, Fishing, and Forestry Occupations  
+ Construction, Extraction, and Maintenance Occupations  
+ Production Occupations  
+ Transportation and Material Moving Occupations  
### Employment Sector for Population 16+, and Percentages  
+ Private Sector  
+ Public Sector  
+ Self-Employed  
+ Non-Profit  
+ Unpaid Family Workers  
### Employment Status  
+ Employed  
+ Unemployed  
+ Unemployment Rate (unemployed divided by sum of employed and unemployed)  
### Per Capita Income  
## Costs Summary  
### Poverty, and Percentages  
+ Population for whom Poverty Status is Determined  
+ Population Living Below Poverty Level 
### Housing Cost-Burden, and Percentages
+ Total Housing Units  
+ Cost Burdened Households 
+ Renter Occupied Units  
+ Cost Burdened Renters  
+ Owner Occupied Units  
+ Cost Burdened Homeowners  
+ Severe Housing Cost Burden (50% or More)  
## Housing Summary  
### Median Home Value (Owner-Occupied Units)  
Remove for incorporated vs. unincorporated  
### Median Gross Rent (Renter-Occupied Units)  
Remove for incorporated vs. unincorporated  
### Tenure and Occupancy (only dropping, in SF1)  
### Housing Units and Units in Structure, and Percentages  
+ Housing Units: 1 Unit: 1, detached  
+ Housing Units: 1 Unit: 1, attached  
+ Housing Units: 2  
+ Housing Units: 3 or 4  
+ Housing Units: 5 to 9  
+ Housing Units: 10 to 19  
+ Housing Units: 20 to 49  
+ Housing Units: 50 or MOre  
+ Housing Units: Mobile Home  
+ Housing Units: Boat, RV, Van, etc.  
## Transportation Summary  
### Means of Transportation to Work for Workers 16+, and Percentages  
+ Transpo:Workers 16+  
+ Transpo:Car, Truck, or Van  
+ Transpo:Public Transportation  
+ Transpo:Motorcycle now Taxicab Motorcycle or Other  
+ Transpo:Bicycle  
+ Transpo:Walked  
+ Transpo:Other Means  
+ Transpo:Worked at Home  
### Vehicle Ownership, and Percentages  
+ Vehicles:Households
+ Vehicles:None  
+ Vehicles:1  
+ Vehicles:2  
+ Vehicles:3  
+ Vehicles:4  
+ Vehicles:5+  
### Travel Time by Mode  
+ Workers 16+ Not Working at Home  
+ Less than 10 Minutes  
+ 10 to 14 Minutes  
+ 15 to 19 Minutes  
+ 20 to 24 Minutes  
+ 25 to 29 Minutes  
+ 30 to 34 Minutes  
+ 35 to 44 Minutes  
+ 45 to 59 Minutes  
+ 60 or More Minutes  
+ Less than 10 Minutes: Car, Truck, or Van Drove Alone  
+ 10 to 14 Minutes: Car, Truck, or Van Drove Alone  
+ 15 to 19 Minutes: Car, Truck, or Van Drove Alone  
+ 20 to 24 Minutes: Car, Truck, or Van Drove Alone  
+ 25 to 29 Minutes: Car, Truck, or Van Drove Alone  
+ 30 to 34 Minutes: Car, Truck, or Van Drove Alone  
+ 35 to 44 Minutes: Car, Truck, or Van Drove Alone  
+ 45 to 59 Minutes: Car, Truck, or Van Drove Alone  
+ 60 or More Minutes: Car, Truck, or Van Drove Alone  
+ Less than 10 Minutes: Car, Truck, or Van Carpooled    
+ 10 to 14 Minutes: Car, Truck, or Van Carpooled    
+ 15 to 19 Minutes: Car, Truck, or Van Carpooled    
+ 20 to 24 Minutes: Car, Truck, or Van Carpooled    
+ 25 to 29 Minutes: Car, Truck, or Van Carpooled    
+ 30 to 34 Minutes: Car, Truck, or Van Carpooled    
+ 35 to 44 Minutes: Car, Truck, or Van Carpooled    
+ 45 to 59 Minutes: Car, Truck, or Van Carpooled    
+ 60 or More Minutes: Car, Truck, or Van Carpooled   
+ Less than 10 Minutes: Public Transportation (Excluding Taxicab)    
+ 10 to 14 Minutes: Public Transportation (Excluding Taxicab)    
+ 15 to 19 Minutes: Public Transportation (Excluding Taxicab)    
+ 20 to 24 Minutes: Public Transportation (Excluding Taxicab)    
+ 25 to 29 Minutes: Public Transportation (Excluding Taxicab)    
+ 30 to 34 Minutes: Public Transportation (Excluding Taxicab)    
+ 35 to 44 Minutes: Public Transportation (Excluding Taxicab)    
+ 45 to 59 Minutes: Public Transportation (Excluding Taxicab)    
+ 60 or More Minutes: Public Transportation (Excluding Taxicab)    
+ Less than 10 Minutes: Walked  
+ 10 to 14 Minutes: Walked  
+ 15 to 19 Minutes: Walked  
+ 20 to 24 Minutes: Walked  
+ 25 to 29 Minutes: Walked  
+ 30 to 34 Minutes: Walked  
+ 35 to 44 Minutes: Walked  
+ 45 to 59 Minutes: Walked  
+ 60 or More Minutes: Walked  
+ Less than 10 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 10 to 14 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 15 to 19 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 20 to 24 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 25 to 29 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 30 to 34 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 35 to 44 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 45 to 59 Minutes: Taxicab, Motorcycle, Bicycle, Other    
+ 60 or More Minutes: Taxicab, Motorcycle, Bicycle, Other  
## Miscellaneous Summary  
### Veteran Status, and Percentages  
+ Civilian Population 18+  
+ Civilian Population 18+: Veteran  
+ Civilian Population 18+ Veteran: 18 to 64  
+ Civilian Population 18+ Veteran: 65 and Over  
+ Civilian Population 18+ Veteran: Nonveteran
+ Civilian Population 18+ Nonveteran: 18 to 64  
+ Civilian Population 18+ Nonveteran: 65 and Over 
### Geographic Mobility, Moved, and Percentages  
+ Mobility: Total  
+ Mobility: Same House  
+ Mobility: Moved Same County  
+ Mobility: Moved Different County Same State  
+ Mobility: Moved Different State  
+ Mobility: Moved From Abroad  
## Diversity Summary  
### Foreign-Born Status  
+ Total Population  
+ Pop: Native Born  
+ Pop: Foreign Born and Percent  
+ Pop Foreign Born: Naturalized Citizen  
+ Pop Foreign Born: Not a Citizen  
### Place of Birth for Foreign-Born Population  
+ Total Foreign Born Population  
+ Total from Europe  
+ Total from Asia  
+ Total from Africa  
+ Total from Oceania  
+ Total from Central + South America + Caribbean  
+ Total from Canada + Other Northern American  
### Language Spoken at Home by Ability to Speak English for Population 5+  
+ Language:Population 5 Years and Over  
+ Language:Speak Only English  
+ Language:Speak Spanish  
+ SpeakSpanish:Speak English Very Well  
+ SpeakSpanish:Speak English Well  
+ SpeakSpanish:Speak English Not Well  
+ SpeakSpanish:Speak English Not At All  
+ Language:Speak other Indo-European Languages
+ SpeakIndoEuro:Speak English Very Well  
+ SpeakIndoEuro:Speak English Well  
+ SpeakIndoEuro:Speak English Not Well  
+ SpeakIndoEuro:Speak English Not At All  
+ Speak Asian and Pacific Island Languages  
+ SpeakAsianPacificIsland:Speak English Very Well  
+ SpeakAsianPacificIsland:Speak English Well  
+ SpeakAsianPacificIsland:Speak English Not Well  
+ SpeakAsianPacificIsland:Speak English Not At All  
+ Language:Speak Other Languages
+ SpeakOtherLanguages:Speak English Very Well  
+ SpeakOtherLanguages:Speak English Well  
+ SpeakOtherLanguages:Speak English Not Well  
+ SpeakOtherLanguages:Speak English Not At All  

#### Percentages  
+ % Speak Only English  
+ % Speak Other Language  
+ % of Those that Speak Other Language and Speak English Not Well or At All

In [8]:
data = pd.read_csv('../../data/ACS20105YR.csv')

In [9]:
data['Population'] = data['agebysex_total_series']
data = data.drop(columns = 'agebysex_total_series')
#hh type and avg hh size drop
cols = ['hhtype_total_series','hhtype_familyhh','hhtype_familyhh_marriedcouplefam','hhtype_familyhh_otherfam','hhtype_familyhh_malenospouse',
        'hhtype_familyhh_femalenospouse','hhtype_nonfamhh','hhtype_nonfamhh_householderalone','hhtype_nonfamhh_householdernotalone']
data = data.drop(columns = cols)
data = data.drop(columns = ['hhsize_avg'])
#median hh income
data['Median Household Income'] = data['hhincome_median']
data = data.drop(columns = ['hhincome_median'])
#hh income brackets
data['HHIncome:Total Households'] = data['hhincome_total_series']
data['HHIncome:Less than 10,000'] = data['hhincome_lessthan10000']
data['HHIncome%:Less than 10,000'] = percent(data['HHIncome:Less than 10,000'], data['HHIncome:Total Households'])
data['HHIncome:10 to 14,999'] = data['hhincome_10to14999']
data['HHIncome%:10 to 14,999'] = percent(data['HHIncome:10 to 14,999'], data['HHIncome:Total Households'])
data['HHIncome:15 to 19,999'] = data['hhincome_15to19999']
data['HHIncome%:15 to 19,999'] = percent(data['HHIncome:15 to 19,999'], data['HHIncome:Total Households'])
data['HHIncome:20 to 24,999'] = data['hhincome_20to24999']
data['HHIncome%:20 to 24,999'] = percent(data['HHIncome:20 to 24,999'], data['HHIncome:Total Households'])
data['HHIncome:25 to 29,999'] = data['hhincome_25to29999']
data['HHIncome%:25 to 29,999'] = percent(data['HHIncome:25 to 29,999'], data['HHIncome:Total Households'])
data['HHIncome:30 to 34,999'] = data['hhincome_30to34999']
data['HHIncome:%30 to 34,999'] = percent(data['HHIncome:30 to 34,999'], data['HHIncome:Total Households'])
data['HHIncome:35 to 39,999'] = data['hhincome_35to39999']
data['HHIncome%:35 to 39,999'] = percent(data['HHIncome:35 to 39,999'], data['HHIncome:Total Households'])
data['HHIncome:40 to 44,999'] = data['hhincome_40to44999']
data['HHIncome%:40 to 44,999'] = percent(data['HHIncome:40 to 44,999'], data['HHIncome:Total Households'])
data['HHIncome:45 to 49,999'] = data['hhincome_45to49999']
data['HHIncome%:45 to 49,999'] = percent(data['HHIncome:45 to 49,999'], data['HHIncome:Total Households'])
data['HHIncome:50 to 59,999'] = data['hhincome_50to59999']
data['HHIncome%:50 to 59,999'] = percent(data['HHIncome:50 to 59,999'], data['HHIncome:Total Households'])
data['HHIncome:60 to 74,999'] = data['hhincome_60to74999']
data['HHIncome%:60 to 74,999'] = percent(data['HHIncome:60 to 74,999'], data['HHIncome:Total Households'])
data['HHIncome:75 to 99,999'] = data['hhincome_75to99999']
data['HHIncome%:75 to 99,999'] = percent(data['HHIncome:75 to 99,999'], data['HHIncome:Total Households'])
data['HHIncome:100 to 124,999'] = data['hhincome_100to124999']
data['HHIncome%:100 to 124,999'] = percent(data['HHIncome:100 to 124,999'], data['HHIncome:Total Households'])
data['HHIncome:125 to 149,999'] = data['hhincome125to149999']
data['HHIncome%:125 to 149,999'] = percent(data['HHIncome:125 to 149,999'], data['HHIncome:Total Households'])
data['HHIncome:150 to 199,999'] = data['hhincome150to199999']
data['HHIncome%:150 to 199,999'] = percent(data['HHIncome:150 to 199,999'], data['HHIncome:Total Households'])
data['HHIncome:200K or More'] = data['hhincome200ormore']
data['HHIncome%:200K or More'] = percent(data['HHIncome:200K or More'], data['HHIncome:Total Households'])
cols = ['hhincome_total_series','hhincome_lessthan10000','hhincome_10to14999','hhincome_15to19999','hhincome_20to24999','hhincome_25to29999',
        'hhincome_30to34999','hhincome_35to39999','hhincome_40to44999','hhincome_45to49999','hhincome_50to59999','hhincome_60to74999','hhincome_75to99999',
        'hhincome_100to124999','hhincome125to149999','hhincome150to199999','hhincome200ormore']
data = data.drop(columns = cols)
#educational attainment
data['Ed:Population 25+ Educational Attainment'] = data['attainment_totalbysex_over25_series']
lesshighschoollist = [data['attainment_m_noschooling'],data['attainment_m_nurseryschoolto4thgrade'],data['attainment_m_5thto6thgrade'], data['attainment_m_7thto8thgrade'],
                      data['attainment_m_9thgrade'],data['attainment_m_10thgrade'],data['attainment_m_11thgrade'],data['attainment_m_12thgradenodiploma'],
                      data['attainment_f_noschooling'],data['attainment_f_nurseryschoolto4thgrade'],data['attainment_f_5thto6thgrade'], data['attainment_f_7thto8thgrade'],
                      data['attainment_f_9thgrade'],data['attainment_f_10thgrade'],data['attainment_f_11thgrade'],data['attainment_f_12thgradenodiploma']]
data['Ed:Less than High School'] = sum(lesshighschoollist)
data['Ed%:Less than High School'] = percent(data['Ed:Less than High School'], data['Ed:Population 25+ Educational Attainment'])
data['Ed:High School Graduate or Equivalency'] = data['attainment_m_highschooldiplomaorequivalent']+data['attainment_f_highschooldiplomaorequivalent']
data['Ed%:High School Graduate or Equivalency'] = percent(data['Ed:High School Graduate or Equivalency'], data['Ed:Population 25+ Educational Attainment'])
highormore = [data['Ed:High School Graduate or Equivalency'],data['attainment_m_somecollegelessthan1year'],data['attainment_m_somecollege1ormoreyearsnodegree'],
              data['attainment_m_associatesdegree'],data['attainment_m_bachelorsdegree'],
              data['attainment_m_mastersdegree'],data['attainment_m_professionalschooldegree'],data['attainment_m_doctoratedegree'],
              data['attainment_f_somecollegelessthan1year'],data['attainment_f_somecollege1ormoreyearsnodegree'],
              data['attainment_f_associatesdegree'],data['attainment_f_bachelorsdegree'],
              data['attainment_f_mastersdegree'],data['attainment_f_professionalschooldegree'],data['attainment_f_doctoratedegree']]
data['Ed%:High School Graduate or More'] = percent(sum(highormore),data['Ed:Population 25+ Educational Attainment'])
somecollege = [data['attainment_m_somecollegelessthan1year'], data['attainment_m_somecollege1ormoreyearsnodegree'],data['attainment_f_somecollegelessthan1year'],
               data['attainment_f_somecollege1ormoreyearsnodegree']]
data['Ed:Some College'] = sum(somecollege)
data['Ed%:Some College'] = percent(data['Ed:Some College'], data['Ed:Population 25+ Educational Attainment'])
somecollegeormore = [data['Ed%:Some College'],data['attainment_m_associatesdegree'],data['attainment_m_bachelorsdegree'],data['attainment_m_mastersdegree'],
                     data['attainment_m_professionalschooldegree'],data['attainment_m_doctoratedegree'],data['attainment_f_associatesdegree'],
                     data['attainment_f_bachelorsdegree'],data['attainment_f_mastersdegree'],data['attainment_f_professionalschooldegree'],
                     data['attainment_f_doctoratedegree']]
data['Ed%:Some College or More'] = percent(sum(somecollegeormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Associates'] = data['attainment_m_associatesdegree']+data['attainment_f_associatesdegree']
data['Ed%:Associates'] = percent(data['Ed:Associates'], data['Ed:Population 25+ Educational Attainment'])
data['Ed:Bachelors'] = data['attainment_m_bachelorsdegree']+data['attainment_f_bachelorsdegree']
data['Ed%:Bachelors'] = percent(data['Ed:Bachelors'], data['Ed:Population 25+ Educational Attainment'])
bachormore = [data['Ed:Bachelors'],data['attainment_m_mastersdegree'],data['attainment_m_professionalschooldegree'],data['attainment_m_doctoratedegree'],
             data['attainment_f_mastersdegree'],data['attainment_f_professionalschooldegree'],data['attainment_f_doctoratedegree']]
data['Ed%:Bachelors or More'] = percent(sum(bachormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Masters'] = data['attainment_m_mastersdegree'] + data['attainment_f_mastersdegree']
mastersormore = [data['Ed:Masters'],data['attainment_m_professionalschooldegree'],data['attainment_m_doctoratedegree'],
                data['attainment_f_professionalschooldegree'],data['attainment_f_doctoratedegree']]
data['Ed%:Masters'] = percent(data['Ed:Masters'], data['Ed:Population 25+ Educational Attainment'])
data['Ed%:Masters or More'] = percent(sum(mastersormore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Professional School Degree'] = data['attainment_m_professionalschooldegree']+ data['attainment_f_professionalschooldegree']
data['Ed%:Professional School Degree'] = percent(data['Ed:Professional School Degree'], data['Ed:Population 25+ Educational Attainment'])
proformore = [data['Ed:Professional School Degree'],data['attainment_m_doctoratedegree'],data['attainment_f_doctoratedegree']]
data['Ed%:Professional School Degree or More'] = percent(sum(proformore),data['Ed:Population 25+ Educational Attainment'])
data['Ed:Doctorate Degree'] = data['attainment_m_doctoratedegree'] + data['attainment_f_doctoratedegree']
data['Ed%:Doctorate Degree'] = percent(data['Ed:Doctorate Degree'], data['Ed:Population 25+ Educational Attainment'])
cols = ['attainment_totalbysex_over25_series','attainment_m','attainment_m_noschooling','attainment_m_nurseryschoolto4thgrade','attainment_m_5thto6thgrade',
        'attainment_m_7thto8thgrade','attainment_m_9thgrade','attainment_m_10thgrade','attainment_m_11thgrade','attainment_m_12thgradenodiploma',
        'attainment_m_highschooldiplomaorequivalent','attainment_m_somecollegelessthan1year','attainment_m_somecollege1ormoreyearsnodegree',
        'attainment_m_associatesdegree','attainment_m_bachelorsdegree','attainment_m_mastersdegree','attainment_m_professionalschooldegree',
        'attainment_m_doctoratedegree','attainment_f','attainment_f_noschooling','attainment_f_nurseryschoolto4thgrade','attainment_f_5thto6thgrade',
        'attainment_f_7thto8thgrade','attainment_f_9thgrade','attainment_f_10thgrade','attainment_f_11thgrade','attainment_f_12thgradenodiploma',
        'attainment_f_highschooldiplomaorequivalent','attainment_f_somecollegelessthan1year','attainment_f_somecollege1ormoreyearsnodegree',
        'attainment_f_associatesdegree','attainment_f_bachelorsdegree','attainment_f_mastersdegree','attainment_f_professionalschooldegree',
        'attainment_f_doctoratedegree']
data = data.drop(columns = cols)
#industry employment
data['Ind:Employed Civilians 16+'] = data['industry_sexbyindustrycivilianpop_total_series']
aglist = [data['industry_m_agriculture_forestry_fishing_hunting_mining'],data['industry_f_agriculture_forestry_fishing_hunting_mining']]
data['Ind:Agriculture, Forestry, Fishing and Hunting, and Mining'] = sum(aglist)
data['Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining']=percent(data['Ind:Agriculture, Forestry, Fishing and Hunting, and Mining'],
                                                                            data['Ind:Employed Civilians 16+'])
data['Ind:Construction'] = data['industry_m_construction']+data['industry_f_construction']
data['Ind%:Construction']=percent(data['Ind:Construction'],data['Ind:Employed Civilians 16+'])
data['Ind:Manufacturing'] = data['industry_m_manufacturing'] + data['industry_f_manufacturing']
data['Ind%:Manufacturing']=percent(data['Ind:Manufacturing'],data['Ind:Employed Civilians 16+'])
data['Ind:Wholesale Trade'] = data['industry_m_wholesaletrade']+data['industry_f_wholesaletrade']
data['Ind%:Wholesale Trade']=percent(data['Ind:Wholesale Trade'],data['Ind:Employed Civilians 16+'])
data['Ind:Retail Trade'] = data['industry_m_retailtrade']+data['industry_f_retailtrade']
data['Ind%:Retail Trade']=percent(data['Ind:Retail Trade'],data['Ind:Employed Civilians 16+'])
transware = [data['industry_m_transportation_warehousing_utilities'],data['industry_f_transportation_warehousing_utilities']]
data['Ind:Transportation and Warehousing, Utilities'] = sum(transware)
data['Ind%:Transportation and Warehousing, Utilities']=percent(data['Ind:Transportation and Warehousing, Utilities'],data['Ind:Employed Civilians 16+'])
data['Ind:Information'] = data['industry_m_information']+data['industry_f_information']
data['Ind%:Information']=percent(data['Ind:Information'],data['Ind:Employed Civilians 16+'])
finins = [data['industry_m_finance_insurance_realestate_rental'],data['industry_f_finance_insurance_realestate_rental']]
data['Ind:Finance, Insurance, Real Estate and Rental and Leasing'] = sum(finins)
data['Ind%:Finance, Insurance, Real Estate and Rental and Leasing']=percent(data['Ind:Finance, Insurance, Real Estate and Rental and Leasing'],
                                                                            data['Ind:Employed Civilians 16+'])
profsci = [data['industry_m_professional_scientific_managementadmin_waste'],data['industry_f_professional_scientific_managementadmin_waste']]
data['Ind:Professional, Scientific, Management, Administrative, and Waste Management Services']= sum(profsci)
data['Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services']=percent(data['Ind:Professional, Scientific, Management, Administrative, and Waste Management Services'],
                                                                                                         data['Ind:Employed Civilians 16+'])
edhealth = [data['industry_m_educational_healthcare_socialassistance'],data['industry_f_educational_healthcare_socialassistance']]
data['Ind:Educational, Health and Social Services'] = sum(edhealth)
data['Ind%:Educational, Health and Social Services']=percent(data['Ind:Educational, Health and Social Services'],data['Ind:Employed Civilians 16+'])
artsrec = [data['industry_m_arts_entertainmentrec_accommodation_food'],data['industry_f_arts_entertainmentrec_accommodation_food']]
data['Ind:Arts, Entertainment, Recreation, Accommodation and Food Services'] = sum(artsrec)
data['Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services']=percent(data['Ind:Arts, Entertainment, Recreation, Accommodation and Food Services'],
                                                                                      data['Ind:Employed Civilians 16+'])
data['Ind:Other Services (Except Public Administration)']=data['industry_m_otherservices_notpublicadmin']+data['industry_f_otherservices_notpublicadmin']
data['Ind%:Other Services (Except Public Administration)']=percent(data['Ind:Other Services (Except Public Administration)'],data['Ind:Employed Civilians 16+'])
data['Ind:Public Administration'] = data['industry_m_publicadmin']+data['industry_f_publicadmin']
data['Ind%:Public Administration']=percent(data['Ind:Public Administration'],data['Ind:Employed Civilians 16+'])
cols = ['industry_sexbyindustrycivilianpop_total_series','industry_sexbyindustrycivilianpop_totalmale','industry_m_agriculture_forestry_fishing_hunting_mining',
        'industry_m_agmining_agriculture_forestry_fishing_hunting','industry_m_agmining_mining_quarrying_oilandgas','industry_m_construction',
        'industry_m_manufacturing','industry_m_wholesaletrade','industry_m_retailtrade','industry_m_transportation_warehousing_utilities',
        'industry_m_transut_transportation_warehousing','industry_m_transut_utilities','industry_m_information','industry_m_finance_insurance_realestate_rental',
        'industry_m_finrent_finance_insurance','industry_m_finrent_realestate_rental','industry_m_professional_scientific_managementadmin_waste',
        'industry_m_profwaste_professional_scientific_technicalservices','industry_m_profwaste_managementcompaniesenterprises','industry_m_adminandsupportandwaste',
        'industry_m_educational_healthcare_socialassistance','industry_m_edsocial_educational','industry_m_edsocial_healthcare_socialassistance',
        'industry_m_arts_entertainmentrec_accommodation_food','industry_m_artsaccom_arts_entertainmentrec','industry_m_artsaccom_accommodation_food',
        'industry_m_otherservices_notpublicadmin','industry_m_publicadmin','industry_sexbyindustrycivilianpop_totalfemale',
        'industry_f_agriculture_forestry_fishing_hunting_mining','industry_f_agmining_agriculture_forestry_fishing_hunting',
        'industry_f_agmining_mining_quarrying_oilandgas','industry_f_construction','industry_f_manufacturing','industry_f_wholesaletrade','industry_f_retailtrade',
        'industry_f_transportation_warehousing_utilities','industry_f_transut_transportation_warehousing','industry_f_transut_utilities','industry_f_information',
        'industry_f_finance_insurance_realestate_rental','industry_f_finrent_finance_insurance','industry_f_finrent_realestate_rental',
        'industry_f_professional_scientific_managementadmin_waste','industry_f_profwaste_professional_scientific_technicalservices',
        'industry_f_profwaste_managementcompaniesenterprises','industry_f_adminandsupportandwaste','industry_f_educational_healthcare_socialassistance',
        'industry_f_edsocial_educational','industry_f_edsocial_healthcare_socialassistance','industry_f_arts_entertainmentrec_accommodation_food',
        'industry_f_artsaccom_arts_entertainmentrec','industry_f_artsaccom_accommodation_food','industry_f_otherservices_notpublicadmin','industry_f_publicadmin']
data = data.drop(columns = cols)
#occupational employment
data['Employed Civilians 16+ Occupational'] = data['occupation_sexbyoccupationcivilianpop_total_series']
manbusfin = [data['occupation_m_management'],data['occupation_f_management'],data['occupation_m_businessandfinancial'],
             data['occupation_f_businessandfinancial']]
data['Occ:Management, Business, and Financial Operations'] = sum(manbusfin)
data['Occ%:Management, Business, and Financial Operations'] = percent(data['Occ:Management, Business, and Financial Operations'],
                                                                      data['Employed Civilians 16+ Occupational'])
profandrelated = [data['occupation_m_businessandfinancial'], data['occupation_m_computerandmathematical'], data['occupation_m_architectureandengineering'],
                  data['occupation_m_lifephysicalsocialscience'], data['occupation_m_communityandsocialservices'], data['occupation_m_legal'],
                  data['occupation_m_educationtrainingandlibrary'], data['occupation_m_artsdesignentertainmentsportsandmedia'], 
                  data['occupation_m_healthcarepractitionersandtechnical'], data['occupation_f_businessandfinancial'], 
                  data['occupation_f_computerandmathematical'], data['occupation_f_architectureandengineering'], data['occupation_f_architectureandengineering'],
                  data['occupation_f_lifephysicalsocialscience'], data['occupation_f_communityandsocialservices'], data['occupation_f_legal'],
                  data['occupation_f_educationtrainingandlibrary'], data['occupation_f_artsdesignentertainmentsportsandmedia'],
                  data['occupation_f_healthcarepractitionersandtechnical']]
data['Occ:Professional and Related'] = sum(profandrelated)
data['Occ%:Professional and Related'] = percent(data['Occ:Professional and Related'],data['Employed Civilians 16+ Occupational'])
data['Occ:Healthcare Support'] = data['occupation_m_healthcaresupport']+data['occupation_f_healthcaresupport']
data['Occ%:Healthcare Support'] = percent(data['Occ:Healthcare Support'],data['Employed Civilians 16+ Occupational'])
data['Occ:Protective Services'] = data['occupation_m_protectiveservice']+data['occupation_f_protectiveservice']
data['Occ%:Protective Services'] = percent(data['Occ:Protective Services'],data['Employed Civilians 16+ Occupational'])
data['Occ:Food Preparation and Serving Related'] = data['occupation_m_foodprepandserving']+data['occupation_f_foodprepandserving']
data['Occ%:Food Preparation and Serving Related'] = percent(data['Occ:Food Preparation and Serving Related'],data['Employed Civilians 16+ Occupational'])
buildinggrounds = [data['occupation_m_buildingandgroundscleaningandmaintenance'],data['occupation_f_buildingandgroundscleaningandmaintenance']]
data['Occ:Building and Grounds Cleaning and Maintenance'] = sum(buildinggrounds)
data['Occ%:Building and Grounds Cleaning and Maintenance'] = percent(data['Occ:Building and Grounds Cleaning and Maintenance'],
                                                                     data['Employed Civilians 16+ Occupational'])
data['Occ:Personal Care and Service'] = data['occupation_m_personalcareandservice'] + data['occupation_f_personalcareandservice']
data['Occ%:Personal Care and Service'] = percent(data['Occ:Personal Care and Service'],data['Employed Civilians 16+ Occupational'])
data['Occ:Sales and Related'] = data['occupation_m_salesandrelated']+data['occupation_f_salesandrelated']
data['Occ%:Sales and Related'] = percent(data['Occ:Sales and Related'],data['Employed Civilians 16+ Occupational'])
data['Occ:Office and Administrative Support'] = data['occupation_m_officeandadmin'] + data['occupation_f_officeandadmin']
data['Occ%:Office and Administrative Support'] = percent(data['Occ:Office and Administrative Support'],data['Employed Civilians 16+ Occupational'])
data['Occ:Farming, Fishing, and Forestry'] = data['occupation_m_farmingfishingandforestry']+data['occupation_f_farmingfishingandforestry']
data['Occ%:Farming, Fishing, and Forestry'] = percent(data['Occ:Farming, Fishing, and Forestry'],data['Employed Civilians 16+ Occupational'])
constexmaint = [data['occupation_m_constructionandextraction'],data['occupation_m_installationmaintenanceandrepair'],data['occupation_f_constructionandextraction'],
               data['occupation_f_installationmaintenanceandrepair']]
data['Occ:Construction, Extraction, and Maintenance'] = sum(constexmaint)
data['Occ%:Construction, Extraction, and Maintenance'] = percent(data['Occ:Construction, Extraction, and Maintenance'],data['Employed Civilians 16+ Occupational'])
data['Occ:Production'] = data['occupation_m_production']+data['occupation_f_production']
data['Occ%:Production'] = percent(data['Occ:Production'],data['Employed Civilians 16+ Occupational'])
transpomat = [data['occupation_m_transportation'],data['occupation_f_transportation'],data['occupation_m_materialmoving'],data['occupation_f_materialmoving']]
data['Occ:Transportation and Material Moving'] = sum(transpomat)
data['Occ%:Transportation and Material Moving'] = percent(data['Occ:Transportation and Material Moving'],data['Employed Civilians 16+ Occupational'])
cols = ['occupation_sexbyoccupationcivilianpop_total_series','occupation_sexbyoccupationcivilianpop_totalmale','occupation_m_management',
        'occupation_m_businessandfinancial','occupation_m_computerandmathematical','occupation_m_architectureandengineering',
        'occupation_m_lifephysicalsocialscience','occupation_m_communityandsocialservices','occupation_m_legal','occupation_m_educationtrainingandlibrary',
        'occupation_m_artsdesignentertainmentsportsandmedia','occupation_m_healthcarepractitionersandtechnical','occupation_m_healthcaresupport',
        'occupation_m_protectiveservice','occupation_m_foodprepandserving','occupation_m_buildingandgroundscleaningandmaintenance',
        'occupation_m_personalcareandservice','occupation_m_salesandrelated','occupation_m_officeandadmin','occupation_m_farmingfishingandforestry',
        'occupation_m_constructionandextraction','occupation_m_installationmaintenanceandrepair','occupation_m_production','occupation_m_transportation',
        'occupation_m_materialmoving','occupation_sexbyoccupationcivilianpop_totalfemale','occupation_f_management',
        'occupation_f_businessandfinancial','occupation_f_computerandmathematical','occupation_f_architectureandengineering','occupation_f_lifephysicalsocialscience',
        'occupation_f_communityandsocialservices','occupation_f_legal','occupation_f_educationtrainingandlibrary',
        'occupation_f_artsdesignentertainmentsportsandmedia','occupation_f_healthcarepractitionersandtechnical','occupation_f_healthcaresupport',
        'occupation_f_protectiveservice','occupation_f_foodprepandserving','occupation_f_buildingandgroundscleaningandmaintenance',
        'occupation_f_personalcareandservice','occupation_f_salesandrelated','occupation_f_officeandadmin','occupation_f_farmingfishingandforestry',
        'occupation_f_constructionandextraction','occupation_f_installationmaintenanceandrepair','occupation_f_production','occupation_f_transportation',
        'occupation_f_materialmoving']
data = data.drop(columns = cols)
#sector
data['Sector: Total Workers'] = data['classworker_total_series']
data['Sector:Private'] = data['classworker_privateforprofit']
data['Sector%:Private'] = percent(data['Sector:Private'], data['Sector: Total Workers'])
data['Sector:Public'] = data['classworker_localgovt']+data['classworker_stategovt']+data['classworker_federalgovt']
data['Sector%:Public'] = percent(data['Sector:Public'], data['Sector: Total Workers'])
data['Sector:Self-Employed'] = data['classworker_privateforprofit_selfemployedincorporatedbusiness']+data['classworker_selfemployednonincorporatedbusiness']
data['Sector%:Self-Employed'] = percent(data['Sector:Self-Employed'], data['Sector: Total Workers'])
data['Sector:Non-Profit'] = data['classworker_privatenotforprofit']
data['Sector%:Non-Profit'] = percent(data['Sector:Non-Profit'], data['Sector: Total Workers'])
data['Sector:Unpaid Family Workers'] = data['classworker_unpaidfamilyworker']
data['Sector%:Unpaid Family Workers'] = percent(data['Sector:Unpaid Family Workers'], data['Sector: Total Workers'])
cols = ['classworker_total_series','classworker_privateforprofit','classworker_privateforprofit_employee',
        'classworker_privateforprofit_selfemployedincorporatedbusiness','classworker_privatenotforprofit','classworker_localgovt','classworker_stategovt',
        'classworker_federalgovt','classworker_selfemployednonincorporatedbusiness','classworker_unpaidfamilyworker']
data = data.drop(columns = cols)
# lf status
civemployed = [data['lfstatus_mciv_16to19_employed'],data['lfstatus_mciv_20to21_employed'],data['lfstatus_mciv_22to24_employed'],
               data['lfstatus_mciv_25to29_employed'],data['lfstatus_mciv_30to34_employed'],data['lfstatus_mciv_35to44_employed'],
               data['lfstatus_mciv_45to54_employed'],data['lfstatus_mciv_55to59_employed'],data['lfstatus_mciv_60to61_employed'],
               data['lfstatus_mciv_62to64_employed'],data['lfstatus_mciv_65to69_employed'],data['lfstatus_mciv_70to74_employed'],
               data['lfstatus_mciv_75+_employed'],data['lfstatus_fciv_16to19_employed'],data['lfstatus_fciv_20to21_employed'],
               data['lfstatus_fciv_22to24_employed'],data['lfstatus_fciv_25to29_employed'],data['lfstatus_fciv_30to34_employed'],
               data['lfstatus_fciv_35to44_employed'],data['lfstatus_fciv_45to54_employed'],data['lfstatus_fciv_55to59_employed'],
               data['lfstatus_fciv_60to61_employed'],data['lfstatus_fciv_62to64_employed'],data['lfstatus_fciv_65to69_employed'],
               data['lfstatus_fciv_70to74_employed'],data['lfstatus_fciv_75+_employed']]
data['Employed'] = sum(civemployed)
civunemployed = [data['lfstatus_mciv_16to19_unemployed'],data['lfstatus_mciv_20to21_unemployed'],data['lfstatus_mciv_22to24_unemployed'],
               data['lfstatus_mciv_25to29_unemployed'],data['lfstatus_mciv_30to34_unemployed'],data['lfstatus_mciv_35to44_unemployed'],
               data['lfstatus_mciv_45to54_unemployed'],data['lfstatus_mciv_55to59_unemployed'],data['lfstatus_mciv_60to61_unemployed'],
               data['lfstatus_mciv_62to64_unemployed'],data['lfstatus_mciv_65to69_unemployed'],data['lfstatus_mciv_70to74_unemployed'],
               data['lfstatus_mciv_75+_unemployed'],data['lfstatus_fciv_16to19_unemployed'],data['lfstatus_fciv_20to21_unemployed'],
               data['lfstatus_fciv_22to24_unemployed'],data['lfstatus_fciv_25to29_unemployed'],data['lfstatus_fciv_30to34_unemployed'],
               data['lfstatus_fciv_35to44_unemployed'],data['lfstatus_fciv_45to54_unemployed'],data['lfstatus_fciv_55to59_unemployed'],
               data['lfstatus_fciv_60to61_unemployed'],data['lfstatus_fciv_62to64_unemployed'],data['lfstatus_fciv_65to69_unemployed'],
               data['lfstatus_fciv_70to74_unemployed'],data['lfstatus_fciv_75+_unemployed']]
data['Unemployed'] = sum(civunemployed)
totalemployment = data['Unemployed']+data['Employed']
data['Unemployment Rate'] = percent(data['Unemployed'], totalemployment)
cols = ['lfstatus_total_sexbyagebyemploymentstatus16+_series','lfstatus_mciv_16to19','lfstatus_mciv_16to19_employed','lfstatus_mciv_16to19_unemployed',
        'lfstatus_mciv_20to21','lfstatus_mciv_20to21_employed','lfstatus_mciv_20to21_unemployed','lfstatus_mciv_22to24','lfstatus_mciv_22to24_employed',
        'lfstatus_mciv_22to24_unemployed','lfstatus_mciv_25to29','lfstatus_mciv_25to29_employed','lfstatus_mciv_25to29_unemployed','lfstatus_mciv_30to34',
        'lfstatus_mciv_30to34_employed','lfstatus_mciv_30to34_unemployed','lfstatus_mciv_35to44','lfstatus_mciv_35to44_employed','lfstatus_mciv_35to44_unemployed',
        'lfstatus_mciv_45to54','lfstatus_mciv_45to54_employed','lfstatus_mciv_45to54_unemployed','lfstatus_mciv_55to59','lfstatus_mciv_55to59_employed',
        'lfstatus_mciv_55to59_unemployed','lfstatus_mciv_60to61','lfstatus_mciv_60to61_employed','lfstatus_mciv_60to61_unemployed','lfstatus_mciv_62to64',
        'lfstatus_mciv_62to64_employed','lfstatus_mciv_62to64_unemployed','lfstatus_mciv_65to69','lfstatus_mciv_65to69_employed','lfstatus_mciv_65to69_unemployed',
        'lfstatus_mciv_70to74','lfstatus_mciv_70to74_employed','lfstatus_mciv_70to74_unemployed','lfstatus_mciv_75+','lfstatus_mciv_75+_employed',
        'lfstatus_mciv_75+_unemployed','lfstatus_fciv_16to19','lfstatus_fciv_16to19_employed','lfstatus_fciv_16to19_unemployed','lfstatus_fciv_20to21',
        'lfstatus_fciv_20to21_employed','lfstatus_fciv_20to21_unemployed','lfstatus_fciv_22to24','lfstatus_fciv_22to24_employed','lfstatus_fciv_22to24_unemployed',
        'lfstatus_fciv_25to29','lfstatus_fciv_25to29_employed','lfstatus_fciv_25to29_unemployed','lfstatus_fciv_30to34','lfstatus_fciv_30to34_employed',
        'lfstatus_fciv_30to34_unemployed','lfstatus_fciv_35to44','lfstatus_fciv_35to44_employed','lfstatus_fciv_35to44_unemployed','lfstatus_fciv_45to54',
        'lfstatus_fciv_45to54_employed','lfstatus_fciv_45to54_unemployed','lfstatus_fciv_55to59','lfstatus_fciv_55to59_employed','lfstatus_fciv_55to59_unemployed',
        'lfstatus_fciv_60to61','lfstatus_fciv_60to61_employed','lfstatus_fciv_60to61_unemployed','lfstatus_fciv_62to64','lfstatus_fciv_62to64_employed',
        'lfstatus_fciv_62to64_unemployed','lfstatus_fciv_65to69','lfstatus_fciv_65to69_employed','lfstatus_fciv_65to69_unemployed','lfstatus_fciv_70to74',
        'lfstatus_fciv_70to74_employed','lfstatus_fciv_70to74_unemployed','lfstatus_fciv_75+','lfstatus_fciv_75+_employed','lfstatus_fciv_75+_unemployed']
data = data.drop(columns = cols)
#per capita income
data['Per Capita Income'] = data['percapita_income']
data = data.drop(columns = 'percapita_income')
#poverty
data['Poverty:Population for Whom Poverty Status is Determined'] = data['poverty_total_bysexbyage_series']
data['Poverty: Population Below Poverty Level'] = data['poverty_belowlevel']
data['Poverty%: Below Poverty Level'] = percent(data['Poverty: Population Below Poverty Level'], data['Poverty:Population for Whom Poverty Status is Determined'])
cols = ['poverty_total_bysexbyage_series','poverty_belowlevel']
data = data.drop(columns = cols)
#cost burden
data['CB:Total Housing Units'] = data['housingcost_total_selectedownercosts%hhincome_series']+data['housingcost_total_rent%hhincome_series']
allcostburden = [data['housingcost_%ownercost30to34.9_wmortgage'],data['housingcost_%ownercost35to39.9_wmortgage'],data['housingcost_%ownercost40to49.9_wmortgage'],
                 data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%ownercost30to34.9_womortgage'],data['housingcost_%ownercost35to39.9_womortgage'],
                 data['housingcost_%ownercost40to49.9_womortgage'],data['housingcost_%ownercost50+_womortgage'],data['housingcost_%rentercost30to34.9'],
                 data['housingcost_%rentercost35to39.9'],data['housingcost_%rentercost40to49.9'],data['housingcost_%rentercost50+']]
data['CB:Cost Burdened Housholds'] = sum(allcostburden)
data['CB:Renter Occupied Units'] = data['housingcost_total_rent%hhincome_series']
rentercostburden = [data['housingcost_%rentercost30to34.9'],data['housingcost_%rentercost35to39.9'],
                    data['housingcost_%rentercost40to49.9'],data['housingcost_%rentercost50+']]
data['CB:Cost Burdened Renters'] = sum(rentercostburden)
data['CB%:Cost Burdened Renters'] = percent(data['CB:Cost Burdened Renters'], data['CB:Total Housing Units'])
data['CB:Owner Occupied Units'] = data['housingcost_total_selectedownercosts%hhincome_series']
ownercostburden = [data['housingcost_%ownercost30to34.9_wmortgage'],data['housingcost_%ownercost35to39.9_wmortgage'],data['housingcost_%ownercost40to49.9_wmortgage'],
                   data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%ownercost30to34.9_womortgage'],data['housingcost_%ownercost35to39.9_womortgage'],
                   data['housingcost_%ownercost40to49.9_womortgage'],data['housingcost_%ownercost50+_womortgage']]
data['CB:Cost Burdened Homeowners'] = sum(ownercostburden)
data['CB%: Cost Burdened Homeowners'] = percent(data['CB:Cost Burdened Homeowners'], data['CB:Total Housing Units'])
severecostburden = [data['housingcost_%ownercost50+_womortgage'],data['housingcost_%ownercost50+_wmortgage'],data['housingcost_%rentercost50+']]
data['CB:Severe Cost Burdened Households'] = sum(severecostburden)
data['CB%:Severe Cost Burdened Households'] = percent(data['CB:Severe Cost Burdened Households'],data['CB:Total Housing Units'])
cols = ['housingcost_total_selectedownercosts%hhincome_series','housingcost_total%ownercostwmortgage_series','housingcost_%ownercost30to34.9_wmortgage',
        'housingcost_%ownercost35to39.9_wmortgage','housingcost_%ownercost40to49.9_wmortgage','housingcost_%ownercost50+_wmortgage',
        'housingcost_total%ownercostwomortgage_series','housingcost_%ownercost30to34.9_womortgage','housingcost_%ownercost35to39.9_womortgage',
        'housingcost_%ownercost40to49.9_womortgage','housingcost_%ownercost50+_womortgage','housingcost_total_rent%hhincome_series',
        'housingcost_%rentercost30to34.9','housingcost_%rentercost35to39.9','housingcost_%rentercost40to49.9','housingcost_%rentercost50+']
data = data.drop(columns = cols)
#total households
data['Total Households'] = data['units_allhousing']
data = data.drop(columns=['units_allhousing'])
#median home value
data['Median Home Value Owner Occupied with Mortgage'] = data['housingcost_medvalue_ownerocc_wmortgage']
data['Median Home Value Owner Occupied without Mortgage'] = data['housingcost_medvalue_ownerocc_womortgage']
cols = ['housingcost_medvalue_ownerocc_wmortgage','housingcost_medvalue_ownerocc_womortgage']
data = data.drop(columns = cols)
#median gross rent
data['Median Gross Rent'] = data['housingcost_mediangrossrent_renteroccupied']
data = data.drop(columns = 'housingcost_mediangrossrent_renteroccupied')
#tenure only drop
cols = ['tenure_total_series','tenure_owneroccunits','tenure_renteroccunits']
data = data.drop(columns = cols)
#occupancy only drop
cols = ['occupancy_total_series','occupancy_occupiedunits','occupancy_vacantunits']
data = data.drop(columns = cols)  
#units
data['Units:Total Series'] = data['units_total_series']
data['Units:1 Unit, Detached'] = data['units_one_detached']
data['Units%:1 Unit, Detached'] = percent(data['Units:1 Unit, Detached'], data['Units:Total Series'])
data['Units:1 Unit, Attached'] = data['units_one_attached']
data['Units%:1 Unit, Attached'] = percent(data['Units:1 Unit, Attached'], data['Units:Total Series'])
data['Units:2'] = data['units_two']
data['Units%:2'] = percent(data['Units:2'], data['Units:Total Series'])
data['Units:3 to 4'] = data['units_threetofour']
data['Units%:3 to 4'] = percent(data['Units:3 to 4'], data['Units:Total Series'])
data['Units:5 to 9'] = data['units_fivetonine']
data['Units%:5 to 9'] = percent(data['Units:5 to 9'], data['Units:Total Series'])
data['Units:10 to 19'] = data['units_tentonineteen']
data['Units%:10 to 19'] = percent(data['Units:10 to 19'], data['Units:Total Series'])
data['Units:20 to 49'] = data['units_twentytofortynine']
data['Units%:20 to 49'] = percent(data['Units:20 to 49'], data['Units:Total Series'])
data['Units:50 or More'] = data['units_fiftyormore']
data['Units%:50 or More'] = percent(data['Units:50 or More'], data['Units:Total Series'])
data['Units:Mobile Home'] = data['units_mobilehome']
data['Units%:Mobile Home'] = percent(data['Units:Mobile Home'], data['Units:Total Series'])
data['Units:Boat, RV, Van etc'] = data['units_boatrvvanetc']
data['Units%:Boat, RV, Van etc'] = percent(data['Units:Boat, RV, Van etc'], data['Units:Total Series'])
cols = ['units_total_series','units_one_detached','units_one_attached','units_two','units_threetofour','units_fivetonine','units_tentonineteen',
        'units_twentytofortynine','units_fiftyormore','units_mobilehome','units_boatrvvanetc']
data = data.drop(columns = cols)
#means of transportation to work
data['Transpo:Workers Commuting'] = data['commute_total_meansoftransportationtowork_series']
data['Transpo:Car, Truck, or Van'] = data['commute_cartruckvan']
data['Transpo%:Car, Truck, or Van'] = percent(data['Transpo:Car, Truck, or Van'],data['Transpo:Workers Commuting'])
data['Transpo:Public Transportation'] = data['commute_publictransportation']
data['Transpo%:Public Transportation'] = percent(data['Transpo:Public Transportation'],data['Transpo:Workers Commuting'])
data['Transpo:Bicycle'] = data['commute_bicycle']
data['Transpo%:Bicycle'] = percent(data['Transpo:Bicycle'],data['Transpo:Workers Commuting'])
data['Transpo:Walk'] = data['commute_walk']
data['Transpo%:Walk'] = percent(data['Transpo:Walk'],data['Transpo:Workers Commuting'])
data['Transpo:Worked From Home'] = data['commute_workedfromhome']
data['Transpo%:Worked From Home'] = percent(data['Transpo:Worked From Home'],data['Transpo:Workers Commuting'])
data['Transpo:Taxi, Motorcycle, Other'] = data['commute_taxicabmotorcycleother']
data['Transpo%:Taxi, Motorcycle, Other'] = percent(data['Transpo:Taxi, Motorcycle, Other'],data['Transpo:Workers Commuting'])
cols = ['commute_total_meansoftransportationtowork_series','commute_cartruckvan','commute_cartruckvan_drovealone','commute_cartruckvan_carpooled',
        'commute_cartruckvan_carpooled_2ppl','commute_cartruckvan_carpooled_3ppl','commute_cartruckvan_carpooled_4ormoreppl','commute_publictransportation',
        'commute_publictransportation_bus','commute_publictransportation_subwayorelevatedrail','commute_publictransportation_longdistancetrainorcommuterrail',
        'commute_publictransportation_lightrailstreetcarortrolley','commute_publictransportation_ferryboat','commute_bicycle','commute_walk',
        'commute_taxicabmotorcycleother','commute_workedfromhome']
data = data.drop(columns = cols)
#vehicle ownership
data['Vehicles:Households'] = data['vehicles_tenurebyvehicles_total_series']
data['Vehicles:None'] = data['vehicles_ownerocc_novehicle']+data['vehicles_renterocc_novehicle']
data['Vehicles%:None'] = percent(data['Vehicles:None'],data['Vehicles:Households'])
data['Vehicles:One'] = data['vehicles_ownerocc_1vehicle']+data['vehicles_renterocc_1vehicle']
data['Vehicles%:One'] = percent(data['Vehicles:One'],data['Vehicles:Households'])
data['Vehicles:Two'] = data['vehicles_ownerocc_2vehicles']+data['vehicles_renterocc_2vehicles']
data['Vehicles%:Two'] = percent(data['Vehicles:Two'],data['Vehicles:Households'])
data['Vehicles:Three'] = data['vehicles_ownerocc_3vehicles']+data['vehicles_renterocc_3vehicles']
data['Vehicles%:Three'] = percent(data['Vehicles:Three'],data['Vehicles:Households'])
data['Vehicles:Four'] = data['vehicles_ownerocc_4vehicles']+data['vehicles_renterocc_4vehicles']
data['Vehicles%:Four'] = percent(data['Vehicles:Four'],data['Vehicles:Households'])
data['Vehicles:Five or More'] = data['vehicles_ownerocc_5+vehicles']+data['vehicles_renterocc_5+vehicles']
data['Vehicles%:Five or More'] = percent(data['Vehicles:Five or More'],data['Vehicles:Households'])
cols = ['vehicles_tenurebyvehicles_total_series','vehicles_tenurebyvehicles_total_series','vehicles_ownerocc_total','vehicles_ownerocc_novehicle',
        'vehicles_ownerocc_1vehicle','vehicles_ownerocc_2vehicles','vehicles_ownerocc_3vehicles','vehicles_ownerocc_4vehicles','vehicles_ownerocc_5+vehicles',
        'vehicles_renterocc_total','vehicles_renterocc_novehicle','vehicles_renterocc_1vehicle','vehicles_renterocc_2vehicles','vehicles_renterocc_3vehicles',
        'vehicles_renterocc_4vehicles','vehicles_renterocc_5+vehicles']
data = data.drop(columns = cols)
#travel time by mode
data['Commute:Workers 16+ Not Working at Home'] = data['traveltimemode_series_total']  
data['Commute:Less than 10 Minutes'] = data['traveltimemode_lessthan10']
data['Commute:10 to 14 Minutes'] = data['traveltimemode_10to14']
data['Commute:15 to 19 Minutes'] = data['traveltimemode_15to19']
data['Commute:20 to 24 Minutes'] = data['traveltimemode_20to24']
data['Commute:25 to 29 Minutes'] = data['traveltimemode_25to29']
data['Commute:30 to 34 Minutes'] = data['traveltimemode_30to34']
data['Commute:35 to 44 Minutes'] = data['traveltimemode_35to44']
data['Commute:45 to 59 Minutes'] = data['traveltimemode_45to59']
data['Commute:60 or More Minutes'] = data['traveltimemode_60ormore']
data['Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes'] = data['traveltimemode_cartruckvan_drovealone_lessthan10']
data['Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes'] = data['traveltimemode_cartruckvan_drovealone_10to14']
data['Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes'] = data['traveltimemode_cartruckvan_drovealone_15to19']
data['Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes'] = data['traveltimemode_cartruckvan_drovealone_20to24']
data['Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes'] = data['traveltimemode_cartruckvan_drovealone_25to29']
data['Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes'] = data['traveltimemode_cartruckvan_drovealone_30to34']
data['Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes'] = data['traveltimemode_cartruckvan_drovealone_35to44']
data['Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes'] = data['traveltimemode_cartruckvan_drovealone_45to59']
data['Commute:Car, Truck, Van Drove Alone:60 or More Minutes'] = data['traveltimemode_cartruckvan_drovealone_60ormore']
data['Commute:Car, Truck, Van Carpooled:Less than 10 Minutes'] = data['traveltimemode_cartruckvan_carpooled_lessthan10']
data['Commute:Car, Truck, Van Carpooled:10 to 14 Minutes'] = data['traveltimemode_cartruckvan_carpooled_10to14']
data['Commute:Car, Truck, Van Carpooled:15 to 19 Minutes'] = data['traveltimemode_cartruckvan_carpooled_15to19']
data['Commute:Car, Truck, Van Carpooled:20 to 24 Minutes'] = data['traveltimemode_cartruckvan_carpooled_20to24']
data['Commute:Car, Truck, Van Carpooled:25 to 29 Minutes'] = data['traveltimemode_cartruckvan_carpooled_25to29']
data['Commute:Car, Truck, Van Carpooled:30 to 34 Minutes'] = data['traveltimemode_cartruckvan_carpooled_30to34']
data['Commute:Car, Truck, Van Carpooled:35 to 44 Minutes'] = data['traveltimemode_cartruckvan_carpooled_35to44']
data['Commute:Car, Truck, Van Carpooled:45 to 59 Minutes'] = data['traveltimemode_cartruckvan_carpooled_45to59']
data['Commute:Car, Truck, Van Carpooled:Less than 10 Minutes'] = data['traveltimemode_cartruckvan_carpooled_60ormore']
data['Commute:Car, Truck, Van Carpooled:60 or More Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_lessthan10']
data['Commute:Car, Truck, Van Carpooled:10 to 14 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_10to14']
data['Commute:Car, Truck, Van Carpooled:15 to 19 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_15to19']
data['Commute:Car, Truck, Van Carpooled:20 to 24 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_20to24']
data['Commute:Car, Truck, Van Carpooled:25 to 29 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_25to29']
data['Commute:Car, Truck, Van Carpooled:30 to 34 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_30to34']
data['Commute:Car, Truck, Van Carpooled:35 to 44 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_35to44']
data['Commute:Car, Truck, Van Carpooled:45 to 59 Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_45to59']
data['Commute:Car, Truck, Van Carpooled:60 or More Minutes'] = data['traveltimemode_publictransportationexcludingtaxi_60ormore']
data['Commute:Car, Truck, Van Carpooled:60 or More Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedother_lessthan10']
data['Commute:Car, Truck, Van Carpooled:10 to 14 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_10to14']
data['Commute:Car, Truck, Van Carpooled:15 to 19 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_15to19']
data['Commute:Car, Truck, Van Carpooled:20 to 24 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_20to24']
data['Commute:Car, Truck, Van Carpooled:25 to 29 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_25to29']
data['Commute:Car, Truck, Van Carpooled:30 to 34 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_30to34']
data['Commute:Car, Truck, Van Carpooled:35 to 44 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_35to44']
data['Commute:Car, Truck, Van Carpooled:45 to 59 Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_45to59']
data['Commute:Car, Truck, Van Carpooled:60 or More Minutes'] = data['traveltimemode_taximotorcyclebicyclewalkedorother_60ormore']
cols = ['traveltimemode_series_total','traveltimemode_lessthan10','traveltimemode_10to14','traveltimemode_15to19','traveltimemode_20to24','traveltimemode_25to29',
        'traveltimemode_30to34','traveltimemode_35to44','traveltimemode_45to59','traveltimemode_60ormore','traveltimemode_cartruckvan_drovealone',
        'traveltimemode_cartruckvan_drovealone_lessthan10','traveltimemode_cartruckvan_drovealone_10to14','traveltimemode_cartruckvan_drovealone_15to19',
        'traveltimemode_cartruckvan_drovealone_20to24','traveltimemode_cartruckvan_drovealone_25to29','traveltimemode_cartruckvan_drovealone_30to34',
        'traveltimemode_cartruckvan_drovealone_35to44','traveltimemode_cartruckvan_drovealone_45to59','traveltimemode_cartruckvan_drovealone_60ormore',
        'traveltimemode_cartruckvan_carpooled','traveltimemode_cartruckvan_carpooled_lessthan10','traveltimemode_cartruckvan_carpooled_10to14',
        'traveltimemode_cartruckvan_carpooled_15to19','traveltimemode_cartruckvan_carpooled_20to24','traveltimemode_cartruckvan_carpooled_25to29',
        'traveltimemode_cartruckvan_carpooled_30to34','traveltimemode_cartruckvan_carpooled_35to44','traveltimemode_cartruckvan_carpooled_45to59',
        'traveltimemode_cartruckvan_carpooled_60ormore','traveltimemode_publictransportationexcludingtaxi',
        'traveltimemode_publictransportationexcludingtaxi_lessthan10','traveltimemode_publictransportationexcludingtaxi_10to14',
        'traveltimemode_publictransportationexcludingtaxi_15to19','traveltimemode_publictransportationexcludingtaxi_20to24',
        'traveltimemode_publictransportationexcludingtaxi_25to29','traveltimemode_publictransportationexcludingtaxi_30to34',
        'traveltimemode_publictransportationexcludingtaxi_35to44','traveltimemode_publictransportationexcludingtaxi_45to59',
        'traveltimemode_publictransportationexcludingtaxi_60ormore','traveltimemode_taximotorcyclebicyclewalkedother',
        'traveltimemode_taximotorcyclebicyclewalkedother_lessthan10','traveltimemode_taximotorcyclebicyclewalkedorother_10to14',
        'traveltimemode_taximotorcyclebicyclewalkedorother_15to19','traveltimemode_taximotorcyclebicyclewalkedorother_20to24',
        'traveltimemode_taximotorcyclebicyclewalkedorother_25to29','traveltimemode_taximotorcyclebicyclewalkedorother_30to34',
        'traveltimemode_taximotorcyclebicyclewalkedorother_35to44','traveltimemode_taximotorcyclebicyclewalkedorother_45to59',
        'traveltimemode_taximotorcyclebicyclewalkedorother_60ormore']
data = data.drop(columns = cols)
#veteran
data['Vet:Population 18+'] = data['veteran_total_series']
data['Vet:Veteran'] = data['veteran_total_veteran']
data['Vet%:Veteran'] = percent(data['Vet:Veteran'],data['Vet:Population 18+'])
data['Vet:Nonveteran'] = data['veteran_total_nonveteran']
data['Vet%:Nonveteran'] = percent(data['Vet:Nonveteran'],data['Vet:Population 18+'])
total1864 = [data['veteran_m18to34'],data['veteran_m35to54'],data['veteran_m55to64'],data['veteran_f18to34'],data['veteran_f35to54'],data['veteran_f55to64']]
vet1864 = [data['veteran_m18to34_veteran'],data['veteran_m35to54_veteran'],data['veteran_m55to64_veteran'],data['veteran_f18to34_veteran'],
           data['veteran_f35to54_veteran'],data['veteran_f55to64_veteran']]
data['Vet:Veteran 18 to 64'] = sum(vet1864)
data['Vet%:Veterans who are 18 to 64'] = percent(data['Vet:Veteran 18 to 64'], sum(total1864))
total65up = [data['veteran_m65to74'],data['veteran_m75+'],data['veteran_f65to74'],data['veteran_f75+']]
vet65up = [data['veteran_m65to74_veteran'],data['veteran_m75+_veteran'],data['veteran_f65to74_veteran'],data['veteran_f75+_veteran']]
data['Vet:Veteran 65 and Older'] = sum(vet65up)
data['Vet%:Veterans who are 65 and Older'] = percent(data['Vet:Veteran 65 and Older'], sum(total65up))
nonvet1864 = [data['veteran_m18to34_nonveteran'],data['veteran_m35to54_nonveteran'],data['veteran_m55to64_nonveteran'],data['veteran_f18to34_nonveteran'],
           data['veteran_f35to54_nonveteran'],data['veteran_f55to64_nonveteran']]
data['Vet:Nonveteran 18 to 64'] = sum(nonvet1864)
nonvet65up = [data['veteran_m65to74_nonveteran'],data['veteran_m75+_nonveteran'],data['veteran_f65to74_nonveteran'],data['veteran_f75+_nonveteran']]
data['Vet:Nonveteran 65 and Older'] = sum(vet65up)
cols = ['veteran_total_series','veteran_total_veteran','veteran_total_nonveteran','veteran_male','veteran_m_veteran','veteran_m_nonveteran','veteran_m18to34',
        'veteran_m18to34_veteran','veteran_m18to34_nonveteran','veteran_m35to54','veteran_m35to54_veteran','veteran_m35to54_nonveteran','veteran_m55to64',
        'veteran_m55to64_veteran','veteran_m55to64_nonveteran','veteran_m65to74','veteran_m65to74_veteran','veteran_m65to74_nonveteran','veteran_m75+',
        'veteran_m75+_veteran','veteran_m75+_nonveteran','veteran_female','veteran_f_veteran','veteran_f_nonveteran','veteran_f18to34','veteran_f18to34_veteran',
        'veteran_f18to34_nonveteran','veteran_f35to54','veteran_f35to54_veteran','veteran_f35to54_nonveteran','veteran_f55to64','veteran_f55to64_veteran',
        'veteran_f55to64_nonveteran','veteran_f65to74','veteran_f65to74_veteran','veteran_f65to74_nonveteran','veteran_f75+','veteran_f75+_veteran',
        'veteran_f75+_nonveteran']
data = data.drop(columns = cols)
#geographic mobility
data['GeoMobility:Total'] = data['geo_total_series']
data['GeoMobility:Same House'] = data['geo_samehouse_total']
data['GeoMobility%:Same House'] = percent(data['GeoMobility:Same House'],data['GeoMobility:Total'])
data['GeoMobility:Moved Same County'] = data['geo_movedsamecounty_total']
data['GeoMobility%:Moved Same County'] = percent(data['GeoMobility:Moved Same County'],data['GeoMobility:Total'])
data['GeoMobility:Moved Different County Same State'] = data['geo_moveddifferentcountysamestate_total']
data['GeoMobility%:Moved Different County Same State'] = percent(data['GeoMobility:Moved Different County Same State'],data['GeoMobility:Total'])
data['GeoMobility:Moved Different State'] = data['geo_moveddifferentstate_total']
data['GeoMobility%:Moved Different State'] = percent(data['GeoMobility:Moved Different State'],data['GeoMobility:Total'])
data['GeoMobility:Moved From Abroad'] = data['geo_movedabroad_total']
data['GeoMobility%:Moved From Abroad'] = percent(data['GeoMobility:Moved From Abroad'],data['GeoMobility:Total'])
cols = ['geo_total_series','geo_1to4_total','geo_5to17_total','geo_18to19_total','geo_20to24_total','geo_25to29_total','geo_30to34_total','geo_35to39_total',
        'geo_40to44_total','geo_45to49_total','geo_50to54_total','geo_55to59_total','geo_60to64_total','geo_65to69_total','geo_70to74_total','geo_75+_total',
        'geo_samehouse_total','geo_55to59_samehouse','geo_60to64_samehouse','geo_65to69_samehouse','geo_70to74_samehouse','geo_75+_samehouse',
        'geo_movedsamecounty_total','geo_55to59_movedsamecounty','geo_60to64_movedsamecounty','geo_65to69_movedsamecounty','geo_70to74_movedsamecounty',
        'geo_75+_movedsamecounty','geo_moveddifferentcountysamestate_total','geo_55to59_moveddifferentcountysamestate','geo_60to64_moveddifferentcountysamestate',
        'geo_65to69_moveddifferentcountysamestate','geo_70to74_moveddifferentcountysamestate','geo_75+_moveddifferentcountysamestate','geo_moveddifferentstate_total',
        'geo_55to59_moveddifferentstate','geo_60to64_moveddifferentstate','geo_65to69_moveddifferentstate','geo_70to74_moveddifferentstate',
        'geo_75+_moveddifferentstate','geo_movedabroad_total','geo_55to59_movedabroad','geo_60to64_movedabroad','geo_65to69_movedabroad','geo_70to74_movedabroad',
        'geo_75+_movedabroad']
data = data.drop(columns = cols)
#foreign born citizenship
data['ForeignBorn:Total Population'] = data['fb_total_series']
data['ForeignBorn:Native Born'] = data['fb_nativeborn']
data['ForeignBorn:Foreign Born'] = data['fb_foreignborn']
data['ForeignBorn%:Foreign Born'] = percent(data['ForeignBorn:Foreign Born'], data['ForeignBorn:Total Population'])
data['ForeignBorn:Foreign Born Naturalized Citizen'] = data['fb_foreignborn_naturalizeduscitizen']
data['ForeignBorn%:Foreign Born Population that are Naturalized Citizen'] = percent(data['ForeignBorn:Foreign Born Naturalized Citizen'],
                                                                                    data['ForeignBorn:Foreign Born'])
data['ForeignBorn:Foreign Born Not a Citizen'] = data['fb_foreignborn_notauscitizen']
data['ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen'] = percent(data['ForeignBorn:Foreign Born Not a Citizen'],
                                                                                        data['ForeignBorn:Foreign Born'])
cols = ['fb_total_series','fb_nativeborn','fb_foreignborn','fb_foreignborn_naturalizeduscitizen','fb_foreignborn_notauscitizen']
data = data.drop(columns = cols)
#foreign born origin
data['Foreign Born Population'] = data['foreignborn_total']
data['ForeignBorn:Europe'] = data['fb_europe']
data['ForeignBorn:Asia'] = data['fb_asia']
data['ForeignBorn:Africa'] = data['fb_africa']
data['ForeignBorn:Oceania'] = data['fb_oceania']
data['ForeignBorn:Central & South America, Caribbean'] = data['fb_americas']
data['ForeignBorn:Canada & Other Northern American'] = data['fb_am_northern']
cols = ['foreignborn_total','fb_europe','fb_asia','fb_africa','fb_oceania','fb_americas','fb_am_latinamerica','fb_am_northern']
data = data.drop(columns = cols)
#language spoken at home by ability to speak english
data['Language:Population 5 and Older'] = data['language_languagebyabilitytospeakenglish_total5+_series']
onlyenglish = [data['language_speakonlyenglish_5to17'],data['language_speakonlyenglish_18to64'],data['language_speakonlyenglish_65+']]
data['Language:Speak Only English'] = sum(onlyenglish)
data['Language%:Speak Only English'] = percent(data['Language:Speak Only English'],data['Language:Population 5 and Older'])
#spanish
speakspanish = [data['language_speakspanish_5to17'],data['language_speakspanish_18to64'],data['language_speakspanish_65+']]
data['Language:Speak Spanish'] = sum(speakspanish)
spanishverywell = [data['language_speakspanish_speakenglishverywell_5to17'],data['language_speakspanish_speakenglishverywell_18to64'],
                   data['language_speakspanish_speakenglishverywell_65+']]
data['Language:Spanish:Speak English Very Well'] = sum(spanishverywell)
spanishwell = [data['language_speakspanish_speakenglishwell_5to17'],data['language_speakspanish_speakenglishwell_18to64'],
                   data['language_speakspanish_speakenglishwell_65+']]
data['Language:Spanish:Speak English Well'] = sum(spanishwell)
spanishnotwell = [data['language_speakspanish_speakenglishnotwell_5to17'],data['language_speakspanish_speakenglishnotwell_18to64'],
                   data['language_speakspanish_speakenglishnotwell_65+']]
data['Language:Spanish:Speak English Not Well'] = sum(spanishnotwell)
spanishnotatall = [data['language_speakspanish_speakenglishnotatall_5to17'],data['language_speakspanish_speakenglishnotatall_18to64'],
                   data['language_speakspanish_speakenglishnotatall_65+']]
data['Language:Spanish:Speak English Not At All'] = sum(spanishnotatall)
#otherindoeuropeanlanguage
speakotherindoeuro = [data['language_speakotherindoeuro_5to17'],data['language_speakotherindoeuro_18to64'],data['language_speakotherindoeuro_65+']]
data['Language:Speak Other Indo-European Language'] = sum(speakotherindoeuro)
otherindoeuroverywell = [data['language_speakotherindoeuro_speakenglishverywell_5to17'],data['language_speakotherindoeuro_speakenglishverywell_18to64'],
                   data['language_speakotherindoeuro_speakenglishverywell_65+']]
data['Language:Other Indo-European:Speak English Very Well'] = sum(otherindoeuroverywell)
otherindoeurowell = [data['language_speakotherindoeuro_speakenglishwell_5to17'],data['language_speakotherindoeuro_speakenglishwell_18to64'],
                   data['language_speakotherindoeuro_speakenglishwell_65+']]
data['Language:Other Indo-European:Speak English Well'] = sum(otherindoeurowell)
otherindoeuronotwell = [data['language_speakotherindoeuro_speakenglishnotwell_5to17'],data['language_speakotherindoeuro_speakenglishnotwell_18to64'],
                   data['language_speakotherindoeuro_speakenglishnotwell_65+']]
data['Language:Other Indo-European:Speak English Not Well'] = sum(otherindoeuronotwell)
otherindoeuronotatall = [data['language_speakotherindoeuro_speakenglishnotatall_5to17'],data['language_speakotherindoeuro_speakenglishnotatall_18to64'],
                   data['language_speakotherindoeuro_speakenglishnotatall_65+']]
data['Language:Other Indo-European:Speak English Not At All'] = sum(otherindoeuronotatall)
#asianpacificislandlanguage
speakasianpacificisland = [data['language_speakasianpacificisland_5to17'],data['language_speakasianpacificisland_18to64'],data['language_speakasianpacificisland_65+']]
data['Language:Speak Asian or Pacific Island Language'] = sum(speakasianpacificisland)
asianpacificislandverywell = [data['language_speakasianpacificisland_speakenglishverywell_5to17'],data['language_speakasianpacificisland_speakenglishverywell_18to64'],
                   data['language_speakasianpacificisland_speakenglishverywell_65+']]
data['Language:Asian or Pacific Island:Speak English Very Well'] = sum(asianpacificislandverywell)
asianpacificislandwell = [data['language_speakasianpacificisland_speakenglishwell_5to17'],data['language_speakasianpacificisland_speakenglishwell_18to64'],
                   data['language_speakasianpacificisland_speakenglishwell_65+']]
data['Language:Asian or Pacific Island:Speak English Well'] = sum(asianpacificislandwell)
asianpacificislandnotwell = [data['language_speakasianpacificisland_speakenglishnotwell_5to17'],data['language_speakasianpacificisland_speakenglishnotwell_18to64'],
                   data['language_speakasianpacificisland_speakenglishnotwell_65+']]
data['Language:Asian or Pacific Island:Speak English Not Well'] = sum(asianpacificislandnotwell)
asianpacificislandnotatall = [data['language_speakasianpacificisland_speakenglishnotatall_5to17'],data['language_speakasianpacificisland_speakenglishnotatall_18to64'],
                   data['language_speakasianpacificisland_speakenglishnotatall_65+']]
data['Language:Asian or Pacific Island:Speak English Not At All'] = sum(asianpacificislandnotatall)
#other
speakother = [data['language_speakother_5to17'],data['language_speakother_18to64'],data['language_speakother_65+']]
data['Language:Speak Other Language'] = sum(speakother)
otherverywell = [data['language_speakother_speakenglishverywell_5to17'],data['language_speakother_speakenglishverywell_18to64'],
                   data['language_speakother_speakenglishverywell_65+']]
data['Language:Other:Speak English Very Well'] = sum(otherverywell)
otherwell = [data['language_speakother_speakenglishwell_5to17'],data['language_speakother_speakenglishwell_18to64'],
                   data['language_speakother_speakenglishwell_65+']]
data['Language:Other:Speak English Well'] = sum(otherwell)
othernotwell = [data['language_speakother_speakenglishnotwell_5to17'],data['language_speakother_speakenglishnotwell_18to64'],
                   data['language_speakother_speakenglishnotwell_65+']]
data['Language:Other:Speak English Not Well'] = sum(othernotwell)
othernotatall = [data['language_speakother_speakenglishnotatall_5to17'],data['language_speakother_speakenglishnotatall_18to64'],
                   data['language_speakother_speakenglishnotatall_65+']]
data['Language:Other:Speak English Not At All'] = sum(othernotatall)
languagenotenglish = [data['Language:Speak Spanish'],data['Language:Speak Other Indo-European Language'],data['Language:Speak Asian or Pacific Island Language'],
                     data['Language:Speak Other Language']]
data['Language%:Speak Language Besides English'] = percent(sum(languagenotenglish),data['Language:Population 5 and Older'])
englishnotwelloratall = [data['Language:Spanish:Speak English Not Well'],data['Language:Spanish:Speak English Not At All'],
                        data['Language:Other Indo-European:Speak English Not Well'],data['Language:Other Indo-European:Speak English Not At All'],
                        data['Language:Asian or Pacific Island:Speak English Not Well'],data['Language:Asian or Pacific Island:Speak English Not At All'],
                        data['Language:Other:Speak English Not Well'],data['Language:Other:Speak English Not At All']]
data['Language%:Of Those that Speak Another Language and Speak English Not Well or At All'] = percent(sum(englishnotwelloratall),sum(languagenotenglish))
cols = ['language_languagebyabilitytospeakenglish_total5+_series','language_total_5to17','language_speakonlyenglish_5to17','language_speakspanish_5to17',
        'language_speakspanish_speakenglishverywell_5to17','language_speakspanish_speakenglishwell_5to17','language_speakspanish_speakenglishnotwell_5to17',
        'language_speakspanish_speakenglishnotatall_5to17','language_speakotherindoeuro_5to17','language_speakotherindoeuro_speakenglishverywell_5to17',
        'language_speakotherindoeuro_speakenglishwell_5to17','language_speakotherindoeuro_speakenglishnotwell_5to17',
        'language_speakotherindoeuro_speakenglishnotatall_5to17','language_speakasianpacificisland_5to17',
        'language_speakasianpacificisland_speakenglishverywell_5to17','language_speakasianpacificisland_speakenglishwell_5to17',
        'language_speakasianpacificisland_speakenglishnotwell_5to17','language_speakasianpacificisland_speakenglishnotatall_5to17','language_speakother_5to17',
        'language_speakother_speakenglishverywell_5to17','language_speakother_speakenglishwell_5to17','language_speakother_speakenglishnotwell_5to17',
        'language_speakother_speakenglishnotatall_5to17','language_total_18to64','language_speakonlyenglish_18to64','language_speakspanish_18to64',
        'language_speakspanish_speakenglishverywell_18to64','language_speakspanish_speakenglishwell_18to64','language_speakspanish_speakenglishnotwell_18to64',
        'language_speakspanish_speakenglishnotatall_18to64','language_speakotherindoeuro_18to64','language_speakotherindoeuro_speakenglishverywell_18to64',
        'language_speakotherindoeuro_speakenglishwell_18to64','language_speakotherindoeuro_speakenglishnotwell_18to64',
        'language_speakotherindoeuro_speakenglishnotatall_18to64','language_speakasianpacificisland_18to64',
        'language_speakasianpacificisland_speakenglishverywell_18to64','language_speakasianpacificisland_speakenglishwell_18to64',
        'language_speakasianpacificisland_speakenglishnotwell_18to64','language_speakasianpacificisland_speakenglishnotatall_18to64',
        'language_speakother_18to64','language_speakother_speakenglishverywell_18to64','language_speakother_speakenglishwell_18to64',
        'language_speakother_speakenglishnotwell_18to64','language_speakother_speakenglishnotatall_18to64','language_total_65+','language_speakonlyenglish_65+',
        'language_speakspanish_65+','language_speakspanish_speakenglishverywell_65+','language_speakspanish_speakenglishwell_65+',
        'language_speakspanish_speakenglishnotwell_65+','language_speakspanish_speakenglishnotatall_65+','language_speakotherindoeuro_65+',
        'language_speakotherindoeuro_speakenglishverywell_65+','language_speakotherindoeuro_speakenglishwell_65+',
        'language_speakotherindoeuro_speakenglishnotwell_65+','language_speakotherindoeuro_speakenglishnotatall_65+','language_speakasianpacificisland_65+',
        'language_speakasianpacificisland_speakenglishverywell_65+','language_speakasianpacificisland_speakenglishwell_65+',
        'language_speakasianpacificisland_speakenglishnotwell_65+','language_speakasianpacificisland_speakenglishnotatall_65+','language_speakother_65+',
        'language_speakother_speakenglishverywell_65+','language_speakother_speakenglishwell_65+','language_speakother_speakenglishnotwell_65+',
        'language_speakother_speakenglishnotatall_65+']
data = data.drop(columns = cols)
data = data.drop(columns = ['Population','Total Households','StateFIPS', 'GeoFIPS'])
data.head()

,NAME,Median Household Income,HHIncome:Total Households,"HHIncome:Less than 10,000","HHIncome%:Less than 10,000","HHIncome:10 to 14,999","HHIncome%:10 to 14,999","HHIncome:15 to 19,999","HHIncome%:15 to 19,999","HHIncome:20 to 24,999","HHIncome%:20 to 24,999","HHIncome:25 to 29,999","HHIncome%:25 to 29,999","HHIncome:30 to 34,999","HHIncome:%30 to 34,999","HHIncome:35 to 39,999","HHIncome%:35 to 39,999","HHIncome:40 to 44,999","HHIncome%:40 to 44,999","HHIncome:45 to 49,999","HHIncome%:45 to 49,999","HHIncome:50 to 59,999","HHIncome%:50 to 59,999","HHIncome:60 to 74,999","HHIncome%:60 to 74,999","HHIncome:75 to 99,999","HHIncome%:75 to 99,999","HHIncome:100 to 124,999","HHIncome%:100 to 124,999","HHIncome:125 to 149,999","HHIncome%:125 to 149,999","HHIncome:150 to 199,999","HHIncome%:150 to 199,999",HHIncome:200K or More,HHIncome%:200K or More,Ed:Population 25+ Educational Attainment,Ed:Less than High School,Ed%:Less than High School,Ed:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency,Ed%:High School Graduate or More,Ed:Some College,Ed%:Some College,Ed%:Some College or More,Ed:Associates,Ed%:Associates,Ed:Bachelors,Ed%:Bachelors,Ed%:Bachelors or More,Ed:Masters,Ed%:Masters,Ed%:Masters or More,Ed:Professional School Degree,Ed%:Professional School Degree,Ed%:Professional School Degree or More,Ed:Doctorate Degree,Ed%:Doctorate Degree,Ind:Employed Civilians 16+,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining",Ind:Construction,Ind%:Construction,Ind:Manufacturing,Ind%:Manufacturing,Ind:Wholesale Trade,Ind%:Wholesale Trade,Ind:Retail Trade,Ind%:Retail Trade,"Ind:Transportation and Warehousing, Utilities","Ind%:Transportation and Warehousing, Utilities",Ind:Information,Ind%:Information,"Ind:Finance, Insurance, Real Estate and Rental and Leasing","Ind%:Finance, Insurance, Real Estate and Rental and Leasing","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind:Educational, Health and Social Services","Ind%:Educational, Health and Social Services","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services",Ind:Other Services (Except Public Administration),Ind%:Other Services (Except Public Administration),Ind:Public Administration,Ind%:Public Administration,Employed Civilians 16+ Occupational,"Occ:Management, Business, and Financial Operations","Occ%:Management, Business, and Financial Operations",Occ:Professional and Related,Occ%:Professional and Related,Occ:Healthcare Support,Occ%:Healthcare Support,Occ:Protective Services,Occ%:Protective Services,Occ:Food Preparation and Serving Related,Occ%:Food Preparation and Serving Related,Occ:Building and Grounds Cleaning and Maintenance,Occ%:Building and Grounds Cleaning and Maintenance,Occ:Personal Care and Service,Occ%:Personal Care and Service,Occ:Sales and Related,Occ%:Sales and Related,Occ:Office and Administrative Support,Occ%:Office and Administrative Support,"Occ:Farming, Fishing, and Forestry","Occ%:Farming, Fishing, and Forestry","Occ:Construction, Extraction, and Maintenance","Occ%:Construction, Extraction, and Maintenance",Occ:Production,Occ%:Production,Occ:Transportation and Material Moving,Occ%:Transportation and Material Moving,Sector: Total Workers,Sector:Private,Sector%:Private,Sector:Public,Sector%:Public,Sector:Self-Employed,Sector%:Self-Employed,Sector:Non-Profit,Sector%:Non-Profit,Sector:Unpaid Family Workers,Sector%:Unpaid Family Workers,Employed,Unemployed,Unemployment Rate,Per Capita Income,Poverty:Population for Whom Poverty Status is Determined,Poverty: Population Below Poverty Level,Poverty%: Below Poverty Level,CB:Total Housing Units,CB:Cost Burdened Housholds,CB:Renter Occupied Units,CB:Cost Burdened Renters,CB%:Cost Burdened Renters,CB:Owner Occupied Units,CB:Cost Burdened Homeowners,CB%: Cost Burdened Homeowners,CB:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households,Median Home Value Owner Occupied with Mortgage,Median Home Value Owner Occupied without Mortgage,Median Gross Rent,Units:Total Series,"Units:1 Unit, Detached","Units%:1 Unit, Detached","Units:1 Unit, Attached","Units%:1 Unit, Attached",Units:2,Units%:2,Units:3 to 4,Units%:3 to 4,Units:5 to 9,Units%:5 to 9,Units:10 to 19,Units%:10 to 19,Units:20 to 49,Units%:20 to 49,Units:50 or More,Units%:50 or More,Units:Mobile Home,Units%:Mobile Home,"Units:Boat, RV, Van etc","Units%:Boat, RV, Van etc",Transpo:Workers Commuting,"Transpo:Car, Truck, or Van","Transpo%:Car, Truck, or Van",Transpo:Public Transportation,Transpo%:Public Transportation,Transpo:Bicycle,Transpo%:Bicycle,Transpo:Walk,Transpo%:Walk,Transpo:Worked From Home,Transpo%:Worked From Home,"Transpo:Taxi, Motorcycle, Other","Transpo%:Taxi, Motorcycle, Other",Vehicles:Households,Vehicles:None,Vehicles%:None,Vehicles:One,Vehicles%:One,Vehicles:Two,Vehicles%:Two,Vehicles:Three,Vehicles%:Three,Vehicles:Four,Vehicles%:Four,Vehicles:Five or More,Vehicles%:Five or More,Commute:Workers 16+ Not Working at Home,Commute:Less than 10 Minutes,Commute:10 to 14 Minutes,Commute:15 to 19 Minutes,Commute:20 to 24 Minutes,Commute:25 to 29 Minutes,Commute:30 to 34 Minutes,Commute:35 to 44 Minutes,Commute:45 to 59 Minutes,Commute:60 or More Minutes,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes","Commute:Car, Truck, Van Drove Alone:60 or More Minutes","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes","Commute:Car, Truck, Van Carpooled:60 or More Minutes",Vet:Population 18+,Vet:Veteran,Vet%:Veteran,Vet:Nonveteran,Vet%:Nonveteran,Vet:Veteran 18 to 64,Vet%:Veterans who are 18 to 64,Vet:Veteran 65 and Older,Vet%:Veterans who are 65 and Older,Vet:Nonveteran 18 to 64,Vet:Nonveteran 65 and Older,GeoMobility:Total,GeoMobility:Same House,GeoMobility%:Same House,GeoMobility:Moved Same County,GeoMobility%:Moved Same County,GeoMobility:Moved Different County Same State,GeoMobility%:Moved Different County Same State,GeoMobility:Moved Different State,GeoMobility%:Moved Different State,GeoMobility:Moved From Abroad,GeoMobility%:Moved From Abroad,ForeignBorn:Total Population,ForeignBorn:Native Born,ForeignBorn:Foreign Born,ForeignBorn%:Foreign Born,ForeignBorn:Foreign Born Naturalized Citizen,ForeignBorn%:Foreign Born Population that are Naturalized Citizen,ForeignBorn:Foreign Born Not a Citizen,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen,Foreign Born Population,ForeignBorn:Europe,ForeignBorn:Asia,ForeignBorn:Africa,ForeignBorn:Oceania,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Canada & Other Northern American,Language:Population 5 and Older,Language:Speak Only English,Language%:Speak Only English,Language:Speak Spanish,Language:Spanish:Speak English Very Well,Language:Spanish:Speak English Well,Language:Spanish:Speak English Not Well,Language:Spanish:Speak English Not At All,Language:Speak Other Indo-European Language,Language:Other Indo-European:Speak English Very Well,Language:Other Indo-European:Speak English Well,Language:Other Indo-European:Speak English Not Well,Language:Other Indo-European:Speak English Not At All,Language:Speak Asian or Pacific Island Language,Language:Asian or Pacific Island:Speak English Very Well,Language:Asian or Pacific Island:Speak English Well,Language:Asian or Pacific Island:Speak English Not Well,Language:Asian or Pacific Island:Speak English Not At All,Language:Speak Other Language,Language:Other:Speak English Very Well,Language:Other:Speak English Well,Language:Other:Speak English Not Well,Language:Other:Speak English Not At All,Language%:Speak Language Besides English,Language%:Of Those that Speak Another Language and Speak English Not Well or At All
0,"Cheatham County, Tennessee",52585.0,14198.0,596.0,4.197774,709.0,4.993661,715.0,5.035921,839.0,5.909283,748.0,5.268348,731.0,5.148612,749.0,5.275391,686.0,4.831666,970.0,6.831948,1205.0,8.487111,1823.0,12.839837,2101.0,14.797859,1210.0,8.522327,424.0,2.986336,432.0,3.042682,260.0,1.831244,25952.0,4788.0,18.449445,9677.0,37.288070,81.550555,5186.0,19.983046,24.356439,1659.0,6.392571,3363.0,12.958539,17.886868,879.0,3.387022,4.928329,285.0,1.098181,1.541307,115.0,0.443126,19066.0,176.0,0.923109,2646.0,13.878108,1894.0,9.933914,797.0,4.180216,2177.0,11.418231,894.0,4.688975,553.0,2.900451,1193.0,6.257212,1883.0,9.876219,3510.0,18.409735,1286.0,6.744991,1027.0,5.386552,1030.0,5.402287,19066.0,2765.0,14.502255,4337.0,22.747299,357.0,1.872443,324.0,1.699360,683.0,3.582293,824.0,4.321829,473.0,2.480856,2194.0,11.507395,3144.0,16.490087,68.0,0.356656,2749.0,14.418336,1026.0,5.381307,1206.0,6.325396,18473.0,12649.0,68.472906,2388.0,12.926975,2853.0,15.444162,1204.0,6.517620,43.0,0.232772,19066.0,1229.0,6.055679,24392.0,37813.0,3517.0,9.301034,14198.0,4032.0,2715.0,1259.0,8.867446,11483.0,2773.0,19.530920,1290.0,9.085787,163700.0,137200.0,763.0,15425.0,12298.0,79.727715,207.0,1.341977,144.0,0.933549,217.0,1.406807,172.0,1.115073,231.0,1.497569,82.0,0.531605,39.0,0.252836,2035.0,13.192869,0.0,0.000000,18473.0,17031.0,92.194013,59.0,0.319385,8.0,0.043306,112.0,0.606290,1043.0,5.646078,220.0,1.190927,14198.0,363.0,2.556698,3478.0,24.496408,5962.0,41.991830,3018.0,21.256515,1086.0,7.648965,291.0,2.049584,17430.0,1256.0,1188.0,1387.0,1433.0,1166.0,3936.0,2745.0,3094.0,1225.0,980.0,1082.0,1150.0,1237.0,1036.0,3344.0,2301.0,2526.0,837.0,356.0,27.0,40.0,42.0,9.0,16.0,24.0,0.0,32.0,28840.0,2939.0,10.190707,25901.0,89.809293,1985.0,8.016315,954.0,23.393821,22777.0,954.0,38374.0,33755.0,87.963204,1877.0,4.891333,2005.0,5.224892,704.0,1.834575,33.0,0.085996,9739.0,9415.0,324.0,3.326830,100.0,30.864198,224.0,69.135802,851.0,127.0,237.0,0.0,480.0,0.0,89.0,36316.0,35098.0,96.646106,775.0,409.0,150.0,134.0,82.0,361.0,216.0,56.0,89.0,0.0,82.0,56.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.353894,25.041051
1,"Davidson County, Tennessee",45668.0,252477.0,21983.0,8.706932,14802.0,5.862712,13855.0,5.487629,14627.0,5.793399,15690.0,6.214427,15668.0,6.205714,13749.0,5.445645,14114.0,5.590212,12556.0,4.973126,21754.0,8.616230,26287.0,10.411641,26188.0,10.372430,14988.0,5.936382,8011.0,3.172962,8018.0,3.175735,10187.0,4.034823,407124.0,60800.0,14.934025,101860.0,25.019404,85.065975,81733.0,20.075702,39.975800,24182.0,5.939714,88182.0,21.659740,34.031155,32732.0,8.039811,12.371415,10514.0,2.582506,4.331604,7121.0,1.749099,312839.0,900.0,0.287688,20042.0,6.406490,24266.0,7.756706,10173.0,3.251832,36604.0,11.700587,14446.0,4.617711,11353.0,3.629023,22464.0,7.180690,34795.0,11.122334,72883.0,23.297287,33557.0,10.726604,17033.0,5.444654,14323.0,4.578393,312839.0,44156.0,14.114608,88541.0,28.302418,5632.0,1.800287,5833.0,1.864537,10501.0,3.356679,13920.0,4.449573,10734.0,3.431158,38107.0,12.181026,47321.0,15.126311,278.0,0.088864,23912.0,7.643548,15762.0,5.038374,17427.0,5.570597,304450.0,217055.0,71.294137,36873.0,12.111348,28411.0,9.331910,29382.0,9.650846,382.0,0.125472,312839.0,25371.0,7.501552,27780.0,590134.0,102384.0,17.349280,252477.0,94347.0,106956.0,50743.0,20.098068,145521.0,43604.0,17.270484,41509.0,16.440705,165400.0,162400.0,776.0,280062.0,150843.0,53.860574,20840.0,7.441209,15613.0,5.574837,9418.0,3.362827,16826.0,6.007955,30358.0,10.839743,17467.0,6.236833,14595.0,5.211346,4093.0,1.461462,9.0,0.003214,304450.0,275335.0,90.436853,6034.0,1.981935,877.0,0.288060,5573.0,1.830514,12850.0,4.220726,3781.0,1.241912,252477.0,19046.0,7.543657,102775.0,40.706678,91741.0,36.336379,28860.0,11.430744,7416.0,2.937297,2639.0,1.045244,291600.0,27377.0,37302.0,53528.0,57892.0,24157.0,50656.0,16303.0,15543.0,8842.0,21074.0,32029.0,46291.0,50789.0,21444.0,42729.0,13415.0,11986.0,5480.0,1560.0,1687.0,1435.0,1028.0,281.0,1098.0,325.0,290.0,525.0,478156.0,39887.0,8.341838,438269.0,91.658162,25148.0,6.073956,14739.0,22.984437,388882.0,14739.0,604412.0,482647.0,79.853974,75253.0,12.450613,19403.0,3.210227,22777.0,3.768456,4332.0,0.716730,414998.0,371882.0,43116.0,10.389448,13540.0,31.403655,29576.0,68.596345,70318.0,5182.0,18764.0,10561.0,35566.0,79.0,940.0,569612.0,485954.0,85.313161,44699.0,16978.0,10521.0,11798.0,5402.0,13914.0,10165.0,2632.0,926.0,191.0,12829.0,6993.0,3455.0,2086.0,295.0,12216.0,6164.0,3099.0,2316.0,637.0,14.686839,28.271056
2,"Dickson County, Tennessee",44554.0,18889.0,1406.0,7.443486,1362.0,7.210546,1090.0,5.770554,1098.0,5.812907,1078.0,5.707025,1225.0,6.485256,1014.0,5.368204,1300.0,6.882312,1013.0,5.362910,1849.0,9.788766,2025.0,10.720525,2162.0,11.445815,1320.0,6.988194,436.0,2.308222,277.0,1.466462,234.0,1.238816,32378.0,6274.0,19.377355,13616.0,42.053246,80.622645,6103.0,18.849219,19.778396,1553.0,4.796467,3080.0,9.512632,14.923714,1274.0,3.934771,5.411082,275.0,0.849342,1.476311,203.0,0.626969,22724.0,243.0,1.069354,2812.0,12.374582,3374.0,14.847738,506.0,2.226721,2548.0,11.212815,1230.0,5.412779,430.0,1.892272,1050.0,4.620665,1541.0,6.781377,4631.0,20.379335,1653.0,7.274247,1293.0,5.690019,1413.0,6.218095,22724.0,2213.0,9.738602,4739.0,20.854603,617.0,2.715191,703.0,3.093645,947.0,4.167400,803.0,3.533709,500.0,2.200317,2393.0,10.530716,3056.0,13.448337,133.0,0.585284,3740.0,16.458370,1928.0,8.484422,1439.0,6.332512,22209.0,15647.0,70.453420,3469.0,15.619794,2486.0,11.193660,1121.0,5.047503,26.0,0.117070,22724.0,1816.0,7.400163,21415.0,48232.0,6733.0,13.959612,18889.0,5224.0,4897.0,1973.0,10.445233,13992.0,3251.0,17.211075,2127.0,11.260522,135700.0,117500.0,671.0,20465.0,14715.0,71.903249,184.0,0.899096,515.0,2.516492,456.0,2.228194,618.0,3.019790,424.0,2.071830,201.0,0.982165,54.0,0.263865,3298.0,16.115319,0.0,0.000000,22209.0,21160.0,95.276690,21.0,0.094556,0.0,0.000000,187.0,0.842001,675.0,3.039308,166.0,0.747445,18889.0,1074.0,5.685849,4991.0,26.422786,7303.0,38.662714,3843.0,20.345174,1309.0,6.929959,369.0,1.953518,21534.0,2989.0,3010.0,2786.0,1868.0,768.0,2059.0,1188.0,3792.0,3074.0,2551.0,2631.0,2381.0,1607.0,617.0,1546.0,977.0,3025.0,2183.0,825.0,41.0,19.0,50.0,0.0,21.0,0.0,15.0,58.0,36197.0,3996.0,11.039589,32201.0,88.960411,2652.0,8.807998,1344.0,22.076216,27457.0,1344.0,47957.0,40512.0,84.475676,4098.0,8.545155,2059.0,4.293430,1194.0,2.489730,94.0,0.196009,17482.0,16906.0,576.0,3.294818,142.0,24.652778,434.0,75.347222,1072.0,89.0,224.0,0.0,759.0,0.0,91.0,45376.0,43965.0,96.890427,907.0,444.0,82.0,329.0,52.0,374.0,272.0,77.0,25.0,0.0,52.0,26.0,16.0,10.0,0.0,78.0,78.0,0.0,0.0,0.0,3.109573,29.482636
3,"Houston County, Tennessee",33738.0,3392.0,399.0,11.762972,389.0,11.468160,244.0,7.193396,220.0,6.485849,215.0,6.338443,282.0,8.313679,175.0,5.159198,218.0,6.426887,136.0,4.009434,348.0,10.259434,269.0,7.930425,225.0,6.633255,113.0,3.331368,77.0,2.270047,55.0,1.621462,27.0,0.795991,5651.0,1151.0,20.368076,2837.0,50.203504,79.631924,1001.0,17.713679,12.028202,237.0,4.193948,290.0,5.131835,7.520793,106.0,1.875774,2.388958,9.0,0.159264,0.513184,20.0,0.353920,3020.0,119.0,3.940397,560.0,18.543046,421.0,13.940397,23.0,0.761589,399.0,13.211921,285.0,9.437086,93.0,3.079470,55.0,1.821192,155.0,5.132450,542.0,17.947020,131.0,4.337748,140.0,4.635762,97.0,3.211921,3020.0,283.0,9.370861,449.0,14.867550,117.0,3.874172,43.0,1.423841,147.0,4.867550,72.0,2.384106,74.0,2.450331,275.0,9.105960,400.0,13.245033,54.0,1.788079,699.0,23.145695,273.0,9.039735,226.0,7.483444,2897.0,1806.0,62.340352,610.0,21.056265,436.0,15.050052,91.0,3.141181,6.0,0.207111,3020.0,369.0,10.888168,17791.0,8075.0,1570.0,19.442724,3392.0,829.0,897.0,325.0,9.581368,2495.0,504.0,14.858491,309.0,9.109670,89800.0,83900.0,539.0,4163.0,2904.0,69.757387,36.0,0.864761,89.0,2.137881,96.0,2.306029,15.0,0.360317,24.0,0.576507,11.0,0.264233,6.0,0.144127,982.0,23.588758,0.0,0.000000,2897.0,2745.0,94.753193,0.0,0.000000,0.0,0.000000,40.0,1.380739,68.0,2.347256,44.0,1.518813,3392.0,275.0,8.107311,989.0,29.156840,1171.0,34.522406,653.0,19.251179,255.0,7.517689,49.0,1.444575,2829.0,723.0,263.0,271.0,289.0,114.0,214.0,179.0,381.0,395.0,666.0,197.0,239.0,255.0,110.0,179.0,163.0,310.0,294.0,101.0,36.0,0.0,3.0,4.0,0.0,0.0,2.0,0.0,6252.0,828.0,13.243762,5424.0,86.756238,468.0,9.717608,360.0,25.069638,4348.0,360.0,8202.0,7287.0,88.844184,507.0,6.181419,261.0,3.182151,147.0,1.792246,0.0,0.000000,1867.0,1853.0,14.0,0.749866,0.0,0.000000,14.0,100.000000,36.0,3.0,0.0,0.0,33.0,0.0,33.0,7798.0,7723.0,99.038215,44.0,31.0,13.0,0.0,0.0,31.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.961785,0.000000
4,"Humphreys County, Tennessee",41486.0,7555.0,504.0,6.671079,558.0,7.385837,504.0,6.671079,651.0,8.616810,458.0,6.062210,626.0,8.285903,363.0,4.804765,449.0,5.943084,487.0,6.446062,625.0,8.272667,719.0,9.516876,885.0,11.714097,444.0,5.876903,101.0,1.336863,101.0,1.336863,80.0,1.058901,12729.0,2308.0,18.131825,5556.0,43.648362,81.868175,2670.0,20.975725,17.408875,516.0,4.053736,1112.0,8.735957,13.190353,440.0,3.456674,4.454395,97.0,0.762039,0.997722,30.0,0.235682,7795.0,107.0,1.372675,729.0,9.352149,1572.0,20.166774,92.0,1.180244,711.0,9.121232,603.0,7.735728,57.0,0.731238,256.0,3.284157,429.0,5.503528,1667.0,21.385504,777.0,9.967928,549.0,7.042976,246.0,3.155869,7795.0,652.0,8.364336,1398.0,17.934573,244.0,3.130212,139.0,1.783194,495.0,6.350225,353.0,4.528544,177.0,2.270686,670.0,8.595253,827.0,10.609365,57.0,0.731238,1177.0,15.099423,1067.0,13.688262,533.0,6.837716,7492.0,5011.0,66.884677,1359.0,18.139349,902.0,12.039509,345.0,4.604912,3.0,0.040043,7795.0,734.0,8.605933,20874.0,18295.0,2361.0,12.905165,7555.0,1707.0,1847.0,452.0,5.982793,5708.0,1255.0,16.611516,542.0,7.174057,108300.0,99000.0,514.0,8878.0,6342.0,71.435008,84.0,0.946159,160.0,1.802208,133.0,1.498085,123.0,1.385447,11.0,0.123902,89.0,1.002478,8.0,0.090110,1897.0,21.367425,31.0,0.349178,7492.0,7287.0,97.263748,7.0,0.093433,0.0,0.000000,30.0,0.400427,120.0,1.601708,48.0,0.640683,7555.0,361.0,4.778293,2178.0,28.828590,2760.0,36.532098,1606.0,21.257445,461.0,6.101919,189.0,2.501655,7372.0,1374.0,858.0,1139.0,1209.0,339.0,841.0,314.0,417.0,881.0,1240.0,749.0,938.0,1116.0,280.0,763.0,245.0,335.0,673.0,208.0,17.0,18.0,0.0,0.0,0.0,0.0,14.0,0.0,14015.0,1695.0,12.094185,12320.0,87.905815,829.0,7.568703,866.0,28.282169,10124.0,866.0,18131.0,15904.0,87.717169,1349.0,7.440296,425.0,2.344052,432.0,2.382660,21.0,0.115824,7159.0,7090.0,69.0,0.963822,0.0,0.000000,69.0,100.000000,157.0,38.0,10.0,0.0,109.0,0.0,6.0,17361.0,17169.0,98.894073,143.0,14.0,30.0,74.0,25.0,39.0,35.0,0.0,4.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.105927,53.645833

In [10]:
suffix = data.set_index('NAME')
suffix = suffix.add_suffix(' 2010')
suffix = suffix.reset_index()
suffix.head(3)

,NAME,Median Household Income 2010,HHIncome:Total Households 2010,"HHIncome:Less than 10,000 2010","HHIncome%:Less than 10,000 2010","HHIncome:10 to 14,999 2010","HHIncome%:10 to 14,999 2010","HHIncome:15 to 19,999 2010","HHIncome%:15 to 19,999 2010","HHIncome:20 to 24,999 2010","HHIncome%:20 to 24,999 2010","HHIncome:25 to 29,999 2010","HHIncome%:25 to 29,999 2010","HHIncome:30 to 34,999 2010","HHIncome:%30 to 34,999 2010","HHIncome:35 to 39,999 2010","HHIncome%:35 to 39,999 2010","HHIncome:40 to 44,999 2010","HHIncome%:40 to 44,999 2010","HHIncome:45 to 49,999 2010","HHIncome%:45 to 49,999 2010","HHIncome:50 to 59,999 2010","HHIncome%:50 to 59,999 2010","HHIncome:60 to 74,999 2010","HHIncome%:60 to 74,999 2010","HHIncome:75 to 99,999 2010","HHIncome%:75 to 99,999 2010","HHIncome:100 to 124,999 2010","HHIncome%:100 to 124,999 2010","HHIncome:125 to 149,999 2010","HHIncome%:125 to 149,999 2010","HHIncome:150 to 199,999 2010","HHIncome%:150 to 199,999 2010",HHIncome:200K or More 2010,HHIncome%:200K or More 2010,Ed:Population 25+ Educational Attainment 2010,Ed:Less than High School 2010,Ed%:Less than High School 2010,Ed:High School Graduate or Equivalency 2010,Ed%:High School Graduate or Equivalency 2010,Ed%:High School Graduate or More 2010,Ed:Some College 2010,Ed%:Some College 2010,Ed%:Some College or More 2010,Ed:Associates 2010,Ed%:Associates 2010,Ed:Bachelors 2010,Ed%:Bachelors 2010,Ed%:Bachelors or More 2010,Ed:Masters 2010,Ed%:Masters 2010,Ed%:Masters or More 2010,Ed:Professional School Degree 2010,Ed%:Professional School Degree 2010,Ed%:Professional School Degree or More 2010,Ed:Doctorate Degree 2010,Ed%:Doctorate Degree 2010,Ind:Employed Civilians 16+ 2010,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2010","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2010",Ind:Construction 2010,Ind%:Construction 2010,Ind:Manufacturing 2010,Ind%:Manufacturing 2010,Ind:Wholesale Trade 2010,Ind%:Wholesale Trade 2010,Ind:Retail Trade 2010,Ind%:Retail Trade 2010,"Ind:Transportation and Warehousing, Utilities 2010","Ind%:Transportation and Warehousing, Utilities 2010",Ind:Information 2010,Ind%:Information 2010,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind:Educational, Health and Social Services 2010","Ind%:Educational, Health and Social Services 2010","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2010","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2010",Ind:Other Services (Except Public Administration) 2010,Ind%:Other Services (Except Public Administration) 2010,Ind:Public Administration 2010,Ind%:Public Administration 2010,Employed Civilians 16+ Occupational 2010,"Occ:Management, Business, and Financial Operations 2010","Occ%:Management, Business, and Financial Operations 2010",Occ:Professional and Related 2010,Occ%:Professional and Related 2010,Occ:Healthcare Support 2010,Occ%:Healthcare Support 2010,Occ:Protective Services 2010,Occ%:Protective Services 2010,Occ:Food Preparation and Serving Related 2010,Occ%:Food Preparation and Serving Related 2010,Occ:Building and Grounds Cleaning and Maintenance 2010,Occ%:Building and Grounds Cleaning and Maintenance 2010,Occ:Personal Care and Service 2010,Occ%:Personal Care and Service 2010,Occ:Sales and Related 2010,Occ%:Sales and Related 2010,Occ:Office and Administrative Support 2010,Occ%:Office and Administrative Support 2010,"Occ:Farming, Fishing, and Forestry 2010","Occ%:Farming, Fishing, and Forestry 2010","Occ:Construction, Extraction, and Maintenance 2010","Occ%:Construction, Extraction, and Maintenance 2010",Occ:Production 2010,Occ%:Production 2010,Occ:Transportation and Material Moving 2010,Occ%:Transportation and Material Moving 2010,Sector: Total Workers 2010,Sector:Private 2010,Sector%:Private 2010,Sector:Public 2010,Sector%:Public 2010,Sector:Self-Employed 2010,Sector%:Self-Employed 2010,Sector:Non-Profit 2010,Sector%:Non-Profit 2010,Sector:Unpaid Family Workers 2010,Sector%:Unpaid Family Workers 2010,Employed 2010,Unemployed 2010,Unemployment Rate 2010,Per Capita Income 2010,Poverty:Population for Whom Poverty Status is Determined 2010,Poverty: Population Below Poverty Level 2010,Poverty%: Below Poverty Level 2010,CB:Total Housing Units 2010,CB:Cost Burdened Housholds 2010,CB:Renter Occupied Units 2010,CB:Cost Burdened Renters 2010,CB%:Cost Burdened Renters 2010,CB:Owner Occupied Units 2010,CB:Cost Burdened Homeowners 2010,CB%: Cost Burdened Homeowners 2010,CB:Severe Cost Burdened Households 2010,CB%:Severe Cost Burdened Households 2010,Median Home Value Owner Occupied with Mortgage 2010,Median Home Value Owner Occupied without Mortgage 2010,Median Gross Rent 2010,Units:Total Series 2010,"Units:1 Unit, Detached 2010","Units%:1 Unit, Detached 2010","Units:1 Unit, Attached 2010","Units%:1 Unit, Attached 2010",Units:2 2010,Units%:2 2010,Units:3 to 4 2010,Units%:3 to 4 2010,Units:5 to 9 2010,Units%:5 to 9 2010,Units:10 to 19 2010,Units%:10 to 19 2010,Units:20 to 49 2010,Units%:20 to 49 2010,Units:50 or More 2010,Units%:50 or More 2010,Units:Mobile Home 2010,Units%:Mobile Home 2010,"Units:Boat, RV, Van etc 2010","Units%:Boat, RV, Van etc 2010",Transpo:Workers Commuting 2010,"Transpo:Car, Truck, or Van 2010","Transpo%:Car, Truck, or Van 2010",Transpo:Public Transportation 2010,Transpo%:Public Transportation 2010,Transpo:Bicycle 2010,Transpo%:Bicycle 2010,Transpo:Walk 2010,Transpo%:Walk 2010,Transpo:Worked From Home 2010,Transpo%:Worked From Home 2010,"Transpo:Taxi, Motorcycle, Other 2010","Transpo%:Taxi, Motorcycle, Other 2010",Vehicles:Households 2010,Vehicles:None 2010,Vehicles%:None 2010,Vehicles:One 2010,Vehicles%:One 2010,Vehicles:Two 2010,Vehicles%:Two 2010,Vehicles:Three 2010,Vehicles%:Three 2010,Vehicles:Four 2010,Vehicles%:Four 2010,Vehicles:Five or More 2010,Vehicles%:Five or More 2010,Commute:Workers 16+ Not Working at Home 2010,Commute:Less than 10 Minutes 2010,Commute:10 to 14 Minutes 2010,Commute:15 to 19 Minutes 2010,Commute:20 to 24 Minutes 2010,Commute:25 to 29 Minutes 2010,Commute:30 to 34 Minutes 2010,Commute:35 to 44 Minutes 2010,Commute:45 to 59 Minutes 2010,Commute:60 or More Minutes 2010,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes 2010","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes 2010","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes 2010","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes 2010","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes 2010","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes 2010","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes 2010","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes 2010","Commute:Car, Truck, Van Drove Alone:60 or More Minutes 2010","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes 2010","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes 2010","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes 2010","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes 2010","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes 2010","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes 2010","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes 2010","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes 2010","Commute:Car, Truck, Van Carpooled:60 or More Minutes 2010",Vet:Population 18+ 2010,Vet:Veteran 2010,Vet%:Veteran 2010,Vet:Nonveteran 2010,Vet%:Nonveteran 2010,Vet:Veteran 18 to 64 2010,Vet%:Veterans who are 18 to 64 2010,Vet:Veteran 65 and Older 2010,Vet%:Veterans who are 65 and Older 2010,Vet:Nonveteran 18 to 64 2010,Vet:Nonveteran 65 and Older 2010,GeoMobility:Total 2010,GeoMobility:Same House 2010,GeoMobility%:Same House 2010,GeoMobility:Moved Same County 2010,GeoMobility%:Moved Same County 2010,GeoMobility:Moved Different County Same State 2010,GeoMobility%:Moved Different County Same State 2010,GeoMobility:Moved Different State 2010,GeoMobility%:Moved Different State 2010,GeoMobility:Moved From Abroad 2010,GeoMobility%:Moved From Abroad 2010,ForeignBorn:Total Population 2010,ForeignBorn:Native Born 2010,ForeignBorn:Foreign Born 2010,ForeignBorn%:Foreign Born 2010,ForeignBorn:Foreign Born Naturalized Citizen 2010,ForeignBorn%:Foreign Born Population that are Naturalized Citizen 2010,ForeignBorn:Foreign Born Not a Citizen 2010,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen 2010,Foreign Born Population 2010,ForeignBorn:Europe 2010,ForeignBorn:Asia 2010,ForeignBorn:Africa 2010,ForeignBorn:Oceania 2010,"ForeignBorn:Central & South America, Caribbean 2010",ForeignBorn:Canada & Other Northern American 2010,Language:Population 5 and Older 2010,Language:Speak Only English 2010,Language%:Speak Only English 2010,Language:Speak Spanish 2010,Language:Spanish:Speak English Very Well 2010,Language:Spanish:Speak English Well 2010,Language:Spanish:Speak English Not Well 2010,Language:Spanish:Speak English Not At All 2010,Language:Speak Other Indo-European Language 2010,Language:Other Indo-European:Speak English Very Well 2010,Language:Other Indo-European:Speak English Well 2010,Language:Other Indo-European:Speak English Not Well 2010,Language:Other Indo-European:Speak English Not At All 2010,Language:Speak Asian or Pacific Island Language 2010,Language:Asian or Pacific Island:Speak English Very Well 2010,Language:Asian or Pacific Island:Speak English Well 2010,Language:Asian or Pacific Island:Speak English Not Well 2010,Language:Asian or Pacific Island:Speak English Not At All 2010,Language:Speak Other Language 2010,Language:Other:Speak English Very Well 2010,Language:Other:Speak English Well 2010,Language:Other:Speak English Not Well 2010,Language:Other:Speak English Not At All 2010,Language%:Speak Language Besides English 2010,Language%:Of Those that Speak Another Language and Speak English Not Well or At All 2010
0,"Cheatham County, Tennessee",52585.0,14198.0,596.0,4.197774,709.0,4.993661,715.0,5.035921,839.0,5.909283,748.0,5.268348,731.0,5.148612,749.0,5.275391,686.0,4.831666,970.0,6.831948,1205.0,8.487111,1823.0,12.839837,2101.0,14.797859,1210.0,8.522327,424.0,2.986336,432.0,3.042682,260.0,1.831244,25952.0,4788.0,18.449445,9677.0,37.288070,81.550555,5186.0,19.983046,24.356439,1659.0,6.392571,3363.0,12.958539,17.886868,879.0,3.387022,4.928329,285.0,1.098181,1.541307,115.0,0.443126,19066.0,176.0,0.923109,2646.0,13.878108,1894.0,9.933914,797.0,4.180216,2177.0,11.418231,894.0,4.688975,553.0,2.900451,1193.0,6.257212,1883.0,9.876219,3510.0,18.409735,1286.0,6.744991,1027.0,5.386552,1030.0,5.402287,19066.0,2765.0,14.502255,4337.0,22.747299,357.0,1.872443,324.0,1.699360,683.0,3.582293,824.0,4.321829,473.0,2.480856,2194.0,11.507395,3144.0,16.490087,68.0,0.356656,2749.0,14.418336,1026.0,5.381307,1206.0,6.325396,18473.0,12649.0,68.472906,2388.0,12.926975,2853.0,15.444162,1204.0,6.517620,43.0,0.232772,19066.0,1229.0,6.055679,24392.0,37813.0,3517.0,9.301034,14198.0,4032.0,2715.0,1259.0,8.867446,11483.0,2773.0,19.530920,1290.0,9.085787,163700.0,137200.0,763.0,15425.0,12298.0,79.727715,207.0,1.341977,144.0,0.933549,217.0,1.406807,172.0,1.115073,231.0,1.497569,82.0,0.531605,39.0,0.252836,2035.0,13.192869,0.0,0.000000,18473.0,17031.0,92.194013,59.0,0.319385,8.0,0.043306,112.0,0.606290,1043.0,5.646078,220.0,1.190927,14198.0,363.0,2.556698,3478.0,24.496408,5962.0,41.991830,3018.0,21.256515,1086.0,7.648965,291.0,2.049584,17430.0,1256.0,1188.0,1387.0,1433.0,1166.0,3936.0,2745.0,3094.0,1225.0,980.0,1082.0,1150.0,1237.0,1036.0,3344.0,2301.0,2526.0,837.0,356.0,27.0,40.0,42.0,9.0,16.0,24.0,0.0,32.0,28840.0,2939.0,10.190707,25901.0,89.809293,1985.0,8.016315,954.0,23.393821,22777.0,954.0,38374.0,33755.0,87.963204,1877.0,4.891333,2005.0,5.224892,704.0,1.834575,33.0,0.085996,9739.0,9415.0,324.0,3.326830,100.0,30.864198,224.0,69.135802,851.0,127.0,237.0,0.0,480.0,0.0,89.0,36316.0,35098.0,96.646106,775.0,409.0,150.0,134.0,82.0,361.0,216.0,56.0,89.0,0.0,82.0,56.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.353894,25.041051
1,"Davidson County, Tennessee",45668.0,252477.0,21983.0,8.706932,14802.0,5.862712,13855.0,5.487629,14627.0,5.793399,15690.0,6.214427,15668.0,6.205714,13749.0,5.445645,14114.0,5.590212,12556.0,4.973126,21754.0,8.616230,26287.0,10.411641,26188.0,10.372430,14988.0,5.936382,8011.0,3.172962,8018.0,3.175735,10187.0,4.034823,407124.0,60800.0,14.934025,101860.0,25.019404,85.065975,81733.0,20.075702,39.975800,24182.0,5.939714,88182.0,21.659740,34.031155,32732.0,8.039811,12.371415,10514.0,2.582506,4.331604,7121.0,1.749099,312839.0,900.0,0.287688,20042.0,6.406490,24266.0,7.756706,10173.0,3.251832,36604.0,11.700587,14446.0,4.617711,11353.0,3.629023,22464.0,7.180690,34795.0,11.122334,72883.0,23.297287,33557.0,10.726604,17033.0,5.444654,14323.0,4.578393,312839.0,44156.0,14.114608,88541.0,28.302418,5632.0,1.800287,5833.0,1.864537,10501.0,3.356679,13920.0,4.449573,10734.0,3.431158,38107.0,12.181026,47321.0,15.126311,278.0,0.088864,23912.0,7.643548,15762.0,5.038374,17427.0,5.570597,304450.0,217055.0,71.294137,36873.0,12.111348,28411.0,9.331910,29382.0,9.650846,382.0,0.125472,312839.0,25371.0,7.501552,27780.0,590134.0,102384.0,17.349280,252477.0,94347.0,106956.0,50743.0,20.098068,145521.0,43604.0,17.270484,41509.0,16.440705,165400.0,162400.0,776.0,280062.0,150843.0,53.860574,20840.0,7.441209,15613.0,5.574837,9418.0,3.362827,16826.0,6.007955,30358.0,10.839743,17467.0,6.236833,14595.0,5.211346,4093.0,1.461462,9.0,0.003214,304450.0,275335.0,90.436853,6034.0,1.981935,877.0,0.288060,5573.0,1.830514,12850.0,4.220726,3781.0,1.241912,252477.0,19046.0,7.543657,102775.0,40.706678,91741.0,36.336379,28860.0,11.430744,7416.0,2.937297,2639.0,1.045244,291600.0,27377.0,37302.0,53528.0,57892.0,24157.0,50656.0,16303.0,15543.0,8842.0,21074.0,32029.0,46291.0,50789.0,21444.0,42729.0,13415.0,11986.0,5480.0,1560.0,1687.0,1435.0,1028.0,281.0,1098.0,325.0,290.0,525.0,478156.0,39887.0,8.341838,438269.0,91.658162,25148.0,6.073956,14739.0,22.984437,388882.0,14739.0,604412.0,482647.0,79.853974,75253.0,12.450613,19403.0,3.210227,22777.0,3.768456,4332.0,0.716730,414998.0,371882.0,43116.0,10.389448,13540.0,31.403655,29576.0,68.596345,70318.0,5182.0,18764.0,10561.0,35566.0,79.0,940.0,569612.0,485954.0,85.313161,44699.0,16978.0,10521.0,11798.0,5402.0,13914.0,10165.0,2632.0,926.0,191.0,12829.0,6993.0,3455.0,2086.0,295.0,12216.0,6164.0,3099.0,2316.0,637.0,14.686839,28.271056
2,"Dickson County, Tennessee",44554.0,18889.0,1406.0,7.443486,1362.0,7.210546,1090.0,5.770554,1098.0,5.812907,1078.0,5.707025,1225.0,6.485256,1014.0,5.368204,1300.0,6.882312,1013.0,5.362910,1849.0,9.788766,2025.0,10.720525,2162.0,11.445815,1320.0,6.988194,436.0,2.308222,277.0,1.466462,234.0,1.238816,32378.0,6274.0,19.377355,13616.0,42.053246,80.622645,6103.0,18.849219,19.778396,1553.0,4.796467,3080.0,9.512632,14.923714,1274.0,3.934771,5.411082,275.0,0.849342,1.476311,203.0,0.626969,22724.0,243.0,1.069354,2812.0,12.374582,3374.0,14.847738,506.0,2.226721,2548.0,11.212815,1230.0,5.412779,430.0,1.892272,1050.0,4.620665,1541.0,6.781377,4631.0,20.379335,1653.0,7.274247,1293.0,5.690019,1413.0,6.218095,22724.0,2213.0,9.738602,4739.0,20.854603,617.0,2.715191,703.0,3.093645,947.0,4.167400,803.0,3.533709,500.0,2.200317,2393.0,10.530716,3056.0,13.448337,133.0,0.585284,3740.0,16.458370,1928.0,8.484422,1439.0,6.332512,22209.0,15647.0,70.453420,3469.0,15.619794,2486.0,11.193660,1121.0,5.047503,26.0,0.117070,22724.0,1816.0,7.400163,21415.0,48232.0,6733.0,13.959612,18889.0,5224.0,4897.0,1973.0,10.445233,13992.0,3251.0,17.211075,2127.0,11.260522,135700.0,117500.0,671.0,20465.0,14715.0,71.903249,184.0,0.899096,515.0,2.516492,456.0,2.228194,618.0,3.019790,424.0,2.071830,201.0,0.982165,54.0,0.263865,3298.0,16.115319,0.0,0.000000,22209.0,21160.0,95.276690,21.0,0.094556,0.0,0.000000,187.0,0.842001,675.0,3.039308,166.0,0.747445,18889.0,1074.0,5.685849,4991.0,26.422786,7303.0,38.662714,3843.0,20.345174,1309.0,6.929959,369.0,1.953518,21534.0,2989.0,3010.0,2786.0,1868.0,768.0,2059.0,1188.0,3792.0,3074.0,2551.0,2631.0,2381.0,1607.0,617.0,1546.0,977.0,3025.0,2183.0,825.0,41.0,19.0,50.0,0.0,21.0,0.0,15.0,58.0,36197.0,3996.0,11.039589,32201.0,88.960411,2652.0,8.807998,1344.0,22.076216,27457.0,1344.0,47957.0,40512.0,84.475676,4098.0,8.545155,2059.0,4.293430,1194.0,2.489730,94.0,0.196009,17482.0,16906.0,576.0,3.294818,142.0,24.652778,434.0,75.347222,1072.0,89.0,224.0,0.0,759.0,0.0,91.0,45376.0,43965.0,96.890427,907.0,444.0,82.0,329.0,52.0,374.0,272.0,77.0,25.0,0.0,52.0,26.0,16.0,10.0,0.0,78.0,78.0,0.0,0.0,0.0,3.109573,29.482636

In [11]:
tidy = data
tidy.head(3)

,NAME,Median Household Income,HHIncome:Total Households,"HHIncome:Less than 10,000","HHIncome%:Less than 10,000","HHIncome:10 to 14,999","HHIncome%:10 to 14,999","HHIncome:15 to 19,999","HHIncome%:15 to 19,999","HHIncome:20 to 24,999","HHIncome%:20 to 24,999","HHIncome:25 to 29,999","HHIncome%:25 to 29,999","HHIncome:30 to 34,999","HHIncome:%30 to 34,999","HHIncome:35 to 39,999","HHIncome%:35 to 39,999","HHIncome:40 to 44,999","HHIncome%:40 to 44,999","HHIncome:45 to 49,999","HHIncome%:45 to 49,999","HHIncome:50 to 59,999","HHIncome%:50 to 59,999","HHIncome:60 to 74,999","HHIncome%:60 to 74,999","HHIncome:75 to 99,999","HHIncome%:75 to 99,999","HHIncome:100 to 124,999","HHIncome%:100 to 124,999","HHIncome:125 to 149,999","HHIncome%:125 to 149,999","HHIncome:150 to 199,999","HHIncome%:150 to 199,999",HHIncome:200K or More,HHIncome%:200K or More,Ed:Population 25+ Educational Attainment,Ed:Less than High School,Ed%:Less than High School,Ed:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency,Ed%:High School Graduate or More,Ed:Some College,Ed%:Some College,Ed%:Some College or More,Ed:Associates,Ed%:Associates,Ed:Bachelors,Ed%:Bachelors,Ed%:Bachelors or More,Ed:Masters,Ed%:Masters,Ed%:Masters or More,Ed:Professional School Degree,Ed%:Professional School Degree,Ed%:Professional School Degree or More,Ed:Doctorate Degree,Ed%:Doctorate Degree,Ind:Employed Civilians 16+,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining",Ind:Construction,Ind%:Construction,Ind:Manufacturing,Ind%:Manufacturing,Ind:Wholesale Trade,Ind%:Wholesale Trade,Ind:Retail Trade,Ind%:Retail Trade,"Ind:Transportation and Warehousing, Utilities","Ind%:Transportation and Warehousing, Utilities",Ind:Information,Ind%:Information,"Ind:Finance, Insurance, Real Estate and Rental and Leasing","Ind%:Finance, Insurance, Real Estate and Rental and Leasing","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind:Educational, Health and Social Services","Ind%:Educational, Health and Social Services","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services",Ind:Other Services (Except Public Administration),Ind%:Other Services (Except Public Administration),Ind:Public Administration,Ind%:Public Administration,Employed Civilians 16+ Occupational,"Occ:Management, Business, and Financial Operations","Occ%:Management, Business, and Financial Operations",Occ:Professional and Related,Occ%:Professional and Related,Occ:Healthcare Support,Occ%:Healthcare Support,Occ:Protective Services,Occ%:Protective Services,Occ:Food Preparation and Serving Related,Occ%:Food Preparation and Serving Related,Occ:Building and Grounds Cleaning and Maintenance,Occ%:Building and Grounds Cleaning and Maintenance,Occ:Personal Care and Service,Occ%:Personal Care and Service,Occ:Sales and Related,Occ%:Sales and Related,Occ:Office and Administrative Support,Occ%:Office and Administrative Support,"Occ:Farming, Fishing, and Forestry","Occ%:Farming, Fishing, and Forestry","Occ:Construction, Extraction, and Maintenance","Occ%:Construction, Extraction, and Maintenance",Occ:Production,Occ%:Production,Occ:Transportation and Material Moving,Occ%:Transportation and Material Moving,Sector: Total Workers,Sector:Private,Sector%:Private,Sector:Public,Sector%:Public,Sector:Self-Employed,Sector%:Self-Employed,Sector:Non-Profit,Sector%:Non-Profit,Sector:Unpaid Family Workers,Sector%:Unpaid Family Workers,Employed,Unemployed,Unemployment Rate,Per Capita Income,Poverty:Population for Whom Poverty Status is Determined,Poverty: Population Below Poverty Level,Poverty%: Below Poverty Level,CB:Total Housing Units,CB:Cost Burdened Housholds,CB:Renter Occupied Units,CB:Cost Burdened Renters,CB%:Cost Burdened Renters,CB:Owner Occupied Units,CB:Cost Burdened Homeowners,CB%: Cost Burdened Homeowners,CB:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households,Median Home Value Owner Occupied with Mortgage,Median Home Value Owner Occupied without Mortgage,Median Gross Rent,Units:Total Series,"Units:1 Unit, Detached","Units%:1 Unit, Detached","Units:1 Unit, Attached","Units%:1 Unit, Attached",Units:2,Units%:2,Units:3 to 4,Units%:3 to 4,Units:5 to 9,Units%:5 to 9,Units:10 to 19,Units%:10 to 19,Units:20 to 49,Units%:20 to 49,Units:50 or More,Units%:50 or More,Units:Mobile Home,Units%:Mobile Home,"Units:Boat, RV, Van etc","Units%:Boat, RV, Van etc",Transpo:Workers Commuting,"Transpo:Car, Truck, or Van","Transpo%:Car, Truck, or Van",Transpo:Public Transportation,Transpo%:Public Transportation,Transpo:Bicycle,Transpo%:Bicycle,Transpo:Walk,Transpo%:Walk,Transpo:Worked From Home,Transpo%:Worked From Home,"Transpo:Taxi, Motorcycle, Other","Transpo%:Taxi, Motorcycle, Other",Vehicles:Households,Vehicles:None,Vehicles%:None,Vehicles:One,Vehicles%:One,Vehicles:Two,Vehicles%:Two,Vehicles:Three,Vehicles%:Three,Vehicles:Four,Vehicles%:Four,Vehicles:Five or More,Vehicles%:Five or More,Commute:Workers 16+ Not Working at Home,Commute:Less than 10 Minutes,Commute:10 to 14 Minutes,Commute:15 to 19 Minutes,Commute:20 to 24 Minutes,Commute:25 to 29 Minutes,Commute:30 to 34 Minutes,Commute:35 to 44 Minutes,Commute:45 to 59 Minutes,Commute:60 or More Minutes,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes","Commute:Car, Truck, Van Drove Alone:60 or More Minutes","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes","Commute:Car, Truck, Van Carpooled:60 or More Minutes",Vet:Population 18+,Vet:Veteran,Vet%:Veteran,Vet:Nonveteran,Vet%:Nonveteran,Vet:Veteran 18 to 64,Vet%:Veterans who are 18 to 64,Vet:Veteran 65 and Older,Vet%:Veterans who are 65 and Older,Vet:Nonveteran 18 to 64,Vet:Nonveteran 65 and Older,GeoMobility:Total,GeoMobility:Same House,GeoMobility%:Same House,GeoMobility:Moved Same County,GeoMobility%:Moved Same County,GeoMobility:Moved Different County Same State,GeoMobility%:Moved Different County Same State,GeoMobility:Moved Different State,GeoMobility%:Moved Different State,GeoMobility:Moved From Abroad,GeoMobility%:Moved From Abroad,ForeignBorn:Total Population,ForeignBorn:Native Born,ForeignBorn:Foreign Born,ForeignBorn%:Foreign Born,ForeignBorn:Foreign Born Naturalized Citizen,ForeignBorn%:Foreign Born Population that are Naturalized Citizen,ForeignBorn:Foreign Born Not a Citizen,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen,Foreign Born Population,ForeignBorn:Europe,ForeignBorn:Asia,ForeignBorn:Africa,ForeignBorn:Oceania,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Canada & Other Northern American,Language:Population 5 and Older,Language:Speak Only English,Language%:Speak Only English,Language:Speak Spanish,Language:Spanish:Speak English Very Well,Language:Spanish:Speak English Well,Language:Spanish:Speak English Not Well,Language:Spanish:Speak English Not At All,Language:Speak Other Indo-European Language,Language:Other Indo-European:Speak English Very Well,Language:Other Indo-European:Speak English Well,Language:Other Indo-European:Speak English Not Well,Language:Other Indo-European:Speak English Not At All,Language:Speak Asian or Pacific Island Language,Language:Asian or Pacific Island:Speak English Very Well,Language:Asian or Pacific Island:Speak English Well,Language:Asian or Pacific Island:Speak English Not Well,Language:Asian or Pacific Island:Speak English Not At All,Language:Speak Other Language,Language:Other:Speak English Very Well,Language:Other:Speak English Well,Language:Other:Speak English Not Well,Language:Other:Speak English Not At All,Language%:Speak Language Besides English,Language%:Of Those that Speak Another Language and Speak English Not Well or At All
0,"Cheatham County, Tennessee",52585.0,14198.0,596.0,4.197774,709.0,4.993661,715.0,5.035921,839.0,5.909283,748.0,5.268348,731.0,5.148612,749.0,5.275391,686.0,4.831666,970.0,6.831948,1205.0,8.487111,1823.0,12.839837,2101.0,14.797859,1210.0,8.522327,424.0,2.986336,432.0,3.042682,260.0,1.831244,25952.0,4788.0,18.449445,9677.0,37.288070,81.550555,5186.0,19.983046,24.356439,1659.0,6.392571,3363.0,12.958539,17.886868,879.0,3.387022,4.928329,285.0,1.098181,1.541307,115.0,0.443126,19066.0,176.0,0.923109,2646.0,13.878108,1894.0,9.933914,797.0,4.180216,2177.0,11.418231,894.0,4.688975,553.0,2.900451,1193.0,6.257212,1883.0,9.876219,3510.0,18.409735,1286.0,6.744991,1027.0,5.386552,1030.0,5.402287,19066.0,2765.0,14.502255,4337.0,22.747299,357.0,1.872443,324.0,1.699360,683.0,3.582293,824.0,4.321829,473.0,2.480856,2194.0,11.507395,3144.0,16.490087,68.0,0.356656,2749.0,14.418336,1026.0,5.381307,1206.0,6.325396,18473.0,12649.0,68.472906,2388.0,12.926975,2853.0,15.444162,1204.0,6.517620,43.0,0.232772,19066.0,1229.0,6.055679,24392.0,37813.0,3517.0,9.301034,14198.0,4032.0,2715.0,1259.0,8.867446,11483.0,2773.0,19.530920,1290.0,9.085787,163700.0,137200.0,763.0,15425.0,12298.0,79.727715,207.0,1.341977,144.0,0.933549,217.0,1.406807,172.0,1.115073,231.0,1.497569,82.0,0.531605,39.0,0.252836,2035.0,13.192869,0.0,0.000000,18473.0,17031.0,92.194013,59.0,0.319385,8.0,0.043306,112.0,0.606290,1043.0,5.646078,220.0,1.190927,14198.0,363.0,2.556698,3478.0,24.496408,5962.0,41.991830,3018.0,21.256515,1086.0,7.648965,291.0,2.049584,17430.0,1256.0,1188.0,1387.0,1433.0,1166.0,3936.0,2745.0,3094.0,1225.0,980.0,1082.0,1150.0,1237.0,1036.0,3344.0,2301.0,2526.0,837.0,356.0,27.0,40.0,42.0,9.0,16.0,24.0,0.0,32.0,28840.0,2939.0,10.190707,25901.0,89.809293,1985.0,8.016315,954.0,23.393821,22777.0,954.0,38374.0,33755.0,87.963204,1877.0,4.891333,2005.0,5.224892,704.0,1.834575,33.0,0.085996,9739.0,9415.0,324.0,3.326830,100.0,30.864198,224.0,69.135802,851.0,127.0,237.0,0.0,480.0,0.0,89.0,36316.0,35098.0,96.646106,775.0,409.0,150.0,134.0,82.0,361.0,216.0,56.0,89.0,0.0,82.0,56.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.353894,25.041051
1,"Davidson County, Tennessee",45668.0,252477.0,21983.0,8.706932,14802.0,5.862712,13855.0,5.487629,14627.0,5.793399,15690.0,6.214427,15668.0,6.205714,13749.0,5.445645,14114.0,5.590212,12556.0,4.973126,21754.0,8.616230,26287.0,10.411641,26188.0,10.372430,14988.0,5.936382,8011.0,3.172962,8018.0,3.175735,10187.0,4.034823,407124.0,60800.0,14.934025,101860.0,25.019404,85.065975,81733.0,20.075702,39.975800,24182.0,5.939714,88182.0,21.659740,34.031155,32732.0,8.039811,12.371415,10514.0,2.582506,4.331604,7121.0,1.749099,312839.0,900.0,0.287688,20042.0,6.406490,24266.0,7.756706,10173.0,3.251832,36604.0,11.700587,14446.0,4.617711,11353.0,3.629023,22464.0,7.180690,34795.0,11.122334,72883.0,23.297287,33557.0,10.726604,17033.0,5.444654,14323.0,4.578393,312839.0,44156.0,14.114608,88541.0,28.302418,5632.0,1.800287,5833.0,1.864537,10501.0,3.356679,13920.0,4.449573,10734.0,3.431158,38107.0,12.181026,47321.0,15.126311,278.0,0.088864,23912.0,7.643548,15762.0,5.038374,17427.0,5.570597,304450.0,217055.0,71.294137,36873.0,12.111348,28411.0,9.331910,29382.0,9.650846,382.0,0.125472,312839.0,25371.0,7.501552,27780.0,590134.0,102384.0,17.349280,252477.0,94347.0,106956.0,50743.0,20.098068,145521.0,43604.0,17.270484,41509.0,16.440705,165400.0,162400.0,776.0,280062.0,150843.0,53.860574,20840.0,7.441209,15613.0,5.574837,9418.0,3.362827,16826.0,6.007955,30358.0,10.839743,17467.0,6.236833,14595.0,5.211346,4093.0,1.461462,9.0,0.003214,304450.0,275335.0,90.436853,6034.0,1.981935,877.0,0.288060,5573.0,1.830514,12850.0,4.220726,3781.0,1.241912,252477.0,19046.0,7.543657,102775.0,40.706678,91741.0,36.336379,28860.0,11.430744,7416.0,2.937297,2639.0,1.045244,291600.0,27377.0,37302.0,53528.0,57892.0,24157.0,50656.0,16303.0,15543.0,8842.0,21074.0,32029.0,46291.0,50789.0,21444.0,42729.0,13415.0,11986.0,5480.0,1560.0,1687.0,1435.0,1028.0,281.0,1098.0,325.0,290.0,525.0,478156.0,39887.0,8.341838,438269.0,91.658162,25148.0,6.073956,14739.0,22.984437,388882.0,14739.0,604412.0,482647.0,79.853974,75253.0,12.450613,19403.0,3.210227,22777.0,3.768456,4332.0,0.716730,414998.0,371882.0,43116.0,10.389448,13540.0,31.403655,29576.0,68.596345,70318.0,5182.0,18764.0,10561.0,35566.0,79.0,940.0,569612.0,485954.0,85.313161,44699.0,16978.0,10521.0,11798.0,5402.0,13914.0,10165.0,2632.0,926.0,191.0,12829.0,6993.0,3455.0,2086.0,295.0,12216.0,6164.0,3099.0,2316.0,637.0,14.686839,28.271056
2,"Dickson County, Tennessee",44554.0,18889.0,1406.0,7.443486,1362.0,7.210546,1090.0,5.770554,1098.0,5.812907,1078.0,5.707025,1225.0,6.485256,1014.0,5.368204,1300.0,6.882312,1013.0,5.362910,1849.0,9.788766,2025.0,10.720525,2162.0,11.445815,1320.0,6.988194,436.0,2.308222,277.0,1.466462,234.0,1.238816,32378.0,6274.0,19.377355,13616.0,42.053246,80.622645,6103.0,18.849219,19.778396,1553.0,4.796467,3080.0,9.512632,14.923714,1274.0,3.934771,5.411082,275.0,0.849342,1.476311,203.0,0.626969,22724.0,243.0,1.069354,2812.0,12.374582,3374.0,14.847738,506.0,2.226721,2548.0,11.212815,1230.0,5.412779,430.0,1.892272,1050.0,4.620665,1541.0,6.781377,4631.0,20.379335,1653.0,7.274247,1293.0,5.690019,1413.0,6.218095,22724.0,2213.0,9.738602,4739.0,20.854603,617.0,2.715191,703.0,3.093645,947.0,4.167400,803.0,3.533709,500.0,2.200317,2393.0,10.530716,3056.0,13.448337,133.0,0.585284,3740.0,16.458370,1928.0,8.484422,1439.0,6.332512,22209.0,15647.0,70.453420,3469.0,15.619794,2486.0,11.193660,1121.0,5.047503,26.0,0.117070,22724.0,1816.0,7.400163,21415.0,48232.0,6733.0,13.959612,18889.0,5224.0,4897.0,1973.0,10.445233,13992.0,3251.0,17.211075,2127.0,11.260522,135700.0,117500.0,671.0,20465.0,14715.0,71.903249,184.0,0.899096,515.0,2.516492,456.0,2.228194,618.0,3.019790,424.0,2.071830,201.0,0.982165,54.0,0.263865,3298.0,16.115319,0.0,0.000000,22209.0,21160.0,95.276690,21.0,0.094556,0.0,0.000000,187.0,0.842001,675.0,3.039308,166.0,0.747445,18889.0,1074.0,5.685849,4991.0,26.422786,7303.0,38.662714,3843.0,20.345174,1309.0,6.929959,369.0,1.953518,21534.0,2989.0,3010.0,2786.0,1868.0,768.0,2059.0,1188.0,3792.0,3074.0,2551.0,2631.0,2381.0,1607.0,617.0,1546.0,977.0,3025.0,2183.0,825.0,41.0,19.0,50.0,0.0,21.0,0.0,15.0,58.0,36197.0,3996.0,11.039589,32201.0,88.960411,2652.0,8.807998,1344.0,22.076216,27457.0,1344.0,47957.0,40512.0,84.475676,4098.0,8.545155,2059.0,4.293430,1194.0,2.489730,94.0,0.196009,17482.0,16906.0,576.0,3.294818,142.0,24.652778,434.0,75.347222,1072.0,89.0,224.0,0.0,759.0,0.0,91.0,45376.0,43965.0,96.890427,907.0,444.0,82.0,329.0,52.0,374.0,272.0,77.0,25.0,0.0,52.0,26.0,16.0,10.0,0.0,78.0,78.0,0.0,0.0,0.0,3.109573,29.482636

In [12]:
suffix.to_csv('../../data/Suffix2010ACS.csv', index = False)
tidy.to_csv('../../data/Tidy2010ACS.csv', index = False)