###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
import dataframe_image as dfi
from collections import deque
from functools import reduce
import matplotlib.pyplot as plt
#pd.options.display.float_format = '{:,.0f}'.format
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
def percentchange(x, y):
    return ((x - y)*100/y)

# Create a Separate Dataframe for Most Tables  
Years are not a column, they are appended to each datapoint so this is the wide dataframe. No time frames are calculated here, determined to be easier in a temporary dataframe during specific table generation.

In [3]:
Suffix2010Subject = pd.read_csv('../../data/Suffix2010Subject.csv')
Suffix2020Subject = pd.read_csv('../../data/Suffix2020Subject.csv')
Suffix2000SF1 = pd.read_csv('../../data/Suffix2000SF1.csv')
Suffix2000SF3 = pd.read_csv('../../data/Suffix2000SF3.csv')
Suffix2010SF1 = pd.read_csv('../../data/Suffix2010SF1.csv')
Suffix2010ACS = pd.read_csv('../../data/Suffix2010ACS.csv')
Suffix2020PL = pd.read_csv('../../data/Suffix2020PL.csv')
Suffix2020ACS = pd.read_csv('../../data/Suffix2020ACS.csv')

In [4]:
dfs = [Suffix2000SF1, Suffix2000SF3, Suffix2010SF1, Suffix2010ACS, Suffix2010Subject, Suffix2020PL, Suffix2020ACS, Suffix2020Subject]
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['NAME'],
                                            how='outer'), dfs)
df_merged = df_merged.set_index('NAME')
df_merged = df_merged.transpose()
numcols = list(df_merged.columns)
numcols
df_merged[numcols] = df_merged[numcols].astype(float)
df_merged.head()

NAME,"Cheatham County, Tennessee","Davidson County, Tennessee","Dickson County, Tennessee","Houston County, Tennessee","Humphreys County, Tennessee","Maury County, Tennessee","Montgomery County, Tennessee","Robertson County, Tennessee","Rutherford County, Tennessee","Stewart County, Tennessee","Sumner County, Tennessee","Trousdale County, Tennessee","Williamson County, Tennessee","Wilson County, Tennessee","Adams city, Tennessee","Ashland City town, Tennessee","Belle Meade city, Tennessee","Berry Hill city, Tennessee","Brentwood city, Tennessee","Burns town, Tennessee","Cedar Hill city, Tennessee","Charlotte town, Tennessee","Clarksville city, Tennessee","Columbia city, Tennessee","Coopertown town, Tennessee","Cross Plains city, Tennessee","Cumberland City town, Tennessee","Dickson city, Tennessee","Dover city, Tennessee","Eagleville city, Tennessee","Erin city, Tennessee","Fairview city, Tennessee","Forest Hills city, Tennessee","Franklin city, Tennessee","Gallatin city, Tennessee","Goodlettsville city, Tennessee","Greenbrier town, Tennessee","Hendersonville city, Tennessee","Kingston Springs town, Tennessee","La Vergne city, Tennessee","Lebanon city, Tennessee","McEwen city, Tennessee","Millersville city, Tennessee","Mount Juliet city, Tennessee","Mount Pleasant city, Tennessee","Murfreesboro city, Tennessee","Nashville-Davidson (balance), Tennessee","New Johnsonville city, Tennessee","Nolensville town, Tennessee","Oak Hill city, Tennessee","Pegram town, Tennessee","Pleasant View city, Tennessee","Portland city, Tennessee","Ridgetop city, Tennessee","Slayden town, Tennessee","Smyrna town, Tennessee","Springfield city, Tennessee","Spring Hill city, Tennessee","Tennessee Ridge town, Tennessee","Thompson's Station town, Tennessee","Vanleer town, Tennessee","Watertown city, Tennessee","Waverly city, Tennessee","Westmoreland town, Tennessee","White Bluff town, Tennessee","White House city, Tennessee",Tennessee,United States,GNRC,GNRC Region,MPO,Rutherford Incorporated,Rutherford Unincorporated,Wilson Incorporated,Wilson Unincorporated,Cheatham Incorporated,Cheatham Unincorporated,Dickson Incorporated,Dickson Unincorporated,Humphreys Incorporated,Humphreys Unincorporated,Montgomery Incorporated,Montgomery Unincorporated,"Nashville-Davidson metropolitan government (balance), Tennessee"
Population 2000,35912.0,569891.0,43156.0,8088.0,17929.0,69498.0,134768.0,54433.0,182023.0,12370.0,130449.0,7259.0,126638.0,88809.0,566.0,3641.0,2943.0,674.0,23445.0,1366.0,298.0,1153.0,103455.0,33055.0,3027.0,1381.0,316.0,12244.0,1442.0,464.0,1490.0,5800.0,4710.0,41842.0,23230.0,13780.0,4940.0,40620.0,2773.0,18687.0,20235.0,1702.0,5308.0,12366.0,4491.0,68816.0,545524.0,1905.0,3099.0,4493.0,2146.0,2934.0,8458.0,1083.0,185.0,25569.0,14329.0,7715.0,1334.0,1283.0,310.0,1358.0,4028.0,2093.0,2142.0,7220.0,5689283.0,281421906.0,1411725.0,1481223.0,1221741.0,113536.0,68487.0,33959.0,54850.0,11494.0,24418.0,17400.0,25756.0,7635.0,10294.0,103455.0,31313.0,NaN
Male Under 5 2000,1372.0,19466.0,1538.0,268.0,567.0,2444.0,5901.0,1897.0,7027.0,374.0,4567.0,217.0,4722.0,3074.0,20.0,116.0,103.0,11.0,685.0,43.0,11.0,32.0,4749.0,1269.0,104.0,46.0,9.0,489.0,29.0,12.0,50.0,239.0,124.0,1850.0,844.0,466.0,206.0,1401.0,104.0,944.0,717.0,63.0,254.0,493.0,153.0,2313.0,18705.0,68.0,117.0,113.0,107.0,140.0,373.0,32.0,4.0,1147.0,523.0,434.0,43.0,51.0,8.0,61.0,130.0,83.0,64.0,365.0,192283.0,9810733.0,50990.0,53434.0,43197.0,4416.0,2611.0,1271.0,1803.0,467.0,905.0,640.0,898.0,261.0,306.0,4749.0,1152.0,NaN
Female Under 5 2000,1187.0,18347.0,1437.0,273.0,505.0,2322.0,5552.0,1823.0,6629.0,353.0,4266.0,222.0,4447.0,2964.0,17.0,112.0,85.0,12.0,654.0,37.0,12.0,32.0,4546.0,1205.0,97.0,34.0,12.0,475.0,35.0,13.0,46.0,245.0,113.0,1708.0,856.0,452.0,195.0,1266.0,82.0,913.0,697.0,56.0,228.0,473.0,138.0,2163.0,17630.0,66.0,117.0,100.0,86.0,124.0,358.0,30.0,5.0,1055.0,561.0,416.0,45.0,40.0,10.0,40.0,110.0,69.0,64.0,271.0,182597.0,9365065.0,48005.0,50327.0,40798.0,4144.0,2485.0,1210.0,1754.0,404.0,783.0,623.0,814.0,232.0,273.0,4546.0,1006.0,NaN
Male 5 to 14 2000,2960.0,35289.0,3412.0,577.0,1270.0,5258.0,11091.0,4379.0,13737.0,895.0,9939.0,550.0,11183.0,6865.0,47.0,270.0,289.0,19.0,2357.0,96.0,23.0,79.0,8505.0,2380.0,257.0,126.0,24.0,971.0,86.0,32.0,99.0,528.0,387.0,3217.0,1636.0,945.0,418.0,3077.0,246.0,1649.0,1337.0,128.0,444.0,1097.0,347.0,4396.0,33520.0,123.0,312.0,320.0,173.0,291.0,647.0,81.0,13.0,1892.0,1004.0,684.0,94.0,99.0,16.0,101.0,255.0,130.0,183.0,682.0,406102.0,21043474.0,102147.0,107405.0,86650.0,7969.0,5768.0,2535.0,4330.0,980.0,1980.0,1358.0,2054.0,506.0,764.0,8505.0,2586.0,NaN
Female 5 to 14 2000,2728.0,33667.0,3185.0,541.0,1181.0,4941.0,10213.0,4046.0,13175.0,837.0,9347.0,467.0,10683.0,6529.0,46.0,268.0,278.0,13.0,2229.0,87.0,26.0,76.0,7791.0,2234.0,237.0,106.0,21.0,855.0,75.0,29.0,92.0,479.0,377.0,3233.0,1545.0,880.0,378.0,2831.0,219.0,1584.0,1342.0,123.0,363.0,1094.0,337.0,4274.0,32038.0,138.0,319.0,290.0,147.0,246.0,636.0,74.0,11.0,1915.0,894.0,673.0,82.0,86.0,22.0,88.0,243.0,163.0,130.0,661.0,384866.0,20034103.0,96599.0,101540.0,82388.0,7802.0,5373.0,2524.0,4005.0,880.0,1848.0,1181.0,2004.0,504.0,677.0,7791.0,2422.0,NaN

In [5]:
df_merged.size

102396

### Data is prepped for geo-sorting and exporting

In [6]:
#GALLATIN
#Geographies Needed: Tennessee, GNRC Region, Goodlettsville city, Tennessee, Millersville city, Tennessee, Portland city, Tennessee, White House city, Tennessee, 
#Gallatin city, Tennessee, Hendersonville city, Tennessee, Westmoreland City, Tennessee, Sumner County, Tennessee 
gallatindata = df_merged[['Tennessee', 'GNRC Region','Sumner County, Tennessee','Gallatin city, Tennessee', 'Goodlettsville city, Tennessee', 
                       'Millersville city, Tennessee', 'Portland city, Tennessee', 'White House city, Tennessee', 'Hendersonville city, Tennessee', 
                       'Westmoreland town, Tennessee', 'United States']] #filter geos
gallatindata.columns = ['Tennessee', 'GNRC Region','Sumner County','Gallatin', 'Goodlettsville', 'Millersville', 'Portland', 
                        'White House', 'Hendersonville', 'Westmoreland', 'US'] #rename geos
gallatindata = gallatindata.transpose().reset_index().rename(columns = {'index':'NAME'})

In [9]:
gallatindata.head()

,NAME,Population 2000,Male Under 5 2000,Female Under 5 2000,Male 5 to 14 2000,Female 5 to 14 2000,Male 15 to 24 2000,Female 15 to 24 2000,Male 5 to 9 2000,Female 5 to 9 2000,Male 10 to 14 2000,Female 10 to 14 2000,Male 15 to 17 2000,Female 15 to 17 2000,Male 18 to 24 2000,Female 18 to 24 2000,Male 25 to 34 2000,Female 25 to 34 2000,Male 35 to 44 2000,Female 35 to 44 2000,Male 45 to 54 2000,Female 45 to 54 2000,Male 55 to 64 2000,Female 55 to 64 2000,Male 65 to 74 2000,Female 65 to 74 2000,Male 75 to 84 2000,Female 75 to 84 2000,Male 85 and Older 2000,Female 85 and Older 2000,Age:Under 5 2000,Age %:Under 5 2000,Age:5 to 9 2000,Age%:5 to 9 2000,Age:10 to 14 2000,Age%:10 to 14 2000,Age:15 to 17 2000,Age%:15 to 17 2000,Age:18 to 24 2000,Age%:18 to 24 2000,Age:25 to 34 2000,Age%:25 to 34 2000,Age:35 to 44 2000,Age%:35 to 44 2000,Age:45 to 54 2000,Age%:45 to 54 2000,Age:55 to 64 2000,Age%:55 to 64 2000,Age:65 to 74 2000,Age%:65 to 74 2000,Age:75 to 84 2000,Age%:75 to 84 2000,Age:85 and Older 2000,Age%:85 and Older 2000,Age:Under 18 2000,Age%:Under 18 2000,Age:18 to 54 2000,Age%:18 to 54 2000,Age:55 and Older 2000,Age%:55 and Older 2000,Age:65 and Older 2000,Age%:65 and Older 2000,White Alone 2000,White Alone % 2000,Non-White Population: Race 2000,Black or African American Alone 2000,Black or African American Alone % 2000,Black or African American Alone % Non-White Population 2000,American Indian Alaska Native Alone 2000,American Indian Alaska Native Alone % 2000,American Indian Alaska Native Alone % Non-White Population 2000,Asian Alone 2000,Asian Alone % 2000,Asian Alone % Non-White Population 2000,Native Hawaiian Other Pacific Islander Alone 2000,Native Hawaiian Other Pacific Islander Alone % 2000,Native Hawaiian Other Pacific Islander Alone % Non-White Population 2000,Some Other Race Alone 2000,Some Other Race Alone % 2000,Some Other Race Alone % Non-White Population 2000,Two or More Races 2000,Two or More Races % 2000,Two or More Races % Non-White Population 2000,Hispanic or Latino 2000,Hispanic or Latino % 2000,Not Hispanic or Latino 2000,Not Hispanic or Latino % 2000,Minority 2000,Minority % 2000,White Alone Not Hispanic or Latino 2000,White Alone Not Hispanic or Latino % 2000,Total Households 2000,Family Households 2000,Family Households: Married Couple Family 2000,"Household Type%: Family, Married Couple Households 2000",Family Households: Not Married Couple Family 2000,"Household Type%: Family, Not Married Couple Households 2000",Family Households: Not Married Couple: Male no Spouse 2000,Family Households: Not Married Couple: Female no Spouse 2000,Nonfamily Households 2000,Nonfamily Households: Householder Alone 2000,"Household Type%: Nonfamily, Householder Alone 2000",Nonfamily Households: Householder not Alone 2000,"Household Type%: Nonfamily, Householder Not Alone 2000",Average Household Size 2000,Occupancy:Total Households 2000,Occupancy:Occupied Units 2000,Occupancy%:Occupied Units 2000,Occupancy:Vacant Units 2000,Occupancy%:Vacant Units 2000,Tenure:Total Households 2000,Tenure:Owners 2000,Tenure%:Owners 2000,Tenure:Renters 2000,Tenure%:Renters 2000,Median Household Income 2000,HHIncome:Total Households 2000,"HHIncome:Less than 10,000 2000","HHIncome%:Less than 10,000 2000","HHIncome:10 to 14,999 2000","HHIncome%:10 to 14,999 2000","HHIncome:15 to 19,999 2000","HHIncome%:15 to 19,999 2000","HHIncome:20 to 24,999 2000","HHIncome%:20 to 24,999 2000","HHIncome:25 to 29,999 2000","HHIncome%:25 to 29,999 2000","HHIncome:30 to 34,999 2000","HHIncome:%30 to 34,999 2000","HHIncome:35 to 39,999 2000","HHIncome%:35 to 39,999 2000","HHIncome:40 to 44,999 2000","HHIncome%:40 to 44,999 2000","HHIncome:45 to 49,999 2000","HHIncome%:45 to 49,999 2000","HHIncome:50 to 59,999 2000","HHIncome%:50 to 59,999 2000","HHIncome:60 to 74,999 2000","HHIncome%:60 to 74,999 2000","HHIncome:75 to 99,999 2000","HHIncome%:75 to 99,999 2000","HHIncome:100 to 124,999 2000","HHIncome%:100 to 124,999 2000","HHIncome:125 to 149,999 2000","HHIncome%:125 to 149,999 2000","HHIncome:150 to 199,999 2000","HHIncome%:150 to 199,999 2000",HHIncome:200K or More 2000,HHIncome%:200K or More 2000,Ed:Population 25+ Educational Attainment 2000,Ed:Less than High School 2000,Ed%:Less than High School 2000,Ed:High School Graduate or Equivalency 2000,Ed%:High School Graduate or Equivalency 2000,Ed%:High School Graduate or More 2000,Ed:Some College 2000,Ed%:Some College 2000,Ed%:Some College or More 2000,Ed:Associates 2000,Ed%:Associates 2000,Ed:Bachelors 2000,Ed%:Bachelors 2000,Ed%:Bachelors or More 2000,Ed:Masters 2000,Ed%:Masters 2000,Ed%:Masters or More 2000,Ed:Professional School Degree 2000,Ed%:Professional School Degree 2000,Ed%:Professional School Degree or More 2000,Ed:Doctorate Degree 2000,Ed%:Doctorate Degree 2000,Ind:Employed Civilians 16+ 2000,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2000","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2000",Ind:Construction 2000,Ind%:Construction 2000,Ind:Manufacturing 2000,Ind%:Manufacturing 2000,Ind:Wholesale Trade 2000,Ind%:Wholesale Trade 2000,Ind:Retail Trade 2000,Ind%:Retail Trade 2000,"Ind:Transportation and Warehousing, Utilities 2000","Ind%:Transportation and Warehousing, Utilities 2000",Ind:Information 2000,Ind%:Information 2000,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind:Educational, Health and Social Services 2000","Ind%:Educational, Health and Social Services 2000","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2000","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2000",Ind:Other Services (Except Public Administration) 2000,Ind%:Other Services (Except Public Administration) 2000,Ind:Public Administration 2000,Ind%:Public Administration 2000,Employed Civilians 16+ Occupational 2000,"Occ:Management, Business, and Financial Operations 2000","Occ%:Management, Business, and Financial Operations 2000",Occ:Professional and Related 2000,Occ%:Professional and Related 2000,Occ:Healthcare Support 2000,Occ%:Healthcare Support 2000,Occ:Protective Services 2000,Occ%:Protective Services 2000,Occ:Food Preparation and Serving Related 2000,Occ%:Food Preparation and Serving Related 2000,Occ:Building and Grounds Cleaning and Maintenance 2000,Occ%:Building and Grounds Cleaning and Maintenance 2000,Occ:Personal Care and Service 2000,Occ%:Personal Care and Service 2000,Occ:Sales and Related 2000,Occ%:Sales and Related 2000,Occ:Office and Administrative Support 2000,Occ%:Office and Administrative Support 2000,"Occ:Farming, Fishing, and Forestry 2000","Occ%:Farming, Fishing, and Forestry 2000","Occ:Construction, Extraction, and Maintenance 2000","Occ%:Construction, Extraction, and Maintenance 2000",Occ:Production 2000,Occ%:Production 2000,Occ:Transportation and Material Moving 2000,Occ%:Transportation and Material Moving 2000,Sector: Total Workers 2000,Sector:Private 2000,Sector%:Private 2000,Sector:Public 2000,Sector%:Public 2000,Sector:Self-Employed 2000,Sector%:Self-Employed 2000,Sector:Non-Profit 2000,Sector%:Non-Profit 2000,Sector:Unpaid Family Workers 2000,Sector%:Unpaid Family Workers 2000,Employed 2000,Unemployed 2000,Unemployment Rate 2000,Per Capita Income 2000,Poverty:Population for Whom Poverty Status is Determined 2000,Poverty: Population Below Poverty Level 2000,Poverty%: Below Poverty Level 2000,CB:Total Housing Units 2000,CB:Cost Burdened Housholds 2000,CB:Renter Occupied Units 2000,CB:Cost Burdened Renters 2000,CB%:Cost Burdened Renters 2000,CB:Owner Occupied Units 2000,CB:Cost Burdened Homeowners 2000,CB%: Cost Burdened Homeowners 2000,CB:Severe Cost Burdened Households 2000,CB%:Severe Cost Burdened Households 2000,Median Home Value Owner Occupied 2000,Median Gross Rent 2000,Units:Total Series 2000,"Units:1 Unit, Detached 2000","Units%:1 Unit, Detached 2000","Units:1 Unit, Attached 2000","Units%:1 Unit, Attached 2000",Units:2 2000,Units%:2 2000,Units:3 to 4 2000,Units%:3 to 4 2000,Units:5 to 9 2000,Units%:5 to 9 2000,Units:10 to 19 2000,Units%:10 to 19 2000,Units:20 to 49 2000,Units%:20 to 49 2000,Units:50 or More 2000,Units%:50 or More 2000,Units:Mobile Home 2000,Units%:Mobile Home 2000,"Units:Boat, RV, Van etc 2000","Units%:Boat, RV, Van etc 2000",Transpo:Workers Commuting 2000,"Transpo:Car, Truck, or Van 2000","Transpo%:Car, Truck, or Van 2000",Transpo:Public Transportation 2000,Transpo%:Public Transportation 2000,Transpo:Bicycle 2000,Transpo%:Bicycle 2000,Transpo:Walk 2000,Transpo%:Walk 2000,Transpo:Worked From Home 2000,Transpo%:Worked From Home 2000,"Transpo:Taxi, Motorcycle, Other 2000","Transpo%:Taxi, Motorcycle, Other 2000",Vehicles:Households 2000,Vehicles:None 2000,Vehicles%:None 2000,Vehicles:One 2000,Vehicles%:One 2000,Vehicles:Two 2000,Vehicles%:Two 2000,Vehicles:Three 2000,Vehicles%:Three 2000,Vehicles:Four 2000,Vehicles%:Four 2000,Vehicles:Five or More 2000,Vehicles%:Five or More 2000,Vet:Population 18+ 2000,Vet:Veteran 2000,Vet%:Veteran 2000,Vet:Nonveteran 2000,Vet%:Nonveteran 2000,Vet:Veteran 18 to 64 2000,Vet%:Veterans who are 18 to 64 2000,Vet:Veteran 65 and Older 2000,Vet%:Veterans who are 65 and Older 2000,Vet:Nonveteran 18 to 64 2000,Vet:Nonveteran 65 and Older 2000,Disability Tally 2000,GeoMobility:Total 2000,GeoMobility:Same House as 1995 2000,GeoMobility%:Same House as 1995 2000,GeoMobility:Moved Since 1995 2000,GeoMobility:Moved Same County as 1995 2000,GeoMobility%:Moved Same County as 1995 2000,GeoMobility:Moved Different County Same State as 1995 2000,GeoMobility%:Moved Different County Same State as 1995 2000,GeoMobility:Moved Different State from 1995 2000,GeoMobility%:Moved Different State from 1995 2000,GeoMobility:Moved From Abroad Since 1995 2000,GeoMobility%:Moved From Abroad Since 1995 2000,ForeignBorn:Foreign Born 2000,ForeignBorn%:Foreign Born 2000,ForeignBorn:Native Born 2000,ForeignBorn:Foreign Born Naturalized Citizen 2000,ForeignBorn%:Foreign Born Population that are Naturalized Citizen 2000,ForeignBorn:Foreign Born Not a Citizen 2000,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen 2000,Foreign Born Population 2000,ForeignBorn:Europe 2000,ForeignBorn:Asia 2000,ForeignBorn:Africa 2000,ForeignBorn:Oceania 2000,"ForeignBorn:Central & South America, Caribbean 2000",ForeignBorn:Canada & Other Northern American 2000,Language:Population 5 and Older 2000,Language:Speak Only English 2000,Language%:Speak Only English 2000,Language:Speak Spanish 2000,Language:Spanish:Speak English Very Well 2000,Language:Spanish:Speak English Well 2000,Language:Spanish:Speak English Not Well 2000,Language:Spanish:Speak English Not At All 2000,Language:Speak Other Indo-European Language 2000,Language:Other Indo-European:Speak English Very Well 2000,Language:Other Indo-European:Speak English Well 2000,Language:Other Indo-European:Speak English Not Well 2000,Language:Other Indo-European:Speak English Not At All 2000,Language:Speak Asian or Pacific Island Language 2000,Language:Asian or Pacific Island:Speak English Very Well 2000,Language:Asian or Pacific Island:Speak English Well 2000,Language:Asian or Pacific Island:Speak English Not Well 2000,Language:Asian or Pacific Island:Speak English Not At All 2000,Language:Speak Other Language 2000,Language:Other:Speak English Very Well 2000,Language:Other:Speak English Well 2000,Language:Other:Speak English Not Well 2000,Language:Other:Speak English Not At All 2000,Language%:Speak Language Besides English 2000,Language%:Of Those that Speak Another Language and Speak English Not Well or At All 2000,Population 2010,Male Under 5 2010,Female Under 5 2010,Male 5 to 9 2010,Female 5 to 9 2010,Male 5 to 14 2010,Female 5 to 14 2010,Male 15 to 24 2010,Female 15 to 24 2010,Male 10 to 14 2010,Female 10 to 14 2010,Male 15 to 17 2010,Female 15 to 17 2010,Male 18 to 24 2010,Female 18 to 24 2010,Male 25 to 34 2010,Female 25 to 34 2010,Male 35 to 44 2010,Female 35 to 44 2010,Male 45 to 54 2010,Female 45 to 54 2010,Male 55 to 64 2010,Female 55 to 64 2010,Male 65 to 74 2010,Female 65 to 74 2010,Male 75 to 84 2010,Female 75 to 84 2010,Male 85 and Older 2010,Female 85 and Older 2010,Age:Under 5 2010,Age %:Under 5 2010,Age:5 to 9 2010,Age%:5 to 9 2010,Age:10 to 14 2010,Age%:10 to 14 2010,Age:15 to 17 2010,Age%:15 to 17 2010,Age:18 to 24 2010,Age%:18 to 24 2010,Age:25 to 34 2010,Age%:25 to 34 2010,Age:35 to 44 2010,Age%:35 to 44 2010,Age:45 to 54 2010,Age%:45 to 54 2010,Age:55 to 64 2010,Age%:55 to 64 2010,Age:65 to 74 2010,Age%:65 to 74 2010,Age:75 to 84 2010,Age%:75 to 84 2010,Age:85 and Older 2010,Age%:85 and Older 2010,Age:Under 18 2010,Age%:Under 18 2010,Age:18 to 54 2010,Age%:18 to 54 2010,Age:55 and Older 2010,Age%:55 and Older 2010,Age:65 and Older 2010,Age%:65 and Older 2010,White Alone 2010,White Alone % 2010,Non-White Population: Race 2010,Black or African American Alone 2010,Black or African American Alone % 2010,Black or African American Alone % Non-White Population 2010,American Indian Alaska Native Alone 2010,American Indian Alaska Native Alone % 2010,American Indian Alaska Native Alone % Non-White Population 2010,Asian Alone 2010,Asian Alone % 2010,Asian Alone % Non-White Population 2010,Native Hawaiian Other Pacific Islander Alone 2010,Native Hawaiian Other Pacific Islander Alone % 2010,Native Hawaiian Other Pacific Islander Alone % Non-White Population 2010,Some Other Race Alone 2010,Some Other Race Alone % 2010,Some Other Race Alone % Non-White Population 2010,Two or More Races 2010,Two or More Races % 2010,Two or More Races % Non-White Population 2010,Hispanic or Latino 2010,Hispanic or Latino % 2010,Not Hispanic or Latino 2010,Not Hispanic or Latino % 2010,Minority 2010,Minority % 2010,White Alone Not Hispanic or Latino 2010,White Alone Not Hispanic or Latino % 2010,Total Households 2010,Family Households 2010,Family Households: Married Couple Family 2010,"Household Type%: Family, Married Couple Households 2010",Family Households: Not Married Couple Family 2010,"Household Type%: Family, Not Married Couple Households 2010",Family Households: Not Married Couple: Male no Spouse 2010,Family Households: Not Married Couple: Female no Spouse 2010,Nonfamily Households 2010,Nonfamily Households: Householder Alone 2010,"Household Type%: Nonfamily, Householder Alone 2010",Nonfamily Households: Householder not Alone 2010,"Household Type%: Nonfamily, Householder Not Alone 2010",Average Household Size 2010,Occupancy:Total Households 2010,Occupancy:Occupied Units 2010,Occupancy%:Occupied Units 2010,Occupancy:Vacant Units 2010,Occupancy%:Vacant Units 2010,Tenure:Total Households 2010,Tenure:Owners 2010,Tenure%:Owners 2010,Tenure:Renters 2010,Tenure%:Renters 2010,Median Household Income 2010,HHIncome:Total Households 2010,"HHIncome:Less than 10,000 2010","HHIncome%:Less than 10,000 2010","HHIncome:10 to 14,999 2010","HHIncome%:10 to 14,999 2010","HHIncome:15 to 19,999 2010","HHIncome%:15 to 19,999 2010","HHIncome:20 to 24,999 2010","HHIncome%:20 to 24,999 2010","HHIncome:25 to 29,999 2010","HHIncome%:25 to 29,999 2010","HHIncome:30 to 34,999 2010","HHIncome:%30 to 34,999 2010","HHIncome:35 to 39,999 2010","HHIncome%:35 to 39,999 2010","HHIncome:40 to 44,999 2010","HHIncome%:40 to 44,999 2010","HHIncome:45 to 49,999 2010","HHIncome%:45 to 49,999 2010","HHIncome:50 to 59,999 2010","HHIncome%:50 to 59,999 2010","HHIncome:60 to 74,999 2010","HHIncome%:60 to 74,999 2010","HHIncome:75 to 99,999 2010","HHIncome%:75 to 99,999 2010","HHIncome:100 to 124,999 2010","HHIncome%:100 to 124,999 2010","HHIncome:125 to 149,999 2010","HHIncome%:125 to 149,999 2010","HHIncome:150 to 199,999 2010","HHIncome%:150 to 199,999 2010",HHIncome:200K or More 2010,HHIncome%:200K or More 2010,Ed:Population 25+ Educational Attainment 2010,Ed:Less than High School 2010,Ed%:Less than High School 2010,Ed:High School Graduate or Equivalency 2010,Ed%:High School Graduate or Equivalency 2010,Ed%:High School Graduate or More 2010,Ed:Some College 2010,Ed%:Some College 2010,Ed%:Some College or More 2010,Ed:Associates 2010,Ed%:Associates 2010,Ed:Bachelors 2010,Ed%:Bachelors 2010,Ed%:Bachelors or More 2010,Ed:Masters 2010,Ed%:Masters 2010,Ed%:Masters or More 2010,Ed:Professional School Degree 2010,Ed%:Professional School Degree 2010,Ed%:Professional School Degree or More 2010,Ed:Doctorate Degree 2010,Ed%:Doctorate Degree 2010,Ind:Employed Civilians 16+ 2010,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2010","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2010",Ind:Construction 2010,Ind%:Construction 2010,Ind:Manufacturing 2010,Ind%:Manufacturing 2010,Ind:Wholesale Trade 2010,Ind%:Wholesale Trade 2010,Ind:Retail Trade 2010,Ind%:Retail Trade 2010,"Ind:Transportation and Warehousing, Utilities 2010","Ind%:Transportation and Warehousing, Utilities 2010",Ind:Information 2010,Ind%:Information 2010,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind:Educational, Health and Social Services 2010","Ind%:Educational, Health and Social Services 2010","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2010","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2010",Ind:Other Services (Except Public Administration) 2010,Ind%:Other Services (Except Public Administration) 2010,Ind:Public Administration 2010,Ind%:Public Administration 2010,Employed Civilians 16+ Occupational 2010,"Occ:Management, Business, and Financial Operations 2010","Occ%:Management, Business, and Financial Operations 2010",Occ:Professional and Related 2010,Occ%:Professional and Related 2010,Occ:Healthcare Support 2010,Occ%:Healthcare Support 2010,Occ:Protective Services 2010,Occ%:Protective Services 2010,Occ:Food Preparation and Serving Related 2010,Occ%:Food Preparation and Serving Related 2010,Occ:Building and Grounds Cleaning and Maintenance 2010,Occ%:Building and Grounds Cleaning and Maintenance 2010,Occ:Personal Care and Service 2010,Occ%:Personal Care and Service 2010,Occ:Sales and Related 2010,Occ%:Sales and Related 2010,Occ:Office and Administrative Support 2010,Occ%:Office and Administrative Support 2010,"Occ:Farming, Fishing, and Forestry 2010","Occ%:Farming, Fishing, and Forestry 2010","Occ:Construction, Extraction, and Maintenance 2010","Occ%:Construction, Extraction, and Maintenance 2010",Occ:Production 2010,Occ%:Production 2010,Occ:Transportation and Material Moving 2010,Occ%:Transportation and Material Moving 2010,Sector: Total Workers 2010,Sector:Private 2010,Sector%:Private 2010,Sector:Public 2010,Sector%:Public 2010,Sector:Self-Employed 2010,Sector%:Self-Employed 2010,Sector:Non-Profit 2010,Sector%:Non-Profit 2010,Sector:Unpaid Family Workers 2010,Sector%:Unpaid Family Workers 2010,Employed 2010,Unemployed 2010,Unemployment Rate 2010,Per Capita Income 2010,Poverty:Population for Whom Poverty Status is Determined 2010,Poverty: Population Below Poverty Level 2010,Poverty%: Below Poverty Level 2010,CB:Total Housing Units 2010,CB:Cost Burdened Housholds 2010,CB:Renter Occupied Units 2010,CB:Cost Burdened Renters 2010,CB%:Cost Burdened Renters 2010,CB:Owner Occupied Units 2010,CB:Cost Burdened Homeowners 2010,CB%: Cost Burdened Homeowners 2010,CB:Severe Cost Burdened Households 2010,CB%:Severe Cost Burdened Households 2010,Median Home Value Owner Occupied with Mortgage 2010,Median Home Value Owner Occupied without Mortgage 2010,Median Gross Rent 2010,Units:Total Series 2010,"Units:1 Unit, Detached 2010","Units%:1 Unit, Detached 2010","Units:1 Unit, Attached 2010","Units%:1 Unit, Attached 2010",Units:2 2010,Units%:2 2010,Units:3 

In [7]:
#export
gallatindata.to_csv('../../data/Geography Specific Output/GallatinTables.csv', index = False)

# Create a Separate Dataframe for Most Figures  
This dataframe will be tidy data formatted with years and time frames

In [8]:
Tidy2010Subject = pd.read_csv('../../data/Tidy2010Subject.csv')
Tidy2020Subject = pd.read_csv('../../data/Tidy2020Subject.csv')
Tidy2000SF1 = pd.read_csv('../../data/Tidy2000SF1.csv')
Tidy2000SF3 = pd.read_csv('../../data/Tidy2000SF3.csv')
Tidy2010SF1 = pd.read_csv('../../data/Tidy2010SF1.csv')
Tidy2010ACS = pd.read_csv('../../data/Tidy2010ACS.csv')
Tidy2020PL = pd.read_csv('../../data/Tidy2020PL.csv')
Tidy2020ACS = pd.read_csv('../../data/Tidy2020ACS.csv')

In [10]:
dfs2000 = [Tidy2000SF1, Tidy2000SF3]
dfs2010 = [Tidy2010SF1, Tidy2010ACS, Tidy2010Subject]
dfs2020 = [Tidy2020PL, Tidy2020ACS, Tidy2020Subject]
#merging 2000's dataframes and adding multi-index for both year and time frame categories
twothousand = Tidy2000SF1.merge(Tidy2000SF3, on = 'NAME')
twothousand['Year'] = 2000
twothousand = twothousand.set_index(['NAME'])
twothousand.columns = pd.MultiIndex.from_product([twothousand.columns, ['2000'], ['None']])
#merging 2010's dataframes and adding multi-index for both year and time frame categories
twothousandten = reduce(lambda  left,right: pd.merge(left,right,on=['NAME'],
                                                     how='outer'), dfs2010)
twothousandten['Year'] = 2010
twothousandten = twothousandten.set_index(['NAME'])
twothousandten.columns = pd.MultiIndex.from_product([twothousandten.columns, ['2010'], ['None']])
#merging 2020's dataframes and adding multi-index for both year and time frame categories
twothousandtwenty = reduce(lambda  left,right: pd.merge(left,right,on=['NAME'],
                                                        how='outer'), dfs2020)
twothousandtwenty['Year'] = 2020
twothousandtwenty = twothousandtwenty.set_index(['NAME'])
twothousandtwenty.columns = pd.MultiIndex.from_product([twothousandtwenty.columns, ['2020'], ['None']])
dfs = [twothousand, twothousandten, twothousandtwenty]
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['NAME'],
                                            how='outer'), dfs)
df = df_merged
df.head(2)

,Population,Male Under 5,Female Under 5,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters,Median Household Income,HHIncome:Total Households,"HHIncome:Less than 10,000","HHIncome%:Less than 10,000","HHIncome:10 to 14,999","HHIncome%:10 to 14,999","HHIncome:15 to 19,999","HHIncome%:15 to 19,999","HHIncome:20 to 24,999","HHIncome%:20 to 24,999","HHIncome:25 to 29,999","HHIncome%:25 to 29,999","HHIncome:30 to 34,999","HHIncome:%30 to 34,999","HHIncome:35 to 39,999","HHIncome%:35 to 39,999","HHIncome:40 to 44,999","HHIncome%:40 to 44,999","HHIncome:45 to 49,999","HHIncome%:45 to 49,999","HHIncome:50 to 59,999","HHIncome%:50 to 59,999","HHIncome:60 to 74,999","HHIncome%:60 to 74,999","HHIncome:75 to 99,999","HHIncome%:75 to 99,999","HHIncome:100 to 124,999","HHIncome%:100 to 124,999","HHIncome:125 to 149,999","HHIncome%:125 to 149,999","HHIncome:150 to 199,999","HHIncome%:150 to 199,999",HHIncome:200K or More,HHIncome%:200K or More,Ed:Population 25+ Educational Attainment,Ed:Less than High School,Ed%:Less than High School,Ed:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency,Ed%:High School Graduate or More,Ed:Some College,Ed%:Some College,Ed%:Some College or More,Ed:Associates,Ed%:Associates,Ed:Bachelors,Ed%:Bachelors,Ed%:Bachelors or More,Ed:Masters,Ed%:Masters,Ed%:Masters or More,Ed:Professional School Degree,Ed%:Professional School Degree,Ed%:Professional School Degree or More,Ed:Doctorate Degree,Ed%:Doctorate Degree,Ind:Employed Civilians 16+,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining",Ind:Construction,Ind%:Construction,Ind:Manufacturing,Ind%:Manufacturing,Ind:Wholesale Trade,Ind%:Wholesale Trade,Ind:Retail Trade,Ind%:Retail Trade,"Ind:Transportation and Warehousing, Utilities","Ind%:Transportation and Warehousing, Utilities",Ind:Information,Ind%:Information,"Ind:Finance, Insurance, Real Estate and Rental and Leasing","Ind%:Finance, Insurance, Real Estate and Rental and Leasing","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind:Educational, Health and Social Services","Ind%:Educational, Health and Social Services","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services",Ind:Other Services (Except Public Administration),Ind%:Other Services (Except Public Administration),Ind:Public Administration,Ind%:Public Administration,Employed Civilians 16+ Occupational,"Occ:Management, Business, and Financial Operations","Occ%:Management, Business, and Financial Operations",Occ:Professional and Related,Occ%:Professional and Related,Occ:Healthcare Support,Occ%:Healthcare Support,Occ:Protective Services,Occ%:Protective Services,Occ:Food Preparation and Serving Related,Occ%:Food Preparation and Serving Related,Occ:Building and Grounds Cleaning and Maintenance,Occ%:Building and Grounds Cleaning and Maintenance,Occ:Personal Care and Service,Occ%:Personal Care and Service,Occ:Sales and Related,Occ%:Sales and Related,Occ:Office and Administrative Support,Occ%:Office and Administrative Support,"Occ:Farming, Fishing, and Forestry","Occ%:Farming, Fishing, and Forestry","Occ:Construction, Extraction, and Maintenance","Occ%:Construction, Extraction, and Maintenance",Occ:Production,Occ%:Production,Occ:Transportation and Material Moving,Occ%:Transportation and Material Moving,Sector: Total Workers,Sector:Private,Sector%:Private,Sector:Public,Sector%:Public,Sector:Self-Employed,Sector%:Self-Employed,Sector:Non-Profit,Sector%:Non-Profit,Sector:Unpaid Family Workers,Sector%:Unpaid Family Workers,Employed,Unemployed,Unemployment Rate,Per Capita Income,Poverty:Population for Whom Poverty Status is Determined,Poverty: Population Below Poverty Level,Poverty%: Below Poverty Level,CB:Total Housing Units,CB:Cost Burdened Housholds,CB:Renter Occupied Units,CB:Cost Burdened Renters,CB%:Cost Burdened Renters,CB:Owner Occupied Units,CB:Cost Burdened Homeowners,CB%: Cost Burdened Homeowners,CB:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households,Median Home Value Owner Occupied,Median Gross Rent,Units:Total Series,"Units:1 Unit, Detached","Units%:1 Unit, Detached","Units:1 Unit, Attached","Units%:1 Unit, Attached",Units:2,Units%:2,Units:3 to 4,Units%:3 to 4,Units:5 to 9,Units%:5 to 9,Units:10 to 19,Units%:10 to 19,Units:20 to 49,Units%:20 to 49,Units:50 or More,Units%:50 or More,Units:Mobile Home,Units%:Mobile Home,"Units:Boat, RV, Van etc","Units%:Boat, RV, Van etc",Transpo:Workers Commuting,"Transpo:Car, Truck, or Van","Transpo%:Car, Truck, or Van",Transpo:Public Transportation,Transpo%:Public Transportation,Transpo:Bicycle,Transpo%:Bicycle,Transpo:Walk,Transpo%:Walk,Transpo:Worked From Home,Transpo%:Worked From Home,"Transpo:Taxi, Motorcycle, Other","Transpo%:Taxi, Motorcycle, Other",Vehicles:Households,Vehicles:None,Vehicles%:None,Vehicles:One,Vehicles%:One,Vehicles:Two,Vehicles%:Two,Vehicles:Three,Vehicles%:Three,Vehicles:Four,Vehicles%:Four,Vehicles:Five or More,Vehicles%:Five or More,Vet:Population 18+,Vet:Veteran,Vet%:Veteran,Vet:Nonveteran,Vet%:Nonveteran,Vet:Veteran 18 to 64,Vet%:Veterans who are 18 to 64,Vet:Veteran 65 and Older,Vet%:Veterans who are 65 and Older,Vet:Nonveteran 18 to 64,Vet:Nonveteran 65 and Older,Disability Tally,GeoMobility:Total,GeoMobility:Same House as 1995,GeoMobility%:Same House as 1995,GeoMobility:Moved Since 1995,GeoMobility:Moved Same County as 1995,GeoMobility%:Moved Same County as 1995,GeoMobility:Moved Different County Same State as 1995,GeoMobility%:Moved Different County Same State as 1995,GeoMobility:Moved Different State from 1995,GeoMobility%:Moved Different State from 1995,GeoMobility:Moved From Abroad Since 1995,GeoMobility%:Moved From Abroad Since 1995,ForeignBorn:Foreign Born,ForeignBorn%:Foreign Born,ForeignBorn:Native Born,ForeignBorn:Foreign Born Naturalized Citizen,ForeignBorn%:Foreign Born Population that are Naturalized Citizen,ForeignBorn:Foreign Born Not a Citizen,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen,Foreign Born Population,ForeignBorn:Europe,ForeignBorn:Asia,ForeignBorn:Africa,ForeignBorn:Oceania,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Canada & Other Northern American,Language:Population 5 and Older,Language:Speak Only English,Language%:Speak Only English,Language:Speak Spanish,Language:Spanish:Speak English Very Well,Language:Spanish:Speak English Well,Language:Spanish:Speak English Not Well,Language:Spanish:Speak English Not At All,Language:Speak Other Indo-European Language,Language:Other Indo-European:Speak English Very Well,Language:Other Indo-European:Speak English Well,Language:Other Indo-European:Speak English Not Well,Language:Other Indo-European:Speak English Not At All,Language:Speak Asian or Pacific Island Language,Language:Asian or Pacific Island:Speak English Very Well,Language:Asian or Pacific Island:Speak English Well,Language:Asian or Pacific Island:Speak English Not Well,Language:Asian or Pacific Island:Speak English Not At All,Language:Speak Other Language,Language:Other:Speak English Very Well,Language:Other:Speak English Well,Language:Other:Speak English Not Well,Language:Other:Speak English Not At All,Language%:Speak Language Besides English,Language%:Of Those that Speak Another Language and Speak English Not Well or At All,Year,Population,Male Under 5,Female Under 5,Male 5 to 9,Female 5 to 9,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters,Median Household Income,HHIncome:Total Households,"HHIncome:Less than 10,000","HHIncome%:Less than 10,000","HHIncome:10 to 14,999","HHIncome%:10 to 14,999","HHIncome:15 to 19,999","HHIncome%:15 to 19,999","HHIncome:20 to 24,999","HHIncome%:20 to 24,999","HHIncome:25 to 29,999","HHIncome%:25 to 29,999","HHIncome:30 to 34,999","HHIncome:%30 to 34,999","HHIncome:35 to 39,999","HHIncome%:35 to 39,999","HHIncome:40 to 44,999","HHIncome%:40 to 44,999","HHIncome:45 to 49,999","HHIncome%:45 to 49,999","HHIncome:50 to 59,999","HHIncome%:50 to 59,999","HHIncome:60 to 74,999","HHIncome%:60 to 74,999","HHIncome:75 to 99,999","HHIncome%:75 to 99,999","HHIncome:100 to 124,999","HHIncome%:100 to 124,999","HHIncome:125 to 149,999","HHIncome%:125 to 149,999","HHIncome:150 to 199,999","HHIncome%:150 to 199,999",HHIncome:200K or More,HHIncome%:200K or More,Ed:Population 25+ Educational Attainment,Ed:Less than High School,Ed%:Less than High School,Ed:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency,Ed%:High School Graduate or More,Ed:Some College,Ed%:Some College,Ed%:Some College or More,Ed:Associates,Ed%:Associates,Ed:Bachelors,Ed%:Bachelors,Ed%:Bachelors or More,Ed:Masters,Ed%:Masters,Ed%:Masters or More,Ed:Professional School Degree,Ed%:Professional School Degree,Ed%:Professional School Degree or More,Ed:Doctorate Degree,Ed%:Doctorate Degree,Ind:Employed Civilians 16+,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining",Ind:Construction,Ind%:Construction,Ind:Manufacturing,Ind%:Manufacturing,Ind:Wholesale Trade,Ind%:Wholesale Trade,Ind:Retail Trade,Ind%:Retail Trade,"Ind:Transportation and Warehousing, Utilities","Ind%:Transportation and Warehousing, Utilities",Ind:Information,Ind%:Information,"Ind:Finance, Insurance, Real Estate and Rental and Leasing","Ind%:Finance, Insurance, Real Estate and Rental and Leasing","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind:Educational, Health and Social Services","Ind%:Educational, Health and Social Services","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services",Ind:Other Services (Except Public Administration),Ind%:Other Services (Except Public Administration),Ind:Public Administration,Ind%:Public Administration,Employed Civilians 16+ Occupational,"Occ:Management, Business, and Financial Operations","Occ%:Management, Business, and Financial Operations",Occ:Professional and Related,Occ%:Professional and Related,Occ:Healthcare Support,Occ%:Healthcare Support,Occ:Protective Services,Occ%:Protective Services,Occ:Food Preparation and Serving Related,Occ%:Food Preparation and Serving Related,Occ:Building and Grounds Cleaning and Maintenance,Occ%:Building and Grounds Cleaning and Maintenance,Occ:Personal Care and Service,Occ%:Personal Care and Service,Occ:Sales and Related,Occ%:Sales and Related,Occ:Office and Administrative Support,Occ%:Office and Administrative Support,"Occ:Farming, Fishing, and Forestry","Occ%:Farming, Fishing, and Forestry","Occ:Construction, Extraction, and Maintenance","Occ%:Construction, Extraction, and Maintenance",Occ:Production,Occ%:Production,Occ:Transportation and Material Moving,Occ%:Transportation and Material Moving,Sector: Total Workers,Sector:Private,Sector%:Private,Sector:Public,Sector%:Public,Sector:Self-Employed,Sector%:Self-Employed,Sector:Non-Profit,Sector%:Non-Profit,Sector:Unpaid Family Workers,Sector%:Unpaid Family Workers,Employed,Unemployed,Unemployment Rate,Per Capita Income,Poverty:Population for Whom Poverty Status is Determined,Poverty: Population Below Poverty Level,Poverty%: Below Poverty Level,CB:Total Housing Units,CB:Cost Burdened Housholds,CB:Renter Occupied Units,CB:Cost Burdened Renters,CB%:Cost Burdened Renters,CB:Owner Occupied Units,CB:Cost Burdened Homeowners,CB%: Cost Burdened Homeowners,CB:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households,Median Home Value Owner Occupied with Mortgage,Median Home Value Owner Occupied without Mortgage,Median Gross Rent,Units:Total Series,"Units:1 Unit, Detached","Units%:1 Unit, Detached","Units:1 Unit, Attached","Units%:1 Unit, Attached",Units:2,Units%:2,Units:3 to 4,Units%:3 to 4,Units:5 to 9,Units%:5 to 9,Units:10 to 19,Units%:10 to 19,Units:20 to 49,Units%:20 to 49,Units:50 or More,Units%:50 or More,Units:Mobile Home,Units%:Mobile Home,"Units:Boat, RV, Van etc","Units%:Boat, RV, Van etc",Transpo:Workers Commuting,"Transpo:Car, Truck, or Van","Transpo%:Car, Truck, or Van",Transpo:Public Transportation,Transpo%:Public Transportation,Transpo:Bicycle,Transpo%:Bicycle,Transpo:Walk,Transpo%:Walk,Transpo:Worked From Home,Transpo%:Worked From Home,"Transpo:Taxi, Motorcycle, Other","Transpo%:Taxi, Motorcycle, Other",Vehicles:Households,Vehicles:None,Vehicles%:None,Vehicles:One,Vehicles%:One,Vehicles:Two,Vehicles%:Two,Vehicles:Three,Vehicles%:Three,Vehicles:Four,Vehicles%:Four,Vehicles:Five or More,Vehicles%:Five or More,Commute:Workers 16+ Not Working at Home,Commute:Less than 10 Minutes,Commute:10 to 14 Minutes,Commute:15 to 19 Minutes,Commute:20 to 24 Minutes,Commute:25 to 29 Minutes,Commute:30 to 34 Minutes,Commute:35 to 44 Minutes,Commute:45 to 59 Minutes,Commute:60 or More Minutes,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes","Commute:Car, Truck, Van Drove Alone:60 or More Minutes","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes","Commute:Car, Truck, Van Carpooled:60 or More Minutes",Vet:Population 18+,Vet:Veteran,Vet%:Veteran,Vet:Nonveteran,Vet%:Nonveteran,Vet:Veteran 18 to 64,Vet%:Veterans who are 18 to 64,Vet:Veteran 65 and Older,Vet%:Veterans who are 65 and Older,Vet:Nonveteran 18 to 64,Vet:Nonveteran 65 and Older,GeoMobility:Total,GeoMobility:Same House,GeoMobility%:Same House,GeoMobility:Moved Same County,GeoMobility%:Moved Same County,GeoMobility:Moved Different County Same State,GeoMobility%:Moved Different County Same State,GeoMobility:Moved Different State,GeoMobility%:Moved Different State,GeoMobility:Moved From Abroad,GeoMobility%:Moved From Abroad,ForeignBorn:Total Population,ForeignBorn:Native Born,ForeignBorn:Foreign Born,ForeignBorn%:Foreign Born,ForeignBorn:Foreign Born Naturalized Citizen,ForeignBorn%:Foreign Born Population that are Naturalized Citizen,ForeignBorn:Foreign Born Not a Citizen,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen,Foreign Born Population,ForeignBorn:Europe,ForeignBorn:Asia,ForeignBorn:Africa,ForeignBorn:Oceania,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Canada & Other Northern American,Lan

In [11]:
#make a list of all columns to run through for calculating percent change and real change over all time periods
columns = list(df.columns)
columns = columns[:]
element = []
for x in columns:
    element.append(x[0])

In [12]:
#loop through elements
for i in element:
    df[('{} % Change'.format(i), 'None','2000-2020')] = percentchange(df[('{}'.format(i),'2020','None')], df[('{}'.format(i),'2000','None')])
    df[('{} % Change'.format(i), 'None','2000-2010')] = percentchange(df[('{}'.format(i),'2010','None')], df[('{}'.format(i),'2000','None')])
    df[('{} % Change'.format(i), 'None','2010-2020')] = percentchange(df[('{}'.format(i),'2020','None')], df[('{}'.format(i),'2010','None')])
    df[('{} Change'.format(i), 'None','2000-2020')] = (df[('{}'.format(i),'2020','None')] - df[('{}'.format(i),'2000','None')])
    df[('{} Change'.format(i), 'None','2000-2010')] = (df[('{}'.format(i),'2010','None')] - df[('{}'.format(i),'2000','None')])
    df[('{} Change'.format(i), 'None','2010-2020')] = (df[('{}'.format(i),'2020','None')] - df[('{}'.format(i),'2010','None')])

C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} Change'.format(i), 'None','2000-2020')] = (df[('{}'.format(i),'2020','None')] - df[('{}'.format(i),'2000','None')])
C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} Change'.format(i), 'None','2000-2010')] = (df[('{}'.format(i),'2010','None')] - df[('{}'.format(i),'2000','None')])
C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} Change'.format(i), 'None','2010-2020')] = (df[('{}'.format(i),'2020','None')] - df[('{}'.format(i),'2010','None')])
C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} % Change'.format(i), 'None','2000-2020')] = percentchange(df[('{}'.format(i),'2020','None')], df[('{}'.format(i),'2000','None')])
C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} % Change'.format(i), 'None','2000-2010')] = percentchange(df[('{}'.format(i),'2010','None')], df[('{}'.format(i),'2000','None')])
C:\Users\jmccall\AppData\Local\Temp/ipykernel_18908/708731311.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[('{} % Change'.format(i), 'None','2010-2020')] = percentchange(df[('{}'.format(i),'2020','None')], df[('{}'.format(i),'2010','None')])

KeyError: 20185

In [13]:
#stack and rename to get tidy data for both year and time period - half of dataframe will be null depending on if it's a change or point in time metric
df = df.stack([1, 1])
df = df.reset_index(drop = False)
df = df.rename(columns = {'level_1':'Year', 'level_2':'Time Frame'})

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Columns: 972 entries, NAME to Year
dtypes: float64(969), object(3)
memory usage: 3.7+ MB

In [15]:
df.size

482112

In [16]:
df.head()

,NAME,Year,Time Frame,Age %:Under 5,Age %:Under 5 % Change,Age %:Under 5 Change,Age%:10 to 14,Age%:10 to 14 % Change,Age%:10 to 14 Change,Age%:15 to 17,Age%:15 to 17 % Change,Age%:15 to 17 Change,Age%:18 to 24,Age%:18 to 24 % Change,Age%:18 to 24 Change,Age%:18 to 54,Age%:18 to 54 % Change,Age%:18 to 54 Change,Age%:25 to 34,Age%:25 to 34 % Change,Age%:25 to 34 Change,Age%:35 to 44,Age%:35 to 44 % Change,Age%:35 to 44 Change,Age%:45 to 54,Age%:45 to 54 % Change,Age%:45 to 54 Change,Age%:5 to 9,Age%:5 to 9 % Change,Age%:5 to 9 Change,Age%:55 and Older,Age%:55 and Older % Change,Age%:55 and Older Change,Age%:55 to 64,Age%:55 to 64 % Change,Age%:55 to 64 Change,Age%:65 and Older,Age%:65 and Older % Change,Age%:65 and Older Change,Age%:65 to 74,Age%:65 to 74 % Change,Age%:65 to 74 Change,Age%:75 to 84,Age%:75 to 84 % Change,Age%:75 to 84 Change,Age%:85 and Older,Age%:85 and Older % Change,Age%:85 and Older Change,Age%:Under 18,Age%:Under 18 % Change,Age%:Under 18 Change,Age:10 to 14,Age:10 to 14 % Change,Age:10 to 14 Change,Age:15 to 17,Age:15 to 17 % Change,Age:15 to 17 Change,Age:18 to 24,Age:18 to 24 % Change,Age:18 to 24 Change,Age:18 to 54,Age:18 to 54 % Change,Age:18 to 54 Change,Age:25 to 34,Age:25 to 34 % Change,Age:25 to 34 Change,Age:35 to 44,Age:35 to 44 % Change,Age:35 to 44 Change,Age:45 to 54,Age:45 to 54 % Change,Age:45 to 54 Change,Age:5 to 9,Age:5 to 9 % Change,Age:5 to 9 Change,Age:55 and Older,Age:55 and Older % Change,Age:55 and Older Change,Age:55 to 64,Age:55 to 64 % Change,Age:55 to 64 Change,Age:65 and Older,Age:65 and Older % Change,Age:65 and Older Change,Age:65 to 74,Age:65 to 74 % Change,Age:65 to 74 Change,Age:75 to 84,Age:75 to 84 % Change,Age:75 to 84 Change,Age:85 and Older,Age:85 and Older % Change,Age:85 and Older Change,Age:Under 18,Age:Under 18 % Change,Age:Under 18 Change,Age:Under 5,Age:Under 5 % Change,Age:Under 5 Change,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % % Change,American Indian Alaska Native Alone % Change,American Indian Alaska Native Alone % Non-White Population,American Indian Alaska Native Alone % Non-White Population % Change,American Indian Alaska Native Alone % Non-White Population Change,American Indian Alaska Native Alone Change,Asian Alone,Asian Alone %,Asian Alone % % Change,Asian Alone % Change,Asian Alone % Non-White Population,Asian Alone % Non-White Population % Change,Asian Alone % Non-White Population Change,Asian Alone Change,Average Household Size,Average Household Size % Change,Average Household Size Change,Black or African American Alone,Black or African American Alone %,Black or African American Alone % % Change,Black or African American Alone % Change,Black or African American Alone % Non-White Population,Black or African American Alone % Non-White Population % Change,Black or African American Alone % Non-White Population Change,Black or African American Alone Change,CB%: Cost Burdened Homeowners,CB%: Cost Burdened Homeowners % Change,CB%: Cost Burdened Homeowners Change,CB%:Cost Burdened Renters,CB%:Cost Burdened Renters % Change,CB%:Cost Burdened Renters Change,CB%:Severe Cost Burdened Households,CB%:Severe Cost Burdened Households % Change,CB%:Severe Cost Burdened Households Change,CB:Cost Burdened Homeowners,CB:Cost Burdened Homeowners % Change,CB:Cost Burdened Homeowners Change,CB:Cost Burdened Housholds,CB:Cost Burdened Housholds % Change,CB:Cost Burdened Housholds Change,CB:Cost Burdened Renters,CB:Cost Burdened Renters % Change,CB:Cost Burdened Renters Change,CB:Owner Occupied Units,CB:Owner Occupied Units % Change,CB:Owner Occupied Units Change,CB:Renter Occupied Units,CB:Renter Occupied Units % Change,CB:Renter Occupied Units Change,CB:Severe Cost Burdened Households,CB:Severe Cost Burdened Households % Change,CB:Severe Cost Burdened Households Change,CB:Total Housing Units,CB:Total Housing Units % Change,CB:Total Housing Units Change,Commute:10 to 14 Minutes,Commute:15 to 19 Minutes,Commute:20 to 24 Minutes,Commute:25 to 29 Minutes,Commute:30 to 34 Minutes,Commute:35 to 44 Minutes,Commute:45 to 59 Minutes,Commute:60 or More Minutes,"Commute:Car, Truck, Van Carpooled:10 to 14 Minutes","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes","Commute:Car, Truck, Van Carpooled:60 or More Minutes","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes","Commute:Car, Truck, Van Drove Alone:60 or More Minutes","Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes",Commute:Less than 10 Minutes,"Commute:Taxi, Motorcycle, Bicycle, Other:10 to 14 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:15 to 19 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:20 to 24 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:25 to 29 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:30 to 34 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:35 to 44 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:45 to 59 Minutes","Commute:Taxi, Motorcycle, Bicycle, Other:60 or More Minutes",Commute:Walked:10 to 14 Minutes,Commute:Walked:15 to 19 Minutes,Commute:Walked:20 to 24 Minutes,Commute:Walked:25 to 29 Minutes,Commute:Walked:30 to 34 Minutes,Commute:Walked:35 to 44 Minutes,Commute:Walked:45 to 59 Minutes,Commute:Walked:60 or More Minutes,Commute:Walked:Less than 10 Minutes,Commute:Workers 16+ Not Working at Home,Disability Tally,Disability%:Ambulatory Difficulty,Disability%:Cognitive Difficulty,Disability%:Hearing Difficulty,Disability%:Independent Living Difficulty,Disability%:Population with One Disability,Disability%:Population with Two or More Disabilities,Disability%:Self-Care Difficulty,Disability%:Vision Difficulty,Disability%:With Disability,Disability:Ambulatory Difficulty,Disability:Cognitive Difficulty,Disability:Hearing Difficulty,Disability:Independent Living Difficulty,Disability:Population with One Disability,Disability:Population with Two or More Disabilities,Disability:Self-Care Difficulty,Disability:Total Disabilities,Disability:Total Population,Disability:Vision Difficulty,Disability:With Disability,Ed%:Associates,Ed%:Associates % Change,Ed%:Associates Change,Ed%:Bachelors,Ed%:Bachelors % Change,Ed%:Bachelors Change,Ed%:Bachelors or More,Ed%:Bachelors or More % Change,Ed%:Bachelors or More Change,Ed%:Doctorate Degree,Ed%:Doctorate Degree % Change,Ed%:Doctorate Degree Change,Ed%:High School Graduate or Equivalency,Ed%:High School Graduate or Equivalency % Change,Ed%:High School Graduate or Equivalency Change,Ed%:High School Graduate or More,Ed%:High School Graduate or More % Change,Ed%:High School Graduate or More Change,Ed%:Less than High School,Ed%:Less than High School % Change,Ed%:Less than High School Change,Ed%:Masters,Ed%:Masters % Change,Ed%:Masters Change,Ed%:Masters or More,Ed%:Masters or More % Change,Ed%:Masters or More Change,Ed%:Professional School Degree,Ed%:Professional School Degree % Change,Ed%:Professional School Degree Change,Ed%:Professional School Degree or More,Ed%:Professional School Degree or More % Change,Ed%:Professional School Degree or More Change,Ed%:Some College,Ed%:Some College % Change,Ed%:Some College Change,Ed%:Some College or More,Ed%:Some College or More % Change,Ed%:Some College or More Change,Ed:Associates,Ed:Associates % Change,Ed:Associates Change,Ed:Bachelors,Ed:Bachelors % Change,Ed:Bachelors Change,Ed:Doctorate Degree,Ed:Doctorate Degree % Change,Ed:Doctorate Degree Change,Ed:High School Graduate or Equivalency,Ed:High School Graduate or Equivalency % Change,Ed:High School Graduate or Equivalency Change,Ed:Less than High School,Ed:Less than High School % Change,Ed:Less than High School Change,Ed:Masters,Ed:Masters % Change,Ed:Masters Change,Ed:Population 25+ Educational Attainment,Ed:Population 25+ Educational Attainment % Change,Ed:Population 25+ Educational Attainment Change,Ed:Professional School Degree,Ed:Professional School Degree % Change,Ed:Professional School Degree Change,Ed:Some College,Ed:Some College % Change,Ed:Some College Change,Employed,Employed % Change,Employed Change,Employed Civilians 16+ Occupational,Employed Civilians 16+ Occupational % Change,Employed Civilians 16+ Occupational Change,Family Households,Family Households % Change,Family Households Change,Family Households: Married Couple Family,Family Households: Married Couple Family % Change,Family Households: Married Couple Family Change,Family Households: Not Married Couple Family,Family Households: Not Married Couple Family % Change,Family Households: Not Married Couple Family Change,Family Households: Not Married Couple: Female no Spouse,Family Households: Not Married Couple: Female no Spouse % Change,Family Households: Not Married Couple: Female no Spouse Change,Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Male no Spouse % Change,Family Households: Not Married Couple: Male no Spouse Change,Female 10 to 14,Female 10 to 14 % Change,Female 10 to 14 Change,Female 15 to 17,Female 15 to 17 % Change,Female 15 to 17 Change,Female 15 to 24,Female 15 to 24 % Change,Female 15 to 24 Change,Female 18 to 24,Female 18 to 24 % Change,Female 18 to 24 Change,Female 25 to 34,Female 25 to 34 % Change,Female 25 to 34 Change,Female 35 to 44,Female 35 to 44 % Change,Female 35 to 44 Change,Female 45 to 54,Female 45 to 54 % Change,Female 45 to 54 Change,Female 5 to 14,Female 5 to 14 % Change,Female 5 to 14 Change,Female 5 to 9,Female 5 to 9 % Change,Female 5 to 9 Change,Female 55 to 64,Female 55 to 64 % Change,Female 55 to 64 Change,Female 65 to 74,Female 65 to 74 % Change,Female 65 to 74 Change,Female 75 to 84,Female 75 to 84 % Change,Female 75 to 84 Change,Female 85 and Older,Female 85 and Older % Change,Female 85 and Older Change,Female Under 5,Female Under 5 % Change,Female Under 5 Change,Foreign Born Population,ForeignBorn%:Foreign Born,ForeignBorn%:Foreign Born Population that are Naturalized Citizen,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen,ForeignBorn:Africa,ForeignBorn:Asia,ForeignBorn:Canada & Other Northern American,"ForeignBorn:Central & South America, Caribbean",ForeignBorn:Europe,ForeignBorn:Foreign Born,ForeignBorn:Foreign Born Naturalized Citizen,ForeignBorn:Foreign Born Not a Citizen,ForeignBorn:Native Born,ForeignBorn:Oceania,ForeignBorn:Total Population,GeoMobility%:Moved Different County Same State,GeoMobility%:Moved Different County Same State as 1995,GeoMobility%:Moved Different State,GeoMobility%:Moved Different State from 1995,GeoMobility%:Moved From Abroad,GeoMobility%:Moved From Abroad Since 1995,GeoMobility%:Moved Same County,GeoMobility%:Moved Same County as 1995,GeoMobility%:Same House,GeoMobility%:Same House as 1995,GeoMobility:Moved Different County Same State,GeoMobility:Moved Different County Same State as 1995,GeoMobility:Moved Different State,GeoMobility:Moved Different State from 1995,GeoMobility:Moved From Abroad,GeoMobility:Moved From Abroad Since 1995,GeoMobility:Moved Same County,GeoMobility:Moved Same County as 1995,GeoMobility:Moved Since 1995,GeoMobility:Same House,GeoMobility:Same House as 1995,GeoMobility:Total,"HHIncome%:10 to 14,999","HHIncome%:10 to 14,999 % Change","HHIncome%:10 to 14,999 Change","HHIncome%:100 to 124,999","HHIncome%:100 to 124,999 % Change","HHIncome%:100 to 124,999 Change","HHIncome%:125 to 149,999","HHIncome%:125 to 149,999 % Change","HHIncome%:125 to 149,999 Change","HHIncome%:15 to 19,999","HHIncome%:15 to 19,999 % Change","HHIncome%:15 to 19,999 Change","HHIncome%:150 to 199,999","HHIncome%:150 to 199,999 % Change","HHIncome%:150 to 199,999 Change","HHIncome%:20 to 24,999","HHIncome%:20 to 24,999 % Change","HHIncome%:20 to 24,999 Change",HHIncome%:200K or More,HHIncome%:200K or More % Change,HHIncome%:200K or More Change,"HHIncome%:25 to 29,999","HHIncome%:25 to 29,999 % Change","HHIncome%:25 to 29,999 Change","HHIncome%:35 to 39,999","HHIncome%:35 to 39,999 % Change","HHIncome%:35 to 39,999 Change","HHIncome%:40 to 44,999","HHIncome%:40 to 44,999 % Change","HHIncome%:40 to 44,999 Change","HHIncome%:45 to 49,999","HHIncome%:45 to 49,999 % Change","HHIncome%:45 to 49,999 Change","HHIncome%:50 to 59,999","HHIncome%:50 to 59,999 % Change","HHIncome%:50 to 59,999 Change","HHIncome%:60 to 74,999","HHIncome%:60 to 74,999 % Change","HHIncome%:60 to 74,999 Change","HHIncome%:75 to 99,999","HHIncome%:75 to 99,999 % Change","HHIncome%:75 to 99,999 Change","HHIncome%:Less than 10,000","HHIncome%:Less than 10,000 % Change","HHIncome%:Less than 10,000 Change","HHIncome:%30 to 34,999","HHIncome:%30 to 34,999 % Change","HHIncome:%30 to 34,999 Change","HHIncome:10 to 14,999","HHIncome:10 to 14,999 % Change","HHIncome:10 to 14,999 Change","HHIncome:100 to 124,999","HHIncome:100 to 124,999 % Change","HHIncome:100 to 124,999 Change","HHIncome:125 to 149,999","HHIncome:125 to 149,999 % Change","HHIncome:125 to 149,999 Change","HHIncome:15 to 19,999","HHIncome:15 to 19,999 % Change","HHIncome:15 to 19,999 Change","HHIncome:150 to 199,999","HHIncome:150 to 199,999 % Change","HHIncome:150 to 199,999 Change","HHIncome:20 to 24,999","HHIncome:20 to 24,999 % Change","HHIncome:20 to 24,999 Change",HHIncome:200K or More,HHIncome:200K or More % Change,HHIncome:200K or More Change,"HHIncome:25 to 29,999","HHIncome:25 to 29,999 % Change","HHIncome:25 to 29,999 Change","HHIncome:30 to 34,999","HHIncome:30 to 34,999 % Change","HHIncome:30 to 34,999 Change","HHIncome:35 to 39,999","HHIncome:35 to 39,999 % Change","HHIncome:35 to 39,999 Change","HHIncome:40 to 44,999","HHIncome:40 to 44,999 % Change","HHIncome:40 to 44,999 Change","HHIncome:45 to 49,999","HHIncome:45 to 49,999 % Change","HHIncome:45 to 49,999 Change","HHIncome:50 to 59,999","HHIncome:50 to 59,999 % Change","HHIncome:50 to 59,999 Change","HHIncome:60 to 74,999","HHIncome:60 to 74,999 % Change","HHIncome:60 to 74,999 Change","HHIncome:75 to 99,999","HHIncome:75 to 99,999 % Change","HHIncome:75 to 99,999 Change","HHIncome:Less than 10,000","HHIncome:Less than 10,000 % Change","HHIncome:Less than 10,000 Change",HHIncome:Total Households,HHIncome:Total Households % Change,HHIncome:Total Households Change,HealthCoverage%: None,HealthCoverage%: With Healthcare Coverage,HealthCoverage%: With Private Healthcare Coverage,HealthCoverage%: With Public Healthcare Coverage,HealthCoverage: With Healthcare Coverage,HealthCoverage: With Private Healthcare Coverage,HealthCoverage: With Public Healthcare Coverage,HealthCoverage:None,HealthCoverage:Total Series,Hispanic or Latino,Hispanic or Latino %,Hispanic or Latino % % Change,Hispanic or Latino % Change,Hispanic or Latino Change,"Household Type%: Family, Married Couple Households","Household Type%: Family, Married Couple Households % Change","Household Type%: Family, Married Couple Households Change","Household Type%: Family, Not Married Couple Households","Household Type%: Family, Not Married Couple Households % Change","Household Type%: Family, Not Married Couple Households Change","Household Type%: Nonfamily, Householder Alone","Household Type%: Nonfamily, Householder Alone % Change","Household Type%: Nonfamily, Householder Alone Change","Household Type%: Nonfamily, Householder Not Alone","Household Type%: Nonfamily, Householder Not Alone % Change","Household Type%: Nonfamily, Householder Not Alone Change","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining % Change","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining Change","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services % Change","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services Change",Ind%:Construction,Ind%:Construction % Change,Ind%:Construction Change,"Ind%:Educational, Health and Social Services","Ind%:Educational, Health and Social Services % Change","Ind%:Educational, Health and Social Services Change","Ind%:Finance, Insurance, Real Estate and Rental and Leasing","Ind%:Finance, Insurance, Real Estate and Rental and Leasing % Change","Ind%:Finance, Insurance, Real Estate and Rental and Leasing Change",Ind%:Information,Ind%:Information % Change,Ind%:Information Change,Ind%:Manufacturing,Ind%:Manufacturing % Change,Ind%:Manufacturing Change,Ind%:Other Services (Except Public Administration),Ind%:Other Services (Except Public Administration) % Change,Ind%:Other Services (Except Public Administration) Change,"Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services % Change","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services Change",Ind%:Public Administration,Ind%:Public Administration % Change,Ind%:Public Administration Change,Ind%:Retail Trade,Ind%:Retail Trade % Change,Ind%:Retail Trade Change,"Ind%:Transportation and Warehousing, Utilities","Ind%:Transportation and Warehousing, Utilities % Change","Ind%:Transportation and Warehousing, Utilities Change",Ind%:Wholesale Trade,Ind%:Wholesale Trade % Change,Ind%:Wholesale Trade Change,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining","Ind:Agriculture, Forestry, Fishing and Hunting, and Mining % Change","Ind:Agriculture, Forestry, Fishing and Hunting, and Mining Change","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services % Change","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services Change",Ind:Construction,Ind:Construction % Change,Ind:Construction Change,"Ind:Educational, Health and Social Services","Ind:Educational, Health and Social Services % Change","Ind:Educational, Health and Social Services Change",Ind:Employed Civilians 16+,Ind:Employed Civilians 16+ % Change,Ind:Employed Civilians 16+ Change,"Ind:Finance, Insurance, Real Estate and Rental and Leasing","Ind:Finance, Insurance, Real Estate and Rental and Leasing % Change","Ind:Finance, Insurance, Real Estate and Rental and Leasing Change",Ind:Information,Ind:Information % Change,Ind:Information Change,Ind:Manufacturing,Ind:Manufacturing % Change,Ind:Manufacturing Change,Ind:Other Services (Except Public Administration),Ind:Other Services (Except Public Administration) % Change,Ind:Other Services (Except Public Administration) Change,"Ind:Professional, Scientific, Management, Administrative, and Waste Management Services","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services % Change","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services Change",Ind:Public Administration,Ind:Public Administration % Change,Ind:Public Administration Change,Ind:Retail Trade,Ind:Retail Trade % Change,Ind:Retail Trade Change,"Ind:Transportation and Warehousing, Utilities","Ind:Transportation and Warehousing, Utilities % Change","Ind:Transportation and Warehousing, Utilities Change",Ind:Wholesale Trade,Ind:Wholesale Trade % Change,Ind:Wholesale Trade Change,Language%:Of Those that Speak Another Language and Speak English Not Well or At All,Language%:Speak Language Besides English,Language%:Speak Only English,Language:Asian or Pacific Island:Speak English Not At All,Language:Asian or Pacific Island:Speak English Not Well,Language:Asian or Pacific Island:S

# Export Different Geographies

In [17]:
# GALLATIN 
gallatin = df.loc[(df['NAME'] == 'United States')|(df['NAME'] == 'Tennessee')|(df['NAME'] == 'GNRC Region')|
                  (df['NAME'] == 'Sumner County, Tennessee')|(df['NAME'] == 'Gallatin city, Tennessee')].reset_index(drop = True)
gallatin = gallatin.replace('Sumner County, Tennessee', 'Sumner County').replace('Gallatin city, Tennessee', 'Gallatin').replace('United States', 'US')
gallatin.to_csv('../../data/Geography Specific Output/GallatinFigures.csv', index = False)