###### Imports and Settings

In [126]:
import pandas as pd
import geopandas as gpd
import numpy as np
import requests
import io
import pickle
import matplotlib.pyplot as plt
from collections import deque
from functools import reduce
%matplotlib inline
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

In [127]:
data = pd.read_csv('../data/ACS20205YR.csv')

# Page by Page of CC Databook to start:

## Population + Projections Summary:

In [128]:
data['Population'] = data['agebysex_total_series']

In [129]:
data = data.drop(columns = 'agebysex_total_series')

### Population Density  
Bring in geofiles

## Health Insurance Coverage  
+ Total Series  
+ Total No Health Insurance Coverage  
+ % Total with No Health Insurance Coverage  
+ Total with Health Insurance Coverage 
+ % Total with Health Insurance Coverage
+ Total with Health Insurance Coverage: Public Health Coverage  
+ % Covered Population: Public Health Coverage  
+ Total with Health Insurance Coverage: Private Health Coverage  
+ % Covered Population: Private Health Coverage

In [130]:
#total series
data['Total Health Coverage Series'] = data['healthcoverage_total_healthcare_series']
data = data.drop(columns = 'healthcoverage_total_healthcare_series')

In [131]:
#total no health insurance
colsnohealthcare = ['healthcoverage_mu6_wo','healthcoverage_m6to18_wo','healthcoverage_m19to25_wo','healthcoverage_m26to34_wo','healthcoverage_m35to44_wo',
        'healthcoverage_m45to54_wo','healthcoverage_m55to64_wo','healthcoverage_m65to74_wo','healthcoverage_m75+_wo','healthcoverage_fu6_wo',
        'healthcoverage_f6to18_wo','healthcoverage_f19to25_wo','healthcoverage_f26to34_wo','healthcoverage_f35to44_wo','healthcoverage_f45to54_wo',
        'healthcoverage_f55to64_wo','healthcoverage_f65to74_wo','healthcoverage_f75+_wo']
nohealthcare = [data['healthcoverage_mu6_wo'],data['healthcoverage_m6to18_wo'],data['healthcoverage_m19to25_wo'],data['healthcoverage_m26to34_wo'],
                data['healthcoverage_m35to44_wo'],data['healthcoverage_m45to54_wo'],data['healthcoverage_m55to64_wo'],data['healthcoverage_m65to74_wo'],
                data['healthcoverage_m75+_wo'],data['healthcoverage_fu6_wo'],data['healthcoverage_f6to18_wo'],data['healthcoverage_f19to25_wo'],
                data['healthcoverage_f26to34_wo'],data['healthcoverage_f35to44_wo'],data['healthcoverage_f45to54_wo'],data['healthcoverage_f55to64_wo'],
                data['healthcoverage_f65to74_wo'],data['healthcoverage_f75+_wo']]
data['Total No Health Insurance Coverage'] = sum(nohealthcare)
data = data.drop(columns = colsnohealthcare)

In [132]:
#% of total with No Health Insurance Coverage
data['Population without Health Insurance %'] = data['Total No Health Insurance Coverage']/data['Total Health Coverage Series']

In [133]:
#total with health insurance
colshealthcare = ['healthcoverage_mu6_w','healthcoverage_m6to18_w','healthcoverage_m19to25_w','healthcoverage_m26to34_w','healthcoverage_m35to44_w',
        'healthcoverage_m45to54_w','healthcoverage_m55to64_w','healthcoverage_m65to74_w','healthcoverage_m75+_w','healthcoverage_fu6_w',
        'healthcoverage_f6to18_w','healthcoverage_f19to25_w','healthcoverage_f26to34_w','healthcoverage_f35to44_w','healthcoverage_f45to54_w',
        'healthcoverage_f55to64_w','healthcoverage_f65to74_w','healthcoverage_f75+_w']
healthcare = [data['healthcoverage_mu6_w'],data['healthcoverage_m6to18_w'],data['healthcoverage_m19to25_w'],data['healthcoverage_m26to34_w'],
                data['healthcoverage_m35to44_w'],data['healthcoverage_m45to54_w'],data['healthcoverage_m55to64_w'],data['healthcoverage_m65to74_w'],
                data['healthcoverage_m75+_w'],data['healthcoverage_fu6_w'],data['healthcoverage_f6to18_w'],data['healthcoverage_f19to25_w'],
                data['healthcoverage_f26to34_w'],data['healthcoverage_f35to44_w'],data['healthcoverage_f45to54_w'],data['healthcoverage_f55to64_w'],
                data['healthcoverage_f65to74_w'],data['healthcoverage_f75+_w']]
data['Total With Health Insurance Coverage'] = sum(healthcare)
data = data.drop(columns = colshealthcare)

In [134]:
#% of total with Health Insurance Coverage
data['Population with Health Insurance %'] = data['Total With Health Insurance Coverage']/data['Total Health Coverage Series']

In [135]:
# Total with Health Insurance: Public Coverage
colspublic = ['healthcoverage_mu6_wpublic','healthcoverage_m6to18_wpublic','healthcoverage_m19to25_wpublic','healthcoverage_m26to34_wpublic',
              'healthcoverage_m35to44_wpublic','healthcoverage_m45to54_wpublic','healthcoverage_m55to64_wpublic','healthcoverage_m65to74_wpublic',
              'healthcoverage_m75+_wpublic','healthcoverage_fu6_wpublic','healthcoverage_f6to18_wpublic','healthcoverage_f19to25_wpublic',
              'healthcoverage_f26to34_wpublic','healthcoverage_f35to44_wpublic','healthcoverage_f45to54_wpublic','healthcoverage_f55to64_wpublic',
              'healthcoverage_f65to74_wpublic','healthcoverage_f75+_wpublic']
public = [data['healthcoverage_mu6_wpublic'],data['healthcoverage_m6to18_wpublic'],data['healthcoverage_m19to25_wpublic'],data['healthcoverage_m26to34_wpublic'],
          data['healthcoverage_m35to44_wpublic'],data['healthcoverage_m45to54_wpublic'],data['healthcoverage_m55to64_wpublic'],
          data['healthcoverage_m65to74_wpublic'],data['healthcoverage_m75+_wpublic'],data['healthcoverage_fu6_wpublic'],
          data['healthcoverage_f6to18_wpublic'],data['healthcoverage_f19to25_wpublic'],data['healthcoverage_f26to34_wpublic'],
          data['healthcoverage_f35to44_wpublic'],data['healthcoverage_f45to54_wpublic'],data['healthcoverage_f55to64_wpublic'],
          data['healthcoverage_f65to74_wpublic'],data['healthcoverage_f75+_wpublic']]
data['Total With Health Insurance, Public'] = sum(public)
data = data.drop(columns = colspublic)

In [136]:
# % of covered with public
data['Covered, % with Public Health Insurance'] = data['Total With Health Insurance, Public']/data['Total With Health Insurance Coverage']

In [137]:
# Total with Health Insurance: Private Coverage
colsprivate = ['healthcoverage_mu6_wprivate','healthcoverage_m6to18_wprivate','healthcoverage_m19to25_wprivate','healthcoverage_m26to34_wprivate',
              'healthcoverage_m35to44_wprivate','healthcoverage_m45to54_wprivate','healthcoverage_m55to64_wprivate','healthcoverage_m65to74_wprivate',
              'healthcoverage_m75+_wprivate','healthcoverage_fu6_wprivate','healthcoverage_f6to18_wprivate','healthcoverage_f19to25_wprivate',
              'healthcoverage_f26to34_wprivate','healthcoverage_f35to44_wprivate','healthcoverage_f45to54_wprivate','healthcoverage_f55to64_wprivate',
              'healthcoverage_f65to74_wprivate','healthcoverage_f75+_wprivate']
private = [data['healthcoverage_mu6_wprivate'],data['healthcoverage_m6to18_wprivate'],data['healthcoverage_m19to25_wprivate'],data['healthcoverage_m26to34_wprivate'],
          data['healthcoverage_m35to44_wprivate'],data['healthcoverage_m45to54_wprivate'],data['healthcoverage_m55to64_wprivate'],
          data['healthcoverage_m65to74_wprivate'],data['healthcoverage_m75+_wprivate'],data['healthcoverage_fu6_wprivate'],
          data['healthcoverage_f6to18_wprivate'],data['healthcoverage_f19to25_wprivate'],data['healthcoverage_f26to34_wprivate'],
          data['healthcoverage_f35to44_wprivate'],data['healthcoverage_f45to54_wprivate'],data['healthcoverage_f55to64_wprivate'],
          data['healthcoverage_f65to74_wprivate'],data['healthcoverage_f75+_wprivate']]
data['Total With Health Insurance, Private'] = sum(private)
data = data.drop(columns = colsprivate)

In [138]:
# % of covered with private
data['Covered, % with Private Health Insurance'] = data['Total With Health Insurance, Private']/data['Total With Health Insurance Coverage']

## Age Sex Race Summary

### Race/Ethnicity #s   
+ White Alone  
+ Black/African American Alone  
+ American Indian Alaska Native Alone  
+ Asian Alone  
+ Native Hawaiian/Other Pacific Islander Alone  
+ Some Other Race Alone  
+ Two or More Races  
+ Hispanic/Latino  
+ White, Not Hispanic/Latino  
+ Total Minority (non-white, non Hispanic/Latino)

In [139]:
#White Alone
data['White Alone'] = data['raceeth_white_alone']
data['White Alone %'] = data['White Alone']/data['Population']
#Black or African American Alone 
data['Black or African American Alone'] = data['raceeth_blackafricanamerican_alone']
data['Black or African American Alone %'] = data['Black or African American Alone']/data['Population']
#American Indian and Alaska Native Alone
data['American Indian Alaska Native Alone'] = data['raceeth_americanindianalaskanative_alone']
data['American Indian Alaska Native Alone %'] = data['American Indian Alaska Native Alone']/data['Population']
#Asian Alone
data['Asian Alone'] = data['raceeth_asian_alone']
data['Asian Alone %'] = data['Asian Alone']/data['Population']
#Native Hawaiian Other Pacific Islander Alone
data['Native Hawaiian Other Pacific Islander Alone'] = data['raceeth_nativehawaiianotherpacificislander_alone']
data['Native Hawaiian Other Pacific Islander Alone %'] = data['Native Hawaiian Other Pacific Islander Alone']/data['Population']
#Some Other Race Alone
data['Some Other Race Alone'] = data['raceeth_someotherrace_alone']
data['Some Other Race Alone %'] = data['Some Other Race Alone']/data['Population']
#Two or More Races
data['Two or More Races'] = data['raceeth_twoormoreraces_alone']
data['Two or More Races %'] = data['Two or More Races']/data['Population']
#Hispanic or Latino
data['Hispanic or Latino'] = data['raceeth_hispanicorlatino']
data['Hispanic or Latino %'] = data['Hispanic or Latino']/data['Population']
#Data Minority
data['Minority'] = data['Population'] - data['raceeth_whitealone_nothispanicorlatino']
data['Minority %'] = data['Minority']/data['Population']
cols = ['raceeth_white_alone','raceeth_blackafricanamerican_alone','raceeth_americanindianalaskanative_alone','raceeth_asian_alone',
        'raceeth_nativehawaiianotherpacificislander_alone','raceeth_someotherrace_alone','raceeth_twoormoreraces_alone','raceeth_hispanicorlatino',
        'raceeth_whitealone_nothispanicorlatino']
data = data.drop(columns = cols)

### Age Brackets
+ M and F U5, 5 to 9, 10 to 14, 15 to 17, 18 to 24, 25 to 34, 35 to 44, 45 to 54, 55 to 64, 65 to 74, 75 to 84, 85+  
+ age brackets: under 18, 18 to 54, 55+  
+ 65+

In [140]:
#small groups m and f
data['Male Under 5'] = data['age_m_u5']
data['Female Under 5'] = data['age_f_u5']
data['Male 5 to 9'] = data['age_m_5to9']
data['Female 5 to 9'] = data['age_f_5to9']
data['Male 10 to 14'] = data['age_m_10to14']
data['Female 10 to 14'] = data['age_f_10to14']
data['Male 15 to 17'] = data['age_m_15to17']
data['Female 15 to 17'] = data['age_f_15to17']
data['Male 18 to 24'] = data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 18 to 24'] = data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 25 to 34'] = data['age_m_25to29']+data['age_m_30to34']
data['Female 25 to 34'] = data['age_f_25to29']+data['age_f_30to34']
data['Male 35 to 44'] = data['age_m_35to39']+data['age_m_40to44']
data['Female 35 to 44'] = data['age_f_35to39']+data['age_f_40to44']
data['Male 45 to 54'] = data['age_m_45to49']+data['age_m_50to54']
data['Female 45 to 54'] = data['age_f_45to49']+data['age_f_50to54']
data['Male 55 to 64'] = data['age_m_55to59']+data['age_m_60to61']+data['age_m_62to64']
data['Female 55 to 64'] = data['age_f_55to59']+data['age_f_60to61']+data['age_f_62to64']
data['Male 65 to 74'] = data['age_m_65to66']+data['age_m_67to69']+data['age_m_70to74']
data['Female 65 to 74'] = data['age_f_65to66']+data['age_f_67to69']+data['age_f_70to74']
data['Male 75 to 84'] = data['age_m_75to79']+data['age_m_80to84']
data['Female 75 to 84'] = data['age_f_75to79']+data['age_f_80to84']
data['Male 85 and Older'] = data['age_m_85+']
data['Female 85 and Older'] = data['age_f_85+']

In [141]:
#age brackets
u18list = [data['Male Under 5'],data['Female Under 5'],data['Male 5 to 9'],data['Female 5 to 9'],data['Male 10 to 14'],data['Female 10 to 14'],data['Male 15 to 17'],
           data['Female 15 to 17']]
data['Under 18'] = sum(u18list)
eighteento54list = [data['Male 18 to 24'],data['Female 18 to 24'],data['Male 25 to 34'],data['Female 25 to 34'],data['Male 35 to 44'],data['Female 35 to 44'],
              data['Male 45 to 54'],data['Female 45 to 54']]
data['18 to 24'] = sum(eighteento54list)
fifty5pluslist = [data['Male 55 to 64'],data['Female 55 to 64'],data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],
                  data['Male 85 and Older'],data['Female 85 and Older']]
data['55 and Older'] = sum(fifty5pluslist)

In [142]:
#65+
sixty5pluslist = [data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],data['Male 85 and Older'],data['Female 85 and Older']]
data['65 and Older'] = sum(sixty5pluslist)

In [143]:
cols = ['age_m_u5','age_m_5to9','age_m_10to14','age_m_15to17','age_m_18to19','age_m_20','age_m_21','age_m_22to24','age_m_25to29','age_m_30to34','age_m_35to39',
        'age_m_40to44','age_m_45to49','age_m_50to54','age_m_55to59','age_m_60to61','age_m_62to64','age_m_65to66','age_m_67to69','age_m_70to74','age_m_75to79',
        'age_m_80to84','age_m_85+','age_f_u5','age_f_5to9','age_f_10to14','age_f_15to17','age_f_18to19','age_f_20','age_f_21','age_f_22to24','age_f_25to29',
        'age_f_30to34','age_f_35to39','age_f_40to44','age_f_45to49','age_f_50to54','age_f_55to59','age_f_60to61','age_f_62to64','age_f_65to66','age_f_67to69',
        'age_f_70to74','age_f_75to79','age_f_80to84','age_f_85+']
data = data.drop(columns = cols)

In [144]:
data.head()

,NAME,age_total_male,age_total_female,hhsize_avg,healthcoverage_total_mallhealthcare,healthcoverage_mu6_all,healthcoverage_m6to18_all,healthcoverage_m19to25_all,healthcoverage_m26to34_all,healthcoverage_m35to44_all,healthcoverage_m45to54_all,healthcoverage_m55to64_all,healthcoverage_m65to74_all,healthcoverage_m75+_all,healthcoverage_total_fallhealthcare,healthcoverage_fu6_all,healthcoverage_f6to18_all,healthcoverage_f19to25_all,healthcoverage_f26to34_all,healthcoverage_f35to44_all,healthcoverage_f45to54_all,healthcoverage_f55to64_all,healthcoverage_f65to74_all,healthcoverage_f75+_all,healthcoverage_total_privatehealthcare_series,healthcoverage_total_mprivate,healthcoverage_mu6_privateall,healthcoverage_mu6_woprivate,healthcoverage_m6to18_privateall,healthcoverage_m6to18_woprivate,healthcoverage_m19to25_privateall,healthcoverage_m19to25_woprivate,healthcoverage_m26to34_privateall,healthcoverage_m26to34_woprivate,healthcoverage_m35to44_privateall,healthcoverage_m35to44_woprivate,healthcoverage_m45to54_privateall,healthcoverage_m45to54_woprivate,healthcoverage_m55to64_privateall,healthcoverage_m55to64_woprivate,healthcoverage_m65to74_privateall,healthcoverage_m65to74_woprivate,healthcoverage_m75+_privateall,healthcoverage_m75+_woprivate,healthcoverage_total_fprivate,healthcoverage_fu6_privateall,healthcoverage_fu6_woprivate,healthcoverage_f6to18_privateall,healthcoverage_f6to18_woprivate,healthcoverage_f19to25_privateall,healthcoverage_f19to25_woprivate,healthcoverage_f26to34_privateall,healthcoverage_f26to34_woprivate,healthcoverage_f35to44_privateall,healthcoverage_f35to44_woprivate,healthcoverage_f45to54_privateall,healthcoverage_f45to54_woprivate,healthcoverage_f55to64_privateall,healthcoverage_f55to64_woprivate,healthcoverage_f65to74_privateall,healthcoverage_f65to74_woprivate,healthcoverage_f75+_privateall,healthcoverage_f75+_woprivate,healthcoverage_total_publichealthcare_series,healthcoverage_total_mpublic,healthcoverage_mu6_publicall,healthcoverage_mu6_wopublic,healthcoverage_m6to18_publicall,healthcoverage_m6to18_wopublic,healthcoverage_m19to25_publicall,healthcoverage_m19to25_wopublic,healthcoverage_m26to34_publicall,healthcoverage_m26to34_wopublic,healthcoverage_m35to44_publicall,healthcoverage_m35to44_wopublic,healthcoverage_m45to54_publicall,healthcoverage_m45to54_wopublic,healthcoverage_m55to64_publicall,healthcoverage_m55to64_wopublic,healthcoverage_m65to74_publicall,healthcoverage_m65to74_wopublic,healthcoverage_m75+_publicall,healthcoverage_m75+_wopublic,healthcoverage_total_fpublic,healthcoverage_fu6_publicall,healthcoverage_fu6_wopublic,healthcoverage_f6to18_publicall,healthcoverage_f6to18_wopublic,healthcoverage_f19to25_publicall,healthcoverage_f19to25_wopublic,healthcoverage_f26to34_publicall,healthcoverage_f26to34_wopublic,healthcoverage_f35to44_publicall,healthcoverage_f35to44_wopublic,healthcoverage_f45to54_publicall,healthcoverage_f45to54_wopublic,healthcoverage_f55to64_publicall,healthcoverage_f55to64_wopublic,healthcoverage_f65to74_publicall,healthcoverage_f65to74_wopublic,healthcoverage_f75+_publicall,healthcoverage_f75+_wopublic,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,structures_total_yearbuilt_series,structures_built2014orlater,structures_built2010to2013,structures_built2000to2009,structures_built1990to1999,structures_built1980to1989,structures_built1970to1979,structures_built1960to1969,structures_built1950to1959,structures_built1940to1949,structures_built1939orearlier,structures_medianyearbuilt,commute_ total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,vehicles_total_series2,vehicles_none,vehicles_one,vehicles_two,vehicles_three,vehicles_four,vehicles_fiveormore,foreignborn_total,fb_europe,fb_eur_northern,fb_eur_n_ireland,fb_eur_n_denmark,fb_eur_n_norway,fb_eur_n_sweden,fb_eur_n_uk,fb_eur_n_excluding england and scotland,fb_eur_n_england,fb_eur_n_scotland,fb_eur_n_other,fb_eur_western,fb_eur_w_austria,fb_eur_w_belgium,fb_eur_w_france,fb_eur_w_germany,fb_eur_w_netherlands,fb_eur_w_switzerland,fb_eur_w_other,fb_eur_southern,fb_eur_s_greece,fb_eur_s_italy,fb_eur_s_portugal,fb_eur_s_azoresislands,fb_eur_s_spain,fb_eur_s_other,fb_eur_eastern,fb_eur_e_albania,fb_eur_e_belarus,fb_eur_e_bosniaandherzegovina,fb_eur_e_bulgaria,fb_eur_e_croatia,fb_eur_e_czechoslovakia,fb_eur_e_hungary,fb_eur_e_latvia,fb_eur_e_lithuania,fb_eur_e_macedonia,fb_eur_e_moldova,fb_eur_e_poland,fb_eur_e_romania,fb_eur_e_russia,fb_eur_e_serbia,fb_eur_e_ukraine,fb_eur_e_other,fb_eur_nec,fb_asia,fb_as_eastern,fb_as_e_china,fb_as_e_chinanohongkongortaiwan,fb_as_e_hongkong,fb_as_e_taiwan,fb_as_e_japan,fb_as_e_korea,fb_as_e_other,fb_as_southcentral,fb_as_sc_afghanistan,fb_as_sc_bangladesh,fb_as_sc_india,fb_as_sc_iran,fb_as_sc_kazakhstan,fb_as_sc_nepal,fb_as_sc_pakistan,fb_as_sc_srilanka,fb_as_sc_uzbekistan,fb_as_sc_other,fb_as_southeastern,fb_as_se_burma,fb_as_se_cambodia,fb_as_se_indonesia,fb_as_se_laos,fb_as_se_malaysia,fb_as_se_philippines,fb_as_se_singapore,fb_as_se_thailand,fb_as_se_vietnam,fb_as_se_other,fb_as_western,fb_as_w_armenia,fb_as_w_iraq,fb_as_w_israel,fb_as_w_jordan,fb_as_w_kuwait,fb_as_w_lebanon,fb_as_w_saudiarabia,fb_as_w_syria,fb_as_w_turkey,fb_as_w_yemen,fb_as_w_other,fb_as_nec,fb_africa,fb_af_eastern,fb_af_e_eritrea,fb_af_e_ethiopia,fb_af_e_kenya,fb_af_e_somalia,fb_af_e_uganda,fb_af_e_zimbabwe,fb_af_e_other,fb_af_middle,fb_af_m_cameroon,fb_af_m_congo,fb_af_m_democraticrepublicofcongo,fb_af_m_other,fb_af_northern,fb_af_n_egypt,fb_af_n_morocco,fb_af_n_sudan,fb_af_n_other,fb_af_southern,fb_af_s_southafrica,fb_af_s_other,fb_af_western,fb_af_w_caboverde,fb_af_w_ghana,fb_af_w_liberia,fb_af_w_nigeria,fb_af_w_senegal,fb_af_w_sierraleone,fb_af_w_other,fb_af_nec,fb_oceania,fb_oc_australianewzealandsubregion,fb_oc_australianewzealandsubregion_australia,fb_oc_australianewzealandsubregion_other,fb_oc_fiji,fb_oc_micronesia,fb_oc_nec,fb_americas,fb_am_latinamerica,fb_am_la_caribbean,fb_am_la_cbb_bahamas,fb_am_la_cbb_barbados,fb_am_la_cbb_cuba,fb_am_la_cbb_dominica,fb_am_la_cbb_dominicanrepublic,fb_am_la_cbb_grenada,fb_am_la_cbb_haiti,fb_am_la_cbb_jamaica,fb_am_la_cbb_stvincentandthegrenadines,fb_am_la_cbb_trinidadandtobago,fb_am_la_cbb_westindies,fb_am_la_cbb_other,fb_am_la_centralamerica,fb_am_la_centr_belize,fb_am_la_centr_costarica,fb_am_la_centr_elsalvador,fb_am_la_centr_guatemala,fb_am_la_centr_honduras,fb_am_la_centr_mexico,fb_am_la_centr_nicaragua,fb_am_la_centr_panama,fb_am_la_centr_other,fb_am_la_southamerica,fb_am_la_s_argentina,fb_am_la_s_bolivia,fb_am_la_s_brazil,fb_am_la_s_chile,fb_am_la_s_columbia,fb_am_la_s_ecuador,fb_am_la_s_guyana,fb_am_la_s_peru,fb_am_la_s_uruguay,fb_am_la_s_venezuela,fb_am_la_s_other,fb_am_northern,fb_am_n_canada,fb_am_n_other,language_total_5+_series,language_total_5to7,language_5to7_onlyenglish,language_5to7_spanish,language_5to7_otherindoeuropean,language_5to7_asianandpacificisland,language_5to7_other,language_total_18to64,language_18to64_onlyenglish,language_18to64_spanish,language_18to64_otherindoeuropean,language_18to64_asianandpacificisland,language_18to64_other,language_total_65+,language_65+_onlyenglish,language_65+_spanish,language_65+_otherindoeuropean,language_65+_asianandpacificisland,language_65+_other,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_20to21_employed.1,lfstatus_mciv_20to21_unemployed.1,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,industry_m_information_x,industry_m_finance_insurance_realestate_rental_x,industry_m_finrent_finance_insurance_x,industry_m_finrent_realestate_rental_x,industry_m_professional_scientific_managementadmin_waste_x,industry_m_profwaste_professional_scientific_technicalservices_x,industry_m_profwaste_managementcompaniesenterprises_x,industry_m_adminandsupportandwaste_x,industry_m_educational_healthcare_socialassistance_x,industry_m_edsocial_educational_x,industry_m_edsocial_healthcare_socialassistance_x,industry_m_arts_entertainmentrec_accommodation_food_x,industry_m_artsaccom_arts_entertainmentrec_x,industry_m_artsaccom_accommodation_food_x,industry_m_otherservices_notpublicadmin_x,industry_m_publicadmin_x,industry_sexbyindustrycivilianpop_totalfemale_x,industry_f_agriculture_forestry_fishing_hunting_fining_x,industry_f_agmining_agriculture_forestry_fishing_hunting_x,industry_f_agmining_fining_quarrying_oilandgas_x,industry_f_construction_x,industry_f_fanufacturing_x,industry_f_wholesaletrade_x,industry_f_retailtrade_x,industry_f_transportation_warehousing_utilities_x,industry_f_transut_transportation_warehousing_x,industry_f_transut_utilities_x,industry_f_information_x,industry_f_finance_insurance_realestate_rental_x,industry_f_finrent_finance_insurance_x,industry_f_finrent_realestate_rental_x,industry_f_professional_scientific_fanagementadmin_waste_x,industry_f_profwaste_professional_scientific_technicalservices_x,industry_f_profwaste_fanagementcompaniesenterprises_x,industry_f_adminandsupportandwaste_x,industry_f_educational_healthcare_socialassistance_x,industry_f_edsocial_educational_x,industry_f_edsocial_healthcare_socialassistance_x,industry_f_arts_entertainmentrec_accommodation_food_x,industry_f_artsaccom_arts_entertainmentrec_x,industry_f_artsaccom_accommodation_food_x,industry_f_otherservices_notpublicadmin_x,industry_f_publicadmin_x,occupation_sexbyoccupationcivilianpop_total_series_x,occupation_sexbyoccupationcivilianpop_totalmale_x,occupation_m_management_x,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+.1,lfstatus_fciv_75+.2,percapita_income_2019dollars,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information_y,industry_m_finance_insurance_realestate_rental_y,industry_m_finrent_finance_insurance_y,industry_m_finrent_realestate_rental_y,industry_m_professional_scientific_managementadmin_waste_y,industry_m_profwaste_professional_scientific_technicalservices_y,industry_m_profwaste_managementcompaniesenterprises_y,industry_m_adminandsupportandwaste_y,industry_m_educational_healthcare_socialassistance_y,industry_m_edsocial_educational_y,industry_m_edsocial_healthcare_socialassistance_y,industry_m_arts_entertainmentrec_accommodation_food_y,industry_m_artsaccom_arts_entertainmentrec_y,industry_m_artsaccom_accommodation_food_y,industry_m_otherservices_notpublicadmin_y,industry_m_publicadmin_y,industry_sexbyindustrycivilianpop_totalfemale_y,industry_f_agriculture_forestry_fishing_hunting_fining_y,industry_f_agmining_agriculture_forestry_fishing_hunting_y,industry_f_agmining_fining_quarrying_oilandgas_y,industry_f_construction_y,industry_f_fanufacturing_y,industry_f_wholesaletrade_y,industry_f_retailtrade_y,industry_f_transportation_warehousing_utilities_y,industry_f_transut_transportation_warehousing_y,industry_f_transut_utilities_y,industry_f_information_y,industry_f_finance_insurance_realestate_rental_y,industry_f_finrent_finance_insurance_y,industry_f_finrent_realestate_rental_y,industry_f_professional_scientific_fanagementadmin_waste_y,industry_f_profwaste_professional_scientific_technicalservices_y,industry_f_profwaste_fanagementcompaniesenterprises_y,industry_f_adminandsupportandwaste_y,industry_f_educational_healthcare_socialassistance_y,industry_f_edsocial_educational_y,industry_f_edsocial_healthcare_socialassistance_y,industry_f_arts_entertainmentrec_accommodation_food_y,industry_f_artsaccom_arts_entertainmentrec_y,industry_f_artsaccom_accommodation_food_y,industry_f_otherservices_notpublicadmin_y,industry_f_publicadmin_y,occupation_sexbyoccupationcivilianpop_total_series_y,occupation_sexbyoccupationcivilianpop_totalmale_y,occupation_m_management_y,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_fanagement_exceptfarmersandfarmmanagers,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educationtrainingandlibrary,occupation_f_artsdesignentertainmentsportsandmedia,occupation_f_healthcarepractitionersandtechnical,occupation_f_healthcaresupport,occupation_f_protectiveservice,occupation_f_foodprepandserving,occupation_f_buildingandgroundscleaningandmaintenance,occupation_f_personalcareandservice,occupation_f_salesandrelated,occupation_f_officeandadmin,occupation_f_farmingfishingandforestry,occupation_f_constructionandextraction,occupation_f_installationmaintenanceandrepair,occupation_f_production,occupation_f_transportation,occupation_f_materialmoving,StateFIPS,GeoFIPS,Population,Total Health Coverage Series,Total No Health Insurance Coverage,Population without Health Insurance %,Total With Health Insurance Coverage,Population with Health Insurance %,"Total With Health Insurance, Public","Covered, % with Public Health Insurance","Total With Health Insurance, Private","Covered, % with Private Health Insurance",White Alone,White Alone %,Black or African American Alone,Black or African American Alone %,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,Asian Alone,Asian Alone %,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Some Other Race Alone,Some Other Race Alone %,Two or More Races,Two or More Races %,Hispanic or Latino,Hispanic or Latino %,Minority,Minority %,Male Under 5,Female Under 5,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Under 18,18 to 24,55 and Older,65 and Older

In [145]:
data.tail()

,NAME,age_total_male,age_total_female,hhsize_avg,healthcoverage_total_mallhealthcare,healthcoverage_mu6_all,healthcoverage_m6to18_all,healthcoverage_m19to25_all,healthcoverage_m26to34_all,healthcoverage_m35to44_all,healthcoverage_m45to54_all,healthcoverage_m55to64_all,healthcoverage_m65to74_all,healthcoverage_m75+_all,healthcoverage_total_fallhealthcare,healthcoverage_fu6_all,healthcoverage_f6to18_all,healthcoverage_f19to25_all,healthcoverage_f26to34_all,healthcoverage_f35to44_all,healthcoverage_f45to54_all,healthcoverage_f55to64_all,healthcoverage_f65to74_all,healthcoverage_f75+_all,healthcoverage_total_privatehealthcare_series,healthcoverage_total_mprivate,healthcoverage_mu6_privateall,healthcoverage_mu6_woprivate,healthcoverage_m6to18_privateall,healthcoverage_m6to18_woprivate,healthcoverage_m19to25_privateall,healthcoverage_m19to25_woprivate,healthcoverage_m26to34_privateall,healthcoverage_m26to34_woprivate,healthcoverage_m35to44_privateall,healthcoverage_m35to44_woprivate,healthcoverage_m45to54_privateall,healthcoverage_m45to54_woprivate,healthcoverage_m55to64_privateall,healthcoverage_m55to64_woprivate,healthcoverage_m65to74_privateall,healthcoverage_m65to74_woprivate,healthcoverage_m75+_privateall,healthcoverage_m75+_woprivate,healthcoverage_total_fprivate,healthcoverage_fu6_privateall,healthcoverage_fu6_woprivate,healthcoverage_f6to18_privateall,healthcoverage_f6to18_woprivate,healthcoverage_f19to25_privateall,healthcoverage_f19to25_woprivate,healthcoverage_f26to34_privateall,healthcoverage_f26to34_woprivate,healthcoverage_f35to44_privateall,healthcoverage_f35to44_woprivate,healthcoverage_f45to54_privateall,healthcoverage_f45to54_woprivate,healthcoverage_f55to64_privateall,healthcoverage_f55to64_woprivate,healthcoverage_f65to74_privateall,healthcoverage_f65to74_woprivate,healthcoverage_f75+_privateall,healthcoverage_f75+_woprivate,healthcoverage_total_publichealthcare_series,healthcoverage_total_mpublic,healthcoverage_mu6_publicall,healthcoverage_mu6_wopublic,healthcoverage_m6to18_publicall,healthcoverage_m6to18_wopublic,healthcoverage_m19to25_publicall,healthcoverage_m19to25_wopublic,healthcoverage_m26to34_publicall,healthcoverage_m26to34_wopublic,healthcoverage_m35to44_publicall,healthcoverage_m35to44_wopublic,healthcoverage_m45to54_publicall,healthcoverage_m45to54_wopublic,healthcoverage_m55to64_publicall,healthcoverage_m55to64_wopublic,healthcoverage_m65to74_publicall,healthcoverage_m65to74_wopublic,healthcoverage_m75+_publicall,healthcoverage_m75+_wopublic,healthcoverage_total_fpublic,healthcoverage_fu6_publicall,healthcoverage_fu6_wopublic,healthcoverage_f6to18_publicall,healthcoverage_f6to18_wopublic,healthcoverage_f19to25_publicall,healthcoverage_f19to25_wopublic,healthcoverage_f26to34_publicall,healthcoverage_f26to34_wopublic,healthcoverage_f35to44_publicall,healthcoverage_f35to44_wopublic,healthcoverage_f45to54_publicall,healthcoverage_f45to54_wopublic,healthcoverage_f55to64_publicall,healthcoverage_f55to64_wopublic,healthcoverage_f65to74_publicall,healthcoverage_f65to74_wopublic,healthcoverage_f75+_publicall,healthcoverage_f75+_wopublic,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,structures_total_yearbuilt_series,structures_built2014orlater,structures_built2010to2013,structures_built2000to2009,structures_built1990to1999,structures_built1980to1989,structures_built1970to1979,structures_built1960to1969,structures_built1950to1959,structures_built1940to1949,structures_built1939orearlier,structures_medianyearbuilt,commute_ total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,vehicles_total_series2,vehicles_none,vehicles_one,vehicles_two,vehicles_three,vehicles_four,vehicles_fiveormore,foreignborn_total,fb_europe,fb_eur_northern,fb_eur_n_ireland,fb_eur_n_denmark,fb_eur_n_norway,fb_eur_n_sweden,fb_eur_n_uk,fb_eur_n_excluding england and scotland,fb_eur_n_england,fb_eur_n_scotland,fb_eur_n_other,fb_eur_western,fb_eur_w_austria,fb_eur_w_belgium,fb_eur_w_france,fb_eur_w_germany,fb_eur_w_netherlands,fb_eur_w_switzerland,fb_eur_w_other,fb_eur_southern,fb_eur_s_greece,fb_eur_s_italy,fb_eur_s_portugal,fb_eur_s_azoresislands,fb_eur_s_spain,fb_eur_s_other,fb_eur_eastern,fb_eur_e_albania,fb_eur_e_belarus,fb_eur_e_bosniaandherzegovina,fb_eur_e_bulgaria,fb_eur_e_croatia,fb_eur_e_czechoslovakia,fb_eur_e_hungary,fb_eur_e_latvia,fb_eur_e_lithuania,fb_eur_e_macedonia,fb_eur_e_moldova,fb_eur_e_poland,fb_eur_e_romania,fb_eur_e_russia,fb_eur_e_serbia,fb_eur_e_ukraine,fb_eur_e_other,fb_eur_nec,fb_asia,fb_as_eastern,fb_as_e_china,fb_as_e_chinanohongkongortaiwan,fb_as_e_hongkong,fb_as_e_taiwan,fb_as_e_japan,fb_as_e_korea,fb_as_e_other,fb_as_southcentral,fb_as_sc_afghanistan,fb_as_sc_bangladesh,fb_as_sc_india,fb_as_sc_iran,fb_as_sc_kazakhstan,fb_as_sc_nepal,fb_as_sc_pakistan,fb_as_sc_srilanka,fb_as_sc_uzbekistan,fb_as_sc_other,fb_as_southeastern,fb_as_se_burma,fb_as_se_cambodia,fb_as_se_indonesia,fb_as_se_laos,fb_as_se_malaysia,fb_as_se_philippines,fb_as_se_singapore,fb_as_se_thailand,fb_as_se_vietnam,fb_as_se_other,fb_as_western,fb_as_w_armenia,fb_as_w_iraq,fb_as_w_israel,fb_as_w_jordan,fb_as_w_kuwait,fb_as_w_lebanon,fb_as_w_saudiarabia,fb_as_w_syria,fb_as_w_turkey,fb_as_w_yemen,fb_as_w_other,fb_as_nec,fb_africa,fb_af_eastern,fb_af_e_eritrea,fb_af_e_ethiopia,fb_af_e_kenya,fb_af_e_somalia,fb_af_e_uganda,fb_af_e_zimbabwe,fb_af_e_other,fb_af_middle,fb_af_m_cameroon,fb_af_m_congo,fb_af_m_democraticrepublicofcongo,fb_af_m_other,fb_af_northern,fb_af_n_egypt,fb_af_n_morocco,fb_af_n_sudan,fb_af_n_other,fb_af_southern,fb_af_s_southafrica,fb_af_s_other,fb_af_western,fb_af_w_caboverde,fb_af_w_ghana,fb_af_w_liberia,fb_af_w_nigeria,fb_af_w_senegal,fb_af_w_sierraleone,fb_af_w_other,fb_af_nec,fb_oceania,fb_oc_australianewzealandsubregion,fb_oc_australianewzealandsubregion_australia,fb_oc_australianewzealandsubregion_other,fb_oc_fiji,fb_oc_micronesia,fb_oc_nec,fb_americas,fb_am_latinamerica,fb_am_la_caribbean,fb_am_la_cbb_bahamas,fb_am_la_cbb_barbados,fb_am_la_cbb_cuba,fb_am_la_cbb_dominica,fb_am_la_cbb_dominicanrepublic,fb_am_la_cbb_grenada,fb_am_la_cbb_haiti,fb_am_la_cbb_jamaica,fb_am_la_cbb_stvincentandthegrenadines,fb_am_la_cbb_trinidadandtobago,fb_am_la_cbb_westindies,fb_am_la_cbb_other,fb_am_la_centralamerica,fb_am_la_centr_belize,fb_am_la_centr_costarica,fb_am_la_centr_elsalvador,fb_am_la_centr_guatemala,fb_am_la_centr_honduras,fb_am_la_centr_mexico,fb_am_la_centr_nicaragua,fb_am_la_centr_panama,fb_am_la_centr_other,fb_am_la_southamerica,fb_am_la_s_argentina,fb_am_la_s_bolivia,fb_am_la_s_brazil,fb_am_la_s_chile,fb_am_la_s_columbia,fb_am_la_s_ecuador,fb_am_la_s_guyana,fb_am_la_s_peru,fb_am_la_s_uruguay,fb_am_la_s_venezuela,fb_am_la_s_other,fb_am_northern,fb_am_n_canada,fb_am_n_other,language_total_5+_series,language_total_5to7,language_5to7_onlyenglish,language_5to7_spanish,language_5to7_otherindoeuropean,language_5to7_asianandpacificisland,language_5to7_other,language_total_18to64,language_18to64_onlyenglish,language_18to64_spanish,language_18to64_otherindoeuropean,language_18to64_asianandpacificisland,language_18to64_other,language_total_65+,language_65+_onlyenglish,language_65+_spanish,language_65+_otherindoeuropean,language_65+_asianandpacificisland,language_65+_other,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_20to21_employed.1,lfstatus_mciv_20to21_unemployed.1,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,industry_m_information_x,industry_m_finance_insurance_realestate_rental_x,industry_m_finrent_finance_insurance_x,industry_m_finrent_realestate_rental_x,industry_m_professional_scientific_managementadmin_waste_x,industry_m_profwaste_professional_scientific_technicalservices_x,industry_m_profwaste_managementcompaniesenterprises_x,industry_m_adminandsupportandwaste_x,industry_m_educational_healthcare_socialassistance_x,industry_m_edsocial_educational_x,industry_m_edsocial_healthcare_socialassistance_x,industry_m_arts_entertainmentrec_accommodation_food_x,industry_m_artsaccom_arts_entertainmentrec_x,industry_m_artsaccom_accommodation_food_x,industry_m_otherservices_notpublicadmin_x,industry_m_publicadmin_x,industry_sexbyindustrycivilianpop_totalfemale_x,industry_f_agriculture_forestry_fishing_hunting_fining_x,industry_f_agmining_agriculture_forestry_fishing_hunting_x,industry_f_agmining_fining_quarrying_oilandgas_x,industry_f_construction_x,industry_f_fanufacturing_x,industry_f_wholesaletrade_x,industry_f_retailtrade_x,industry_f_transportation_warehousing_utilities_x,industry_f_transut_transportation_warehousing_x,industry_f_transut_utilities_x,industry_f_information_x,industry_f_finance_insurance_realestate_rental_x,industry_f_finrent_finance_insurance_x,industry_f_finrent_realestate_rental_x,industry_f_professional_scientific_fanagementadmin_waste_x,industry_f_profwaste_professional_scientific_technicalservices_x,industry_f_profwaste_fanagementcompaniesenterprises_x,industry_f_adminandsupportandwaste_x,industry_f_educational_healthcare_socialassistance_x,industry_f_edsocial_educational_x,industry_f_edsocial_healthcare_socialassistance_x,industry_f_arts_entertainmentrec_accommodation_food_x,industry_f_artsaccom_arts_entertainmentrec_x,industry_f_artsaccom_accommodation_food_x,industry_f_otherservices_notpublicadmin_x,industry_f_publicadmin_x,occupation_sexbyoccupationcivilianpop_total_series_x,occupation_sexbyoccupationcivilianpop_totalmale_x,occupation_m_management_x,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+.1,lfstatus_fciv_75+.2,percapita_income_2019dollars,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information_y,industry_m_finance_insurance_realestate_rental_y,industry_m_finrent_finance_insurance_y,industry_m_finrent_realestate_rental_y,industry_m_professional_scientific_managementadmin_waste_y,industry_m_profwaste_professional_scientific_technicalservices_y,industry_m_profwaste_managementcompaniesenterprises_y,industry_m_adminandsupportandwaste_y,industry_m_educational_healthcare_socialassistance_y,industry_m_edsocial_educational_y,industry_m_edsocial_healthcare_socialassistance_y,industry_m_arts_entertainmentrec_accommodation_food_y,industry_m_artsaccom_arts_entertainmentrec_y,industry_m_artsaccom_accommodation_food_y,industry_m_otherservices_notpublicadmin_y,industry_m_publicadmin_y,industry_sexbyindustrycivilianpop_totalfemale_y,industry_f_agriculture_forestry_fishing_hunting_fining_y,industry_f_agmining_agriculture_forestry_fishing_hunting_y,industry_f_agmining_fining_quarrying_oilandgas_y,industry_f_construction_y,industry_f_fanufacturing_y,industry_f_wholesaletrade_y,industry_f_retailtrade_y,industry_f_transportation_warehousing_utilities_y,industry_f_transut_transportation_warehousing_y,industry_f_transut_utilities_y,industry_f_information_y,industry_f_finance_insurance_realestate_rental_y,industry_f_finrent_finance_insurance_y,industry_f_finrent_realestate_rental_y,industry_f_professional_scientific_fanagementadmin_waste_y,industry_f_profwaste_professional_scientific_technicalservices_y,industry_f_profwaste_fanagementcompaniesenterprises_y,industry_f_adminandsupportandwaste_y,industry_f_educational_healthcare_socialassistance_y,industry_f_edsocial_educational_y,industry_f_edsocial_healthcare_socialassistance_y,industry_f_arts_entertainmentrec_accommodation_food_y,industry_f_artsaccom_arts_entertainmentrec_y,industry_f_artsaccom_accommodation_food_y,industry_f_otherservices_notpublicadmin_y,industry_f_publicadmin_y,occupation_sexbyoccupationcivilianpop_total_series_y,occupation_sexbyoccupationcivilianpop_totalmale_y,occupation_m_management_y,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_fanagement_exceptfarmersandfarmmanagers,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educationtrainingandlibrary,occupation_f_artsdesignentertainmentsportsandmedia,occupation_f_healthcarepractitionersandtechnical,occupation_f_healthcaresupport,occupation_f_protectiveservice,occupation_f_foodprepandserving,occupation_f_buildingandgroundscleaningandmaintenance,occupation_f_personalcareandservice,occupation_f_salesandrelated,occupation_f_officeandadmin,occupation_f_farmingfishingandforestry,occupation_f_constructionandextraction,occupation_f_installationmaintenanceandrepair,occupation_f_production,occupation_f_transportation,occupation_f_materialmoving,StateFIPS,GeoFIPS,Population,Total Health Coverage Series,Total No Health Insurance Coverage,Population without Health Insurance %,Total With Health Insurance Coverage,Population with Health Insurance %,"Total With Health Insurance, Public","Covered, % with Public Health Insurance","Total With Health Insurance, Private","Covered, % with Private Health Insurance",White Alone,White Alone %,Black or African American Alone,Black or African American Alone %,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,Asian Alone,Asian Alone %,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Some Other Race Alone,Some Other Race Alone %,Two or More Races,Two or More Races %,Hispanic or Latino,Hispanic or Latino %,Minority,Minority %,Male Under 5,Female Under 5,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Under 18,18 to 24,55 and Older,65 and Older

In [146]:
data.to_csv('../data/progress.csv')