In [82]:
# df_styled = fig1.style.set_properties(**{'border': '1.3px solid black','color': 'black'}).set_precision(0).set_caption('Population Change Over Time')
# Deprecated... but it works... check this out later
# https://stackoverflow.com/questions/23981601/format-certain-floating-dataframe-columns-into-percentage-in-pandas

Good link for styling: https://www.analyticsvidhya.com/blog/2021/06/style-your-pandas-dataframe-and-make-it-stunning/

In [17]:
# pip install dataframe_image

###### Imports and Settings

In [62]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
import dataframe_image as dfi
from collections import deque
from functools import reduce
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
pd.options.mode.chained_assignment = None  # default='warn'

###### Functions

In [115]:
def prettypercentchange(x, y):
    return round((x - y)*100/y, 1).astype(str)+'%'
def mathpercentchange(x, y):
    return round((x - y)/y, 1)

In [100]:
Prefix2010Subject = pd.read_csv('../../data/Prefix2010Subject.csv')
Prefix2020Subject = pd.read_csv('../../data/Prefix2020Subject.csv')
Prefix2000SF1 = pd.read_csv('../../data/Prefix2000SF1.csv')
Prefix2000SF3 = pd.read_csv('../../data/Prefix2000SF3.csv')
Prefix2010SF1 = pd.read_csv('../../data/Prefix2010SF1.csv')
Prefix2010ACS = pd.read_csv('../../data/Prefix2010ACS.csv')
Prefix2020PL = pd.read_csv('../../data/Prefix2020PL.csv')
Prefix2020ACS = pd.read_csv('../../data/Prefix2020ACS.csv')

In [101]:
dfs = [Prefix2000SF1, Prefix2000SF3, Prefix2010SF1, Prefix2010ACS, Prefix2010Subject, Prefix2020PL, Prefix2020ACS, Prefix2020Subject]

In [102]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['NAME'],
                                            how='outer'), dfs)

In [103]:
df_merged.head(3)

,NAME,Population 2000,Male Under 5 2000,Female Under 5 2000,Male 5 to 9 2000,Female 5 to 9 2000,Male 10 to 14 2000,Female 10 to 14 2000,Male 15 to 17 2000,Female 15 to 17 2000,Male 18 to 24 2000,Female 18 to 24 2000,Male 25 to 34 2000,Female 25 to 34 2000,Male 35 to 44 2000,Female 35 to 44 2000,Male 45 to 54 2000,Female 45 to 54 2000,Male 55 to 64 2000,Female 55 to 64 2000,Male 65 to 74 2000,Female 65 to 74 2000,Male 75 to 84 2000,Female 75 to 84 2000,Male 85 and Older 2000,Female 85 and Older 2000,Age:Under 18 2000,Age:18 to 54 2000,Age:55 and Older 2000,Age:65 and Older 2000,White Alone 2000,White Alone % 2000,Black or African American Alone 2000,Black or African American Alone % 2000,American Indian Alaska Native Alone 2000,American Indian Alaska Native Alone % 2000,Asian Alone 2000,Asian Alone % 2000,Native Hawaiian Other Pacific Islander Alone 2000,Native Hawaiian Other Pacific Islander Alone % 2000,Some Other Race Alone 2000,Some Other Race Alone % 2000,Two or More Races 2000,Two or More Races % 2000,Hispanic or Latino 2000,Hispanic or Latino % 2000,Minority 2000,Minority % 2000,Total Households 2000,Family Households 2000,Family Households: Married Couple Family 2000,Family Households: Not Married Couple Family 2000,Family Households: Not Married Couple: Male no Spouse 2000,Family Households: Not Married Couple: Female no Spouse 2000,Nonfamily Households 2000,Nonfamily Households: Householder Alone 2000,Nonfamily Households: Householder not Alone 2000,Average Household Size 2000,Occupancy:Total Households 2000,Occupancy:Occupied Units 2000,Occupancy%:Occupied Units 2000,Occupancy:Vacant Units 2000,Occupancy%:Vacant Units 2000,Tenure:Total Households 2000,Tenure:Owners 2000,Tenure%:Owners 2000,Tenure:Renters 2000,Tenure%:Renters 2000,Median Household Income 2000,HHIncome:Total Households 2000,"HHIncome:Less than 10,000 2000","HHIncome%:Less than 10,000 2000","HHIncome:10 to 14,999 2000","HHIncome%:10 to 14,999 2000","HHIncome:15 to 19,999 2000","HHIncome%:15 to 19,999 2000","HHIncome:20 to 24,999 2000","HHIncome%:20 to 24,999 2000","HHIncome:25 to 29,999 2000","HHIncome%:25 to 29,999 2000","HHIncome:30 to 34,999 2000","HHIncome:%30 to 34,999 2000","HHIncome:35 to 39,999 2000","HHIncome%:35 to 39,999 2000","HHIncome:40 to 44,999 2000","HHIncome%:40 to 44,999 2000","HHIncome:45 to 49,999 2000","HHIncome%:45 to 49,999 2000","HHIncome:50 to 59,999 2000","HHIncome%:50 to 59,999 2000","HHIncome:60 to 74,999 2000","HHIncome%:60 to 74,999 2000","HHIncome:75 to 99,999 2000","HHIncome%:75 to 99,999 2000","HHIncome:100 to 124,999 2000","HHIncome%:100 to 124,999 2000","HHIncome:125 to 149,999 2000","HHIncome%:125 to 149,999 2000","HHIncome:150 to 199,999 2000","HHIncome%:150 to 199,999 2000",HHIncome:200K or More 2000,HHIncome%:200K or More 2000,Ed:Population 25+ Educational Attainment 2000,Ed:Less than High School 2000,Ed%:Less than High School 2000,Ed:High School Graduate or Equivalency 2000,Ed%:High School Graduate or Equivalency 2000,Ed%:High School Graduate or More 2000,Ed:Some College 2000,Ed%:Some College 2000,Ed%:Some College or More 2000,Ed:Associates 2000,Ed%:Associates 2000,Ed:Bachelors 2000,Ed%:Bachelors 2000,Ed%:Bachelors or More 2000,Ed:Masters 2000,Ed%:Masters 2000,Ed%:Masters or More 2000,Ed:Professional School Degree 2000,Ed%:Professional School Degree 2000,Ed%:Professional School Degree or More 2000,Ed:Doctorate Degree 2000,Ed%:Doctorate Degree 2000,Ind:Employed Civilians 16+ 2000,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2000","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2000",Ind:Construction 2000,Ind%:Construction 2000,Ind:Manufacturing 2000,Ind%:Manufacturing 2000,Ind:Wholesale Trade 2000,Ind%:Wholesale Trade 2000,Ind:Retail Trade 2000,Ind%:Retail Trade 2000,"Ind:Transportation and Warehousing, Utilities 2000","Ind%:Transportation and Warehousing, Utilities 2000",Ind:Information 2000,Ind%:Information 2000,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind:Educational, Health and Social Services 2000","Ind%:Educational, Health and Social Services 2000","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2000","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2000",Ind:Other Services (Except Public Administration) 2000,Ind%:Other Services (Except Public Administration) 2000,Ind:Public Administration 2000,Ind%:Public Administration 2000,Employed Civilians 16+ Occupational 2000,"Occ:Management, Business, and Financial Operations 2000","Occ%:Management, Business, and Financial Operations 2000",Occ:Professional and Related 2000,Occ%:Professional and Related 2000,Occ:Healthcare Support 2000,Occ%:Healthcare Support 2000,Occ:Protective Services 2000,Occ%:Protective Services 2000,Occ:Food Preparation and Serving Related 2000,Occ%:Food Preparation and Serving Related 2000,Occ:Building and Grounds Cleaning and Maintenance 2000,Occ%:Building and Grounds Cleaning and Maintenance 2000,Occ:Personal Care and Service 2000,Occ%:Personal Care and Service 2000,Occ:Sales and Related 2000,Occ%:Sales and Related 2000,Occ:Office and Administrative Support 2000,Occ%:Office and Administrative Support 2000,"Occ:Farming, Fishing, and Forestry 2000","Occ%:Farming, Fishing, and Forestry 2000","Occ:Construction, Extraction, and Maintenance 2000","Occ%:Construction, Extraction, and Maintenance 2000",Occ:Production 2000,Occ%:Production 2000,Occ:Transportation and Material Moving 2000,Occ%:Transportation and Material Moving 2000,Sector: Total Workers 2000,Sector:Private 2000,Sector%:Private 2000,Sector:Public 2000,Sector%:Public 2000,Sector:Self-Employed 2000,Sector%:Self-Employed 2000,Sector:Non-Profit 2000,Sector%:Non-Profit 2000,Sector:Unpaid Family Workers 2000,Sector%:Unpaid Family Workers 2000,Employed 2000,Unemployed 2000,Unemployment Rate 2000,Per Capita Income 2000,Poverty:Population for Whom Poverty Status is Determined 2000,Poverty: Population Below Poverty Level 2000,Poverty%: Below Poverty Level 2000,CB:Total Housing Units 2000,CB:Cost Burdened Housholds 2000,CB:Renter Occupied Units 2000,CB:Cost Burdened Renters 2000,CB%:Cost Burdened Renters 2000,CB:Owner Occupied Units 2000,CB:Cost Burdened Homeowners 2000,CB%: Cost Burdened Homeowners 2000,CB:Severe Cost Burdened Households 2000,CB%:Severe Cost Burdened Households 2000,Median Home Value Owner Occupied 2000,Median Gross Rent 2000,Units:Total Series 2000,"Units:1 Unit, Detached 2000","Units%:1 Unit, Detached 2000","Units:1 Unit, Attached 2000","Units%:1 Unit, Attached 2000",Units:2 2000,Units%:2 2000,Units:3 to 4 2000,Units%:3 to 4 2000,Units:5 to 9 2000,Units%:5 to 9 2000,Units:10 to 19 2000,Units%:10 to 19 2000,Units:20 to 49 2000,Units%:20 to 49 2000,Units:50 or More 2000,Units%:50 or More 2000,Units:Mobile Home 2000,Units%:Mobile Home 2000,"Units:Boat, RV, Van etc 2000","Units%:Boat, RV, Van etc 2000",Transpo:Workers Commuting 2000,"Transpo:Car, Truck, or Van 2000","Transpo%:Car, Truck, or Van 2000",Transpo:Public Transportation 2000,Transpo%:Public Transportation 2000,Transpo:Bicycle 2000,Transpo%:Bicycle 2000,Transpo:Walk 2000,Transpo%:Walk 2000,Transpo:Worked From Home 2000,Transpo%:Worked From Home 2000,"Transpo:Taxi, Motorcycle, Other 2000","Transpo%:Taxi, Motorcycle, Other 2000",Vehicles:Households 2000,Vehicles:None 2000,Vehicles%:None 2000,Vehicles:One 2000,Vehicles%:One 2000,Vehicles:Two 2000,Vehicles%:Two 2000,Vehicles:Three 2000,Vehicles%:Three 2000,Vehicles:Four 2000,Vehicles%:Four 2000,Vehicles:Five or More 2000,Vehicles%:Five or More 2000,Vet:Population 18+ 2000,Vet:Veteran 2000,Vet%:Veteran 2000,Vet:Nonveteran 2000,Vet%:Nonveteran 2000,Vet:Veteran 18 to 64 2000,Vet%:Veterans who are 18 to 64 2000,Vet:Veteran 65 and Older 2000,Vet%:Veterans who are 65 and Older 2000,Vet:Nonveteran 18 to 64 2000,Vet:Nonveteran 65 and Older 2000,Disability Tally 2000,GeoMobility:Total 2000,GeoMobility:Same House as 1995 2000,GeoMobility%:Same House as 1995 2000,GeoMobility:Moved Since 1995 2000,GeoMobility:Moved Same County as 1995 2000,GeoMobility%:Moved Same County as 1995 2000,GeoMobility:Moved Different County Same State as 1995 2000,GeoMobility%:Moved Different County Same State as 1995 2000,GeoMobility:Moved Different State from 1995 2000,GeoMobility%:Moved Different State from 1995 2000,GeoMobility:Moved From Abroad Since 1995 2000,GeoMobility%:Moved From Abroad Since 1995 2000,ForeignBorn:Foreign Born 2000,ForeignBorn%:Foreign Born 2000,ForeignBorn:Native Born 2000,ForeignBorn:Foreign Born Naturalized Citizen 2000,ForeignBorn%:Foreign Born Population that are Naturalized Citizen 2000,ForeignBorn:Foreign Born Not a Citizen 2000,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen 2000,Foreign Born Population 2000,ForeignBorn:Europe 2000,ForeignBorn:Asia 2000,ForeignBorn:Africa 2000,ForeignBorn:Oceania 2000,"ForeignBorn:Central & South America, Caribbean 2000",ForeignBorn:Canada & Other Northern American 2000,Language:Population 5 and Older 2000,Language:Speak Only English 2000,Language%:Speak Only English 2000,Language:Speak Spanish 2000,Language:Spanish:Speak English Very Well 2000,Language:Spanish:Speak English Well 2000,Language:Spanish:Speak English Not Well 2000,Language:Spanish:Speak English Not At All 2000,Language:Speak Other Indo-European Language 2000,Language:Other Indo-European:Speak English Very Well 2000,Language:Other Indo-European:Speak English Well 2000,Language:Other Indo-European:Speak English Not Well 2000,Language:Other Indo-European:Speak English Not At All 2000,Language:Speak Asian or Pacific Island Language 2000,Language:Asian or Pacific Island:Speak English Very Well 2000,Language:Asian or Pacific Island:Speak English Well 2000,Language:Asian or Pacific Island:Speak English Not Well 2000,Language:Asian or Pacific Island:Speak English Not At All 2000,Language:Speak Other Language 2000,Language:Other:Speak English Very Well 2000,Language:Other:Speak English Well 2000,Language:Other:Speak English Not Well 2000,Language:Other:Speak English Not At All 2000,Language%:Speak Language Besides English 2000,Language%:Of Those that Speak Another Language and Speak English Not Well or At All 2000,Population 2010,Male Under 5 2010,Female Under 5 2010,Male 5 to 9 2010,Female 5 to 9 2010,Male 10 to 14 2010,Female 10 to 14 2010,Male 15 to 17 2010,Female 15 to 17 2010,Male 18 to 24 2010,Female 18 to 24 2010,Male 25 to 34 2010,Female 25 to 34 2010,Male 35 to 44 2010,Female 35 to 44 2010,Male 45 to 54 2010,Female 45 to 54 2010,Male 55 to 64 2010,Female 55 to 64 2010,Male 65 to 74 2010,Female 65 to 74 2010,Male 75 to 84 2010,Female 75 to 84 2010,Male 85 and Older 2010,Female 85 and Older 2010,Age:Under 18 2010,Age:18 to 54 2010,Age:55 and Older 2010,Age:65 and Older 2010,White Alone 2010,White Alone % 2010,Black or African American Alone 2010,Black or African American Alone % 2010,American Indian Alaska Native Alone 2010,American Indian Alaska Native Alone % 2010,Asian Alone 2010,Asian Alone % 2010,Native Hawaiian Other Pacific Islander Alone 2010,Native Hawaiian Other Pacific Islander Alone % 2010,Some Other Race Alone 2010,Some Other Race Alone % 2010,Two or More Races 2010,Two or More Races % 2010,Hispanic or Latino 2010,Hispanic or Latino % 2010,Minority 2010,Minority % 2010,Total Households 2010,Family Households 2010,Family Households: Married Couple Family 2010,Family Households: Not Married Couple Family 2010,Family Households: Not Married Couple: Male no Spouse 2010,Family Households: Not Married Couple: Female no Spouse 2010,Nonfamily Households 2010,Nonfamily Households: Householder Alone 2010,Nonfamily Households: Householder not Alone 2010,Average Household Size 2010,Occupancy:Total Households 2010,Occupancy:Occupied Units 2010,Occupancy%:Occupied Units 2010,Occupancy:Vacant Units 2010,Occupancy%:Vacant Units 2010,Tenure:Total Households 2010,Tenure:Owners 2010,Tenure%:Owners 2010,Tenure:Renters 2010,Tenure%:Renters 2010,Median Household Income 2010,HHIncome:Total Households 2010,"HHIncome:Less than 10,000 2010","HHIncome%:Less than 10,000 2010","HHIncome:10 to 14,999 2010","HHIncome%:10 to 14,999 2010","HHIncome:15 to 19,999 2010","HHIncome%:15 to 19,999 2010","HHIncome:20 to 24,999 2010","HHIncome%:20 to 24,999 2010","HHIncome:25 to 29,999 2010","HHIncome%:25 to 29,999 2010","HHIncome:30 to 34,999 2010","HHIncome:%30 to 34,999 2010","HHIncome:35 to 39,999 2010","HHIncome%:35 to 39,999 2010","HHIncome:40 to 44,999 2010","HHIncome%:40 to 44,999 2010","HHIncome:45 to 49,999 2010","HHIncome%:45 to 49,999 2010","HHIncome:50 to 59,999 2010","HHIncome%:50 to 59,999 2010","HHIncome:60 to 74,999 2010","HHIncome%:60 to 74,999 2010","HHIncome:75 to 99,999 2010","HHIncome%:75 to 99,999 2010","HHIncome:100 to 124,999 2010","HHIncome%:100 to 124,999 2010","HHIncome:125 to 149,999 2010","HHIncome%:125 to 149,999 2010","HHIncome:150 to 199,999 2010","HHIncome%:150 to 199,999 2010",HHIncome:200K or More 2010,HHIncome%:200K or More 2010,Ed:Population 25+ Educational Attainment 2010,Ed:Less than High School 2010,Ed%:Less than High School 2010,Ed:High School Graduate or Equivalency 2010,Ed%:High School Graduate or Equivalency 2010,Ed%:High School Graduate or More 2010,Ed:Some College 2010,Ed%:Some College 2010,Ed%:Some College or More 2010,Ed:Associates 2010,Ed%:Associates 2010,Ed:Bachelors 2010,Ed%:Bachelors 2010,Ed%:Bachelors or More 2010,Ed:Masters 2010,Ed%:Masters 2010,Ed%:Masters or More 2010,Ed:Professional School Degree 2010,Ed%:Professional School Degree 2010,Ed%:Professional School Degree or More 2010,Ed:Doctorate Degree 2010,Ed%:Doctorate Degree 2010,Ind:Employed Civilians 16+ 2010,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2010","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2010",Ind:Construction 2010,Ind%:Construction 2010,Ind:Manufacturing 2010,Ind%:Manufacturing 2010,Ind:Wholesale Trade 2010,Ind%:Wholesale Trade 2010,Ind:Retail Trade 2010,Ind%:Retail Trade 2010,"Ind:Transportation and Warehousing, Utilities 2010","Ind%:Transportation and Warehousing, Utilities 2010",Ind:Information 2010,Ind%:Information 2010,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind:Educational, Health and Social Services 2010","Ind%:Educational, Health and Social Services 2010","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2010","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2010",Ind:Other Services (Except Public Administration) 2010,Ind%:Other Services (Except Public Administration) 2010,Ind:Public Administration 2010,Ind%:Public Administration 2010,Employed Civilians 16+ Occupational 2010,"Occ:Management, Business, and Financial Operations 2010","Occ%:Management, Business, and Financial Operations 2010",Occ:Professional and Related 2010,Occ%:Professional and Related 2010,Occ:Healthcare Support 2010,Occ%:Healthcare Support 2010,Occ:Protective Services 2010,Occ%:Protective Services 2010,Occ:Food Preparation and Serving Related 2010,Occ%:Food Preparation and Serving Related 2010,Occ:Building and Grounds Cleaning and Maintenance 2010,Occ%:Building and Grounds Cleaning and Maintenance 2010,Occ:Personal Care and Service 2010,Occ%:Personal Care and Service 2010,Occ:Sales and Related 2010,Occ%:Sales and Related 2010,Occ:Office and Administrative Support 2010,Occ%:Office and Administrative Support 2010,"Occ:Farming, Fishing, and Forestry 2010","Occ%:Farming, Fishing, and Forestry 2010","Occ:Construction, Extraction, and Maintenance 2010","Occ%:Construction, Extraction, and Maintenance 2010",Occ:Production 2010,Occ%:Production 2010,Occ:Transportation and Material Moving 2010,Occ%:Transportation and Material Moving 2010,Sector: Total Workers 2010,Sector:Private 2010,Sector%:Private 2010,Sector:Public 2010,Sector%:Public 2010,Sector:Self-Employed 2010,Sector%:Self-Employed 2010,Sector:Non-Profit 2010,Sector%:Non-Profit 2010,Sector:Unpaid Family Workers 2010,Sector%:Unpaid Family Workers 2010,Employed 2010,Unemployed 2010,Unemployment Rate 2010,Per Capita Income 2010,Poverty:Population for Whom Poverty Status is Determined 2010,Poverty: Population Below Poverty Level 2010,Poverty%: Below Poverty Level 2010,CB:Total Housing Units 2010,CB:Cost Burdened Housholds 2010,CB:Renter Occupied Units 2010,CB:Cost Burdened Renters 2010,CB%:Cost Burdened Renters 2010,CB:Owner Occupied Units 2010,CB:Cost Burdened Homeowners 2010,CB%: Cost Burdened Homeowners 2010,CB:Severe Cost Burdened Households 2010,CB%:Severe Cost Burdened Households 2010,Median Home Value Owner Occupied with Mortgage 2010,Median Home Value Owner Occupied without Mortgage 2010,Median Gross Rent 2010,Units:Total Series 2010,"Units:1 Unit, Detached 2010","Units%:1 Unit, Detached 2010","Units:1 Unit, Attached 2010","Units%:1 Unit, Attached 2010",Units:2 2010,Units%:2 2010,Units:3 to 4 2010,Units%:3 to 4 2010,Units:5 to 9 2010,Units%:5 to 9 2010,Units:10 to 19 2010,Units%:10 to 19 2010,Units:20 to 49 2010,Units%:20 to 49 2010,Units:50 or More 2010,Units%:50 or More 2010,Units:Mobile Home 2010,Units%:Mobile Home 2010,"Units:Boat, RV, Van etc 2010","Units%:Boat, RV, Van etc 2010",Transpo:Workers Commuting 2010,"Transpo:Car, Truck, or Van 2010","Transpo%:Car, Truck, or Van 2010",Transpo:Public Transportation 2010,Transpo%:Public Transportation 2010,Transpo:Bicycle 2010,Transpo%:Bicycle 2010,Transpo:Walk 2010,Transpo%:Walk 2010,Transpo:Worked From Home 2010,Transpo%:Worked From Home 2010,"Transpo:Taxi, Motorcycle, Other 2010","Transpo%:Taxi, Motorcycle, Other 2010",Vehicles:Households 2010,Vehicles:None 2010,Vehicles%:None 2010,Vehicles:One 2010,Vehicles%:One 2010,Vehicles:Two 2010,Vehicles%:Two 2010,Vehicles:Three 2010,Vehicles%:Three 2010,Vehicles:Four 2010,Vehicles%:Four 2010,Vehicles:Five or More 2010,Vehicles%:Five or More 2010,Commute:Workers 16+ Not Working at Home 2010,Commute:Less than 10 Minutes 2010,Commute:10 to 14 Minutes 2010,Commute:15 to 19 Minutes 2010,Commute:20 to 24 Minutes 2010,Commute:25 to 29 Minutes 2010,Commute:30 to 34 Minutes 2010,Commute:35 to 44 Minutes 2010,Commute:45 to 59 Minutes 2010,Commute:60 or More Minutes 2010,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes 2010","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes 2010","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes 2010","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes 2010","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes 2010","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes 2010","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes 2010","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes 2010","Commute:Car, Truck, Van Drove Alone:60 or More Minutes 2010","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes 2010","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes 2010","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes 2010","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes 2010","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes 2010","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes 2010","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes 2010","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes 2010","Commute:Car, Truck, Van Carpooled:60 or More Minutes 2010",Vet:Population 18+ 2010,Vet:Veteran 2010,Vet%:Veteran 2010,Vet:Nonveteran 2010,Vet%:Nonveteran 2010,Vet:Veteran 18 to 64 2010,Vet%:Veterans who are 18 to 64 2010,Vet:Veteran 65 and Older 2010,Vet%:Veterans who are 65 and Older 2010,Vet:Nonveteran 18 to 64 2010,Vet:Nonveteran 65 and Older 2010,GeoMobility:Total 2010,GeoMobili

Filter to Gallatin Geographies

In [104]:
transp = df_merged.transpose()
transp.columns = transp.iloc[0]
transp = transp.loc[transp['Stewart County, Tennessee'] != 'Stewart County, Tennessee']

In [105]:
numcols = list(transp.columns)
numcols
transp[numcols] = transp[numcols].astype(float)

In [106]:
#Geographies Needed: Tennessee, GNRC, MPO, Goodlettsville city, Tennessee, Millersville city, Tennessee, Portland city, Tennessee, White House city, Tennessee, 
#Gallatin city, Tennessee, Hendersonville city, Tennessee, Westmoreland City, Tennessee, Sumner County, Tennessee 
gallatindata = transp[['Tennessee', 'GNRC','MPO','Sumner County, Tennessee','Gallatin city, Tennessee', 'Goodlettsville city, Tennessee', 
                       'Millersville city, Tennessee', 'Portland city, Tennessee', 'White House city, Tennessee', 'Hendersonville city, Tennessee', 
                       'Westmoreland town, Tennessee']]
gallatindata.columns = ['Tennessee', 'GNRC','MPO','Sumner County','Gallatin', 'Goodlettsville', 'Millersville', 'Portland', 
                        'White House', 'Hendersonville', 'Westmoreland']
data = gallatindata.transpose().reset_index()
data = data.rename(columns = {'index':'NAME'})
data.head(3)

,NAME,Population 2000,Male Under 5 2000,Female Under 5 2000,Male 5 to 9 2000,Female 5 to 9 2000,Male 10 to 14 2000,Female 10 to 14 2000,Male 15 to 17 2000,Female 15 to 17 2000,Male 18 to 24 2000,Female 18 to 24 2000,Male 25 to 34 2000,Female 25 to 34 2000,Male 35 to 44 2000,Female 35 to 44 2000,Male 45 to 54 2000,Female 45 to 54 2000,Male 55 to 64 2000,Female 55 to 64 2000,Male 65 to 74 2000,Female 65 to 74 2000,Male 75 to 84 2000,Female 75 to 84 2000,Male 85 and Older 2000,Female 85 and Older 2000,Age:Under 18 2000,Age:18 to 54 2000,Age:55 and Older 2000,Age:65 and Older 2000,White Alone 2000,White Alone % 2000,Black or African American Alone 2000,Black or African American Alone % 2000,American Indian Alaska Native Alone 2000,American Indian Alaska Native Alone % 2000,Asian Alone 2000,Asian Alone % 2000,Native Hawaiian Other Pacific Islander Alone 2000,Native Hawaiian Other Pacific Islander Alone % 2000,Some Other Race Alone 2000,Some Other Race Alone % 2000,Two or More Races 2000,Two or More Races % 2000,Hispanic or Latino 2000,Hispanic or Latino % 2000,Minority 2000,Minority % 2000,Total Households 2000,Family Households 2000,Family Households: Married Couple Family 2000,Family Households: Not Married Couple Family 2000,Family Households: Not Married Couple: Male no Spouse 2000,Family Households: Not Married Couple: Female no Spouse 2000,Nonfamily Households 2000,Nonfamily Households: Householder Alone 2000,Nonfamily Households: Householder not Alone 2000,Average Household Size 2000,Occupancy:Total Households 2000,Occupancy:Occupied Units 2000,Occupancy%:Occupied Units 2000,Occupancy:Vacant Units 2000,Occupancy%:Vacant Units 2000,Tenure:Total Households 2000,Tenure:Owners 2000,Tenure%:Owners 2000,Tenure:Renters 2000,Tenure%:Renters 2000,Median Household Income 2000,HHIncome:Total Households 2000,"HHIncome:Less than 10,000 2000","HHIncome%:Less than 10,000 2000","HHIncome:10 to 14,999 2000","HHIncome%:10 to 14,999 2000","HHIncome:15 to 19,999 2000","HHIncome%:15 to 19,999 2000","HHIncome:20 to 24,999 2000","HHIncome%:20 to 24,999 2000","HHIncome:25 to 29,999 2000","HHIncome%:25 to 29,999 2000","HHIncome:30 to 34,999 2000","HHIncome:%30 to 34,999 2000","HHIncome:35 to 39,999 2000","HHIncome%:35 to 39,999 2000","HHIncome:40 to 44,999 2000","HHIncome%:40 to 44,999 2000","HHIncome:45 to 49,999 2000","HHIncome%:45 to 49,999 2000","HHIncome:50 to 59,999 2000","HHIncome%:50 to 59,999 2000","HHIncome:60 to 74,999 2000","HHIncome%:60 to 74,999 2000","HHIncome:75 to 99,999 2000","HHIncome%:75 to 99,999 2000","HHIncome:100 to 124,999 2000","HHIncome%:100 to 124,999 2000","HHIncome:125 to 149,999 2000","HHIncome%:125 to 149,999 2000","HHIncome:150 to 199,999 2000","HHIncome%:150 to 199,999 2000",HHIncome:200K or More 2000,HHIncome%:200K or More 2000,Ed:Population 25+ Educational Attainment 2000,Ed:Less than High School 2000,Ed%:Less than High School 2000,Ed:High School Graduate or Equivalency 2000,Ed%:High School Graduate or Equivalency 2000,Ed%:High School Graduate or More 2000,Ed:Some College 2000,Ed%:Some College 2000,Ed%:Some College or More 2000,Ed:Associates 2000,Ed%:Associates 2000,Ed:Bachelors 2000,Ed%:Bachelors 2000,Ed%:Bachelors or More 2000,Ed:Masters 2000,Ed%:Masters 2000,Ed%:Masters or More 2000,Ed:Professional School Degree 2000,Ed%:Professional School Degree 2000,Ed%:Professional School Degree or More 2000,Ed:Doctorate Degree 2000,Ed%:Doctorate Degree 2000,Ind:Employed Civilians 16+ 2000,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2000","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2000",Ind:Construction 2000,Ind%:Construction 2000,Ind:Manufacturing 2000,Ind%:Manufacturing 2000,Ind:Wholesale Trade 2000,Ind%:Wholesale Trade 2000,Ind:Retail Trade 2000,Ind%:Retail Trade 2000,"Ind:Transportation and Warehousing, Utilities 2000","Ind%:Transportation and Warehousing, Utilities 2000",Ind:Information 2000,Ind%:Information 2000,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2000","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2000","Ind:Educational, Health and Social Services 2000","Ind%:Educational, Health and Social Services 2000","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2000","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2000",Ind:Other Services (Except Public Administration) 2000,Ind%:Other Services (Except Public Administration) 2000,Ind:Public Administration 2000,Ind%:Public Administration 2000,Employed Civilians 16+ Occupational 2000,"Occ:Management, Business, and Financial Operations 2000","Occ%:Management, Business, and Financial Operations 2000",Occ:Professional and Related 2000,Occ%:Professional and Related 2000,Occ:Healthcare Support 2000,Occ%:Healthcare Support 2000,Occ:Protective Services 2000,Occ%:Protective Services 2000,Occ:Food Preparation and Serving Related 2000,Occ%:Food Preparation and Serving Related 2000,Occ:Building and Grounds Cleaning and Maintenance 2000,Occ%:Building and Grounds Cleaning and Maintenance 2000,Occ:Personal Care and Service 2000,Occ%:Personal Care and Service 2000,Occ:Sales and Related 2000,Occ%:Sales and Related 2000,Occ:Office and Administrative Support 2000,Occ%:Office and Administrative Support 2000,"Occ:Farming, Fishing, and Forestry 2000","Occ%:Farming, Fishing, and Forestry 2000","Occ:Construction, Extraction, and Maintenance 2000","Occ%:Construction, Extraction, and Maintenance 2000",Occ:Production 2000,Occ%:Production 2000,Occ:Transportation and Material Moving 2000,Occ%:Transportation and Material Moving 2000,Sector: Total Workers 2000,Sector:Private 2000,Sector%:Private 2000,Sector:Public 2000,Sector%:Public 2000,Sector:Self-Employed 2000,Sector%:Self-Employed 2000,Sector:Non-Profit 2000,Sector%:Non-Profit 2000,Sector:Unpaid Family Workers 2000,Sector%:Unpaid Family Workers 2000,Employed 2000,Unemployed 2000,Unemployment Rate 2000,Per Capita Income 2000,Poverty:Population for Whom Poverty Status is Determined 2000,Poverty: Population Below Poverty Level 2000,Poverty%: Below Poverty Level 2000,CB:Total Housing Units 2000,CB:Cost Burdened Housholds 2000,CB:Renter Occupied Units 2000,CB:Cost Burdened Renters 2000,CB%:Cost Burdened Renters 2000,CB:Owner Occupied Units 2000,CB:Cost Burdened Homeowners 2000,CB%: Cost Burdened Homeowners 2000,CB:Severe Cost Burdened Households 2000,CB%:Severe Cost Burdened Households 2000,Median Home Value Owner Occupied 2000,Median Gross Rent 2000,Units:Total Series 2000,"Units:1 Unit, Detached 2000","Units%:1 Unit, Detached 2000","Units:1 Unit, Attached 2000","Units%:1 Unit, Attached 2000",Units:2 2000,Units%:2 2000,Units:3 to 4 2000,Units%:3 to 4 2000,Units:5 to 9 2000,Units%:5 to 9 2000,Units:10 to 19 2000,Units%:10 to 19 2000,Units:20 to 49 2000,Units%:20 to 49 2000,Units:50 or More 2000,Units%:50 or More 2000,Units:Mobile Home 2000,Units%:Mobile Home 2000,"Units:Boat, RV, Van etc 2000","Units%:Boat, RV, Van etc 2000",Transpo:Workers Commuting 2000,"Transpo:Car, Truck, or Van 2000","Transpo%:Car, Truck, or Van 2000",Transpo:Public Transportation 2000,Transpo%:Public Transportation 2000,Transpo:Bicycle 2000,Transpo%:Bicycle 2000,Transpo:Walk 2000,Transpo%:Walk 2000,Transpo:Worked From Home 2000,Transpo%:Worked From Home 2000,"Transpo:Taxi, Motorcycle, Other 2000","Transpo%:Taxi, Motorcycle, Other 2000",Vehicles:Households 2000,Vehicles:None 2000,Vehicles%:None 2000,Vehicles:One 2000,Vehicles%:One 2000,Vehicles:Two 2000,Vehicles%:Two 2000,Vehicles:Three 2000,Vehicles%:Three 2000,Vehicles:Four 2000,Vehicles%:Four 2000,Vehicles:Five or More 2000,Vehicles%:Five or More 2000,Vet:Population 18+ 2000,Vet:Veteran 2000,Vet%:Veteran 2000,Vet:Nonveteran 2000,Vet%:Nonveteran 2000,Vet:Veteran 18 to 64 2000,Vet%:Veterans who are 18 to 64 2000,Vet:Veteran 65 and Older 2000,Vet%:Veterans who are 65 and Older 2000,Vet:Nonveteran 18 to 64 2000,Vet:Nonveteran 65 and Older 2000,Disability Tally 2000,GeoMobility:Total 2000,GeoMobility:Same House as 1995 2000,GeoMobility%:Same House as 1995 2000,GeoMobility:Moved Since 1995 2000,GeoMobility:Moved Same County as 1995 2000,GeoMobility%:Moved Same County as 1995 2000,GeoMobility:Moved Different County Same State as 1995 2000,GeoMobility%:Moved Different County Same State as 1995 2000,GeoMobility:Moved Different State from 1995 2000,GeoMobility%:Moved Different State from 1995 2000,GeoMobility:Moved From Abroad Since 1995 2000,GeoMobility%:Moved From Abroad Since 1995 2000,ForeignBorn:Foreign Born 2000,ForeignBorn%:Foreign Born 2000,ForeignBorn:Native Born 2000,ForeignBorn:Foreign Born Naturalized Citizen 2000,ForeignBorn%:Foreign Born Population that are Naturalized Citizen 2000,ForeignBorn:Foreign Born Not a Citizen 2000,ForeignBorn%:Foreign Born Population that are Not Naturalized Citizen 2000,Foreign Born Population 2000,ForeignBorn:Europe 2000,ForeignBorn:Asia 2000,ForeignBorn:Africa 2000,ForeignBorn:Oceania 2000,"ForeignBorn:Central & South America, Caribbean 2000",ForeignBorn:Canada & Other Northern American 2000,Language:Population 5 and Older 2000,Language:Speak Only English 2000,Language%:Speak Only English 2000,Language:Speak Spanish 2000,Language:Spanish:Speak English Very Well 2000,Language:Spanish:Speak English Well 2000,Language:Spanish:Speak English Not Well 2000,Language:Spanish:Speak English Not At All 2000,Language:Speak Other Indo-European Language 2000,Language:Other Indo-European:Speak English Very Well 2000,Language:Other Indo-European:Speak English Well 2000,Language:Other Indo-European:Speak English Not Well 2000,Language:Other Indo-European:Speak English Not At All 2000,Language:Speak Asian or Pacific Island Language 2000,Language:Asian or Pacific Island:Speak English Very Well 2000,Language:Asian or Pacific Island:Speak English Well 2000,Language:Asian or Pacific Island:Speak English Not Well 2000,Language:Asian or Pacific Island:Speak English Not At All 2000,Language:Speak Other Language 2000,Language:Other:Speak English Very Well 2000,Language:Other:Speak English Well 2000,Language:Other:Speak English Not Well 2000,Language:Other:Speak English Not At All 2000,Language%:Speak Language Besides English 2000,Language%:Of Those that Speak Another Language and Speak English Not Well or At All 2000,Population 2010,Male Under 5 2010,Female Under 5 2010,Male 5 to 9 2010,Female 5 to 9 2010,Male 10 to 14 2010,Female 10 to 14 2010,Male 15 to 17 2010,Female 15 to 17 2010,Male 18 to 24 2010,Female 18 to 24 2010,Male 25 to 34 2010,Female 25 to 34 2010,Male 35 to 44 2010,Female 35 to 44 2010,Male 45 to 54 2010,Female 45 to 54 2010,Male 55 to 64 2010,Female 55 to 64 2010,Male 65 to 74 2010,Female 65 to 74 2010,Male 75 to 84 2010,Female 75 to 84 2010,Male 85 and Older 2010,Female 85 and Older 2010,Age:Under 18 2010,Age:18 to 54 2010,Age:55 and Older 2010,Age:65 and Older 2010,White Alone 2010,White Alone % 2010,Black or African American Alone 2010,Black or African American Alone % 2010,American Indian Alaska Native Alone 2010,American Indian Alaska Native Alone % 2010,Asian Alone 2010,Asian Alone % 2010,Native Hawaiian Other Pacific Islander Alone 2010,Native Hawaiian Other Pacific Islander Alone % 2010,Some Other Race Alone 2010,Some Other Race Alone % 2010,Two or More Races 2010,Two or More Races % 2010,Hispanic or Latino 2010,Hispanic or Latino % 2010,Minority 2010,Minority % 2010,Total Households 2010,Family Households 2010,Family Households: Married Couple Family 2010,Family Households: Not Married Couple Family 2010,Family Households: Not Married Couple: Male no Spouse 2010,Family Households: Not Married Couple: Female no Spouse 2010,Nonfamily Households 2010,Nonfamily Households: Householder Alone 2010,Nonfamily Households: Householder not Alone 2010,Average Household Size 2010,Occupancy:Total Households 2010,Occupancy:Occupied Units 2010,Occupancy%:Occupied Units 2010,Occupancy:Vacant Units 2010,Occupancy%:Vacant Units 2010,Tenure:Total Households 2010,Tenure:Owners 2010,Tenure%:Owners 2010,Tenure:Renters 2010,Tenure%:Renters 2010,Median Household Income 2010,HHIncome:Total Households 2010,"HHIncome:Less than 10,000 2010","HHIncome%:Less than 10,000 2010","HHIncome:10 to 14,999 2010","HHIncome%:10 to 14,999 2010","HHIncome:15 to 19,999 2010","HHIncome%:15 to 19,999 2010","HHIncome:20 to 24,999 2010","HHIncome%:20 to 24,999 2010","HHIncome:25 to 29,999 2010","HHIncome%:25 to 29,999 2010","HHIncome:30 to 34,999 2010","HHIncome:%30 to 34,999 2010","HHIncome:35 to 39,999 2010","HHIncome%:35 to 39,999 2010","HHIncome:40 to 44,999 2010","HHIncome%:40 to 44,999 2010","HHIncome:45 to 49,999 2010","HHIncome%:45 to 49,999 2010","HHIncome:50 to 59,999 2010","HHIncome%:50 to 59,999 2010","HHIncome:60 to 74,999 2010","HHIncome%:60 to 74,999 2010","HHIncome:75 to 99,999 2010","HHIncome%:75 to 99,999 2010","HHIncome:100 to 124,999 2010","HHIncome%:100 to 124,999 2010","HHIncome:125 to 149,999 2010","HHIncome%:125 to 149,999 2010","HHIncome:150 to 199,999 2010","HHIncome%:150 to 199,999 2010",HHIncome:200K or More 2010,HHIncome%:200K or More 2010,Ed:Population 25+ Educational Attainment 2010,Ed:Less than High School 2010,Ed%:Less than High School 2010,Ed:High School Graduate or Equivalency 2010,Ed%:High School Graduate or Equivalency 2010,Ed%:High School Graduate or More 2010,Ed:Some College 2010,Ed%:Some College 2010,Ed%:Some College or More 2010,Ed:Associates 2010,Ed%:Associates 2010,Ed:Bachelors 2010,Ed%:Bachelors 2010,Ed%:Bachelors or More 2010,Ed:Masters 2010,Ed%:Masters 2010,Ed%:Masters or More 2010,Ed:Professional School Degree 2010,Ed%:Professional School Degree 2010,Ed%:Professional School Degree or More 2010,Ed:Doctorate Degree 2010,Ed%:Doctorate Degree 2010,Ind:Employed Civilians 16+ 2010,"Ind:Agriculture, Forestry, Fishing and Hunting, and Mining 2010","Ind%:Agriculture, Forestry, Fishing and Hunting, and Mining 2010",Ind:Construction 2010,Ind%:Construction 2010,Ind:Manufacturing 2010,Ind%:Manufacturing 2010,Ind:Wholesale Trade 2010,Ind%:Wholesale Trade 2010,Ind:Retail Trade 2010,Ind%:Retail Trade 2010,"Ind:Transportation and Warehousing, Utilities 2010","Ind%:Transportation and Warehousing, Utilities 2010",Ind:Information 2010,Ind%:Information 2010,"Ind:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind%:Finance, Insurance, Real Estate and Rental and Leasing 2010","Ind:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind%:Professional, Scientific, Management, Administrative, and Waste Management Services 2010","Ind:Educational, Health and Social Services 2010","Ind%:Educational, Health and Social Services 2010","Ind:Arts, Entertainment, Recreation, Accommodation and Food Services 2010","Ind%:Arts, Entertainment, Recreation, Accommodation and Food Services 2010",Ind:Other Services (Except Public Administration) 2010,Ind%:Other Services (Except Public Administration) 2010,Ind:Public Administration 2010,Ind%:Public Administration 2010,Employed Civilians 16+ Occupational 2010,"Occ:Management, Business, and Financial Operations 2010","Occ%:Management, Business, and Financial Operations 2010",Occ:Professional and Related 2010,Occ%:Professional and Related 2010,Occ:Healthcare Support 2010,Occ%:Healthcare Support 2010,Occ:Protective Services 2010,Occ%:Protective Services 2010,Occ:Food Preparation and Serving Related 2010,Occ%:Food Preparation and Serving Related 2010,Occ:Building and Grounds Cleaning and Maintenance 2010,Occ%:Building and Grounds Cleaning and Maintenance 2010,Occ:Personal Care and Service 2010,Occ%:Personal Care and Service 2010,Occ:Sales and Related 2010,Occ%:Sales and Related 2010,Occ:Office and Administrative Support 2010,Occ%:Office and Administrative Support 2010,"Occ:Farming, Fishing, and Forestry 2010","Occ%:Farming, Fishing, and Forestry 2010","Occ:Construction, Extraction, and Maintenance 2010","Occ%:Construction, Extraction, and Maintenance 2010",Occ:Production 2010,Occ%:Production 2010,Occ:Transportation and Material Moving 2010,Occ%:Transportation and Material Moving 2010,Sector: Total Workers 2010,Sector:Private 2010,Sector%:Private 2010,Sector:Public 2010,Sector%:Public 2010,Sector:Self-Employed 2010,Sector%:Self-Employed 2010,Sector:Non-Profit 2010,Sector%:Non-Profit 2010,Sector:Unpaid Family Workers 2010,Sector%:Unpaid Family Workers 2010,Employed 2010,Unemployed 2010,Unemployment Rate 2010,Per Capita Income 2010,Poverty:Population for Whom Poverty Status is Determined 2010,Poverty: Population Below Poverty Level 2010,Poverty%: Below Poverty Level 2010,CB:Total Housing Units 2010,CB:Cost Burdened Housholds 2010,CB:Renter Occupied Units 2010,CB:Cost Burdened Renters 2010,CB%:Cost Burdened Renters 2010,CB:Owner Occupied Units 2010,CB:Cost Burdened Homeowners 2010,CB%: Cost Burdened Homeowners 2010,CB:Severe Cost Burdened Households 2010,CB%:Severe Cost Burdened Households 2010,Median Home Value Owner Occupied with Mortgage 2010,Median Home Value Owner Occupied without Mortgage 2010,Median Gross Rent 2010,Units:Total Series 2010,"Units:1 Unit, Detached 2010","Units%:1 Unit, Detached 2010","Units:1 Unit, Attached 2010","Units%:1 Unit, Attached 2010",Units:2 2010,Units%:2 2010,Units:3 to 4 2010,Units%:3 to 4 2010,Units:5 to 9 2010,Units%:5 to 9 2010,Units:10 to 19 2010,Units%:10 to 19 2010,Units:20 to 49 2010,Units%:20 to 49 2010,Units:50 or More 2010,Units%:50 or More 2010,Units:Mobile Home 2010,Units%:Mobile Home 2010,"Units:Boat, RV, Van etc 2010","Units%:Boat, RV, Van etc 2010",Transpo:Workers Commuting 2010,"Transpo:Car, Truck, or Van 2010","Transpo%:Car, Truck, or Van 2010",Transpo:Public Transportation 2010,Transpo%:Public Transportation 2010,Transpo:Bicycle 2010,Transpo%:Bicycle 2010,Transpo:Walk 2010,Transpo%:Walk 2010,Transpo:Worked From Home 2010,Transpo%:Worked From Home 2010,"Transpo:Taxi, Motorcycle, Other 2010","Transpo%:Taxi, Motorcycle, Other 2010",Vehicles:Households 2010,Vehicles:None 2010,Vehicles%:None 2010,Vehicles:One 2010,Vehicles%:One 2010,Vehicles:Two 2010,Vehicles%:Two 2010,Vehicles:Three 2010,Vehicles%:Three 2010,Vehicles:Four 2010,Vehicles%:Four 2010,Vehicles:Five or More 2010,Vehicles%:Five or More 2010,Commute:Workers 16+ Not Working at Home 2010,Commute:Less than 10 Minutes 2010,Commute:10 to 14 Minutes 2010,Commute:15 to 19 Minutes 2010,Commute:20 to 24 Minutes 2010,Commute:25 to 29 Minutes 2010,Commute:30 to 34 Minutes 2010,Commute:35 to 44 Minutes 2010,Commute:45 to 59 Minutes 2010,Commute:60 or More Minutes 2010,"Commute:Car, Truck, Van Drove Alone:Less than 10 Minutes 2010","Commute:Car, Truck, Van Drove Alone:10 to 14 Minutes 2010","Commute:Car, Truck, Van Drove Alone:15 to 19 Minutes 2010","Commute:Car, Truck, Van Drove Alone:20 to 24 Minutes 2010","Commute:Car, Truck, Van Drove Alone:25 to 29 Minutes 2010","Commute:Car, Truck, Van Drove Alone:30 to 34 Minutes 2010","Commute:Car, Truck, Van Drove Alone:35 to 44 Minutes 2010","Commute:Car, Truck, Van Drove Alone:45 to 59 Minutes 2010","Commute:Car, Truck, Van Drove Alone:60 or More Minutes 2010","Commute:Car, Truck, Van Carpooled:Less than 10 Minutes 2010","Commute:Car, Truck, Van Carpooled:10 to 14 Minutes 2010","Commute:Car, Truck, Van Carpooled:15 to 19 Minutes 2010","Commute:Car, Truck, Van Carpooled:20 to 24 Minutes 2010","Commute:Car, Truck, Van Carpooled:25 to 29 Minutes 2010","Commute:Car, Truck, Van Carpooled:30 to 34 Minutes 2010","Commute:Car, Truck, Van Carpooled:35 to 44 Minutes 2010","Commute:Car, Truck, Van Carpooled:45 to 59 Minutes 2010","Commute:Car, Truck, Van Carpooled:60 or More Minutes 2010",Vet:Population 18+ 2010,Vet:Veteran 2010,Vet%:Veteran 2010,Vet:Nonveteran 2010,Vet%:Nonveteran 2010,Vet:Veteran 18 to 64 2010,Vet%:Veterans who are 18 to 64 2010,Vet:Veteran 65 and Older 2010,Vet%:Veterans who are 65 and Older 2010,Vet:Nonveteran 18 to 64 2010,Vet:Nonveteran 65 and Older 2010,GeoMobility:Total 2010,GeoMobili

In [108]:
data.to_csv('checker.csv', index = False)

In [109]:
df = data

### Fig.1: Total Population 2000 to 2020 Table  
Table with State, GNRC MPO regions, county incorporated and unincorporated areas, and the geography of interest with population for 2000, 2010, and 2020 followed by percent change 2000 to 2020 and 2010 to 2020.

In [116]:
fig1 = data[['NAME','Population 2000', 'Population 2010', 'Population 2020']]
fig1['% Change 2000 to 2020'] = prettypercentchange(data['Population 2020'], data['Population 2000'])
fig1['% Change 2010 to 2020'] = prettypercentchange(data['Population 2010'], data['Population 2000'])
#For just State, Regions, County, and Gallatin city
fig1 = fig1.loc[(fig1['NAME'] == 'Tennessee')|(fig1['NAME'] == 'GNRC')|(fig1['NAME'] == 'MPO') |(fig1['NAME'] == 'Sumner County')|(fig1['NAME'] == 'Gallatin')]

In [126]:
styles = [
    #TH:Header
    dict(selector="th", props=[("color", "#fff"),("border", "1px solid #eee"),("padding", "12px 35px"),("border-collapse", "collapse"),
                               ("background", "#00cccc"),("text-transform", "uppercase"),("font-size", "18px")]),
    #TD:Cell
    dict(selector="td", props=[("color", "#999"),("border", "1px solid #eee"),("padding", "12px 35px"),("border-collapse", "collapse"),("font-size", "15px")]),
    dict(selector="table", props=[("font-family" , 'Arial'),("margin" , "25px auto"),("border-collapse" , "collapse"),
                                  ("border" , "1px solid #eee"),("border-bottom" , "#EB7525"),]),
    dict(selector="caption", props=[("caption-side", "top"),("color", "#666"),("font-size", "20px"),("text-transform", "uppercase"),("font-family" , 'Arial'),
                                    ("margin" , "25px auto"),("border" , "1px solid #eee")])
]

In [111]:
fig1.head()

            NAME  Population 2000  Population 2010  Population 2020 % Change 2000 to 2020 % Change 2010 to 2020
0      Tennessee        5689283.0        6346105.0        6910840.0                 21.5%                 11.5%
1           GNRC        1411725.0        1722648.0        2089918.0                 48.0%                 22.0%
2            MPO        1221741.0        1494344.0        1822891.0                 49.2%                 22.3%
3  Sumner County         130449.0         160645.0         196281.0                 50.5%                 23.1%
4       Gallatin          23230.0          30278.0          44431.0                 91.3%                 30.3%

In [112]:
df_styled = fig1.style.set_table_styles(styles2).set_precision(0).set_caption('Population Change Over Time').hide_index()

C:\Users\jmccall\AppData\Local\Temp/ipykernel_21592/258788067.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  df_styled = fig1.style.set_table_styles(styles2).set_precision(0).set_caption('Population Change Over Time').hide_index()

In [113]:
df_styled

In [114]:
dfi.export(df_styled,"f.1_Population Change Over Time.png")

### Fig.2: Total Population 2000 to 2020 Graphic  
They have a line graph with all geographies on the same figure.

### Fig.3: Percent Change in Historic Population Graphic  
Bar chart with the percent change in population between 2000 and 2020 per geography

### Figures 4 - 6 pertain to population projections

### Fig.7: Population Pyramid Graphic  
Population pyramid by sex for age groups: u5, 5 to 9, 10 to 14, 15 to 17, 18 to 24, 25 to 34, 35 to 44, 45 to 54, 55 to 64, 65 to 74, 75 to 84, 85 and Older

### Fig.8: Population by Age Brackets, 2010 Table  
All geographies: total population, under 18 years, 18 to 54, 55+ (number and percent of total population)

In [117]:
def prettypercentof(x, y):
    return round((100*x)/y, 1).astype(str)+'%'
# def mathpercentchange(x, y):
#     return round((x - y)/y, 1)
                 
# return round((x - y)*100/y, 1).astype(str)+'%'

In [119]:
fig2 = data[['NAME','Population 2010', 'Age:Under 18 2010', 'Age:18 to 54 2010', 'Age:55 and Older 2010']]
fig2['% of Population Under 18'] = prettypercentof(data['Age:Under 18 2010'], data['Population 2010'])
fig2['% of Population 18 to 54'] = prettypercentof(data['Age:18 to 54 2010'], data['Population 2010'])
fig2['% of Population 55 and Older'] = prettypercentof(data['Age:55 and Older 2010'], data['Population 2010'])
#For just State, Regions, County, and Gallatin city
fig2 = fig2.loc[(fig1['NAME'] == 'Tennessee')|(fig2['NAME'] == 'GNRC')|(fig2['NAME'] == 'MPO') |(fig2['NAME'] == 'Sumner County')|(fig2['NAME'] == 'Gallatin')]

In [120]:
fig2.head()

,NAME,Population 2010,Age:Under 18 2010,Age:18 to 54 2010,Age:55 and Older 2010,% of Population Under 18,% of Population 18 to 54,% of Population 55 and Older
0,Tennessee,6346105.0,1496001.0,3210927.0,1639177.0,23.6%,50.6%,25.8%
1,GNRC,1722648.0,426636.0,928044.0,367968.0,24.8%,53.9%,21.4%
2,MPO,1494344.0,364624.0,805650.0,324070.0,24.4%,53.9%,21.7%
3,Sumner County,160645.0,40630.0,79902.0,40113.0,25.3%,49.7%,25.0%
4,Gallatin,30278.0,7330.0,15347.0,7601.0,24.2%,50.7%,25.1%

In [123]:
df_styled = fig2.style.set_table_styles(styles2).set_precision(0).set_caption('Population by Age Brackets 2010').hide_index()

C:\Users\jmccall\AppData\Local\Temp/ipykernel_21592/2408809821.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  df_styled = fig2.style.set_table_styles(styles2).set_precision(0).set_caption('Population by Age Brackets 2010').hide_index()

In [124]:
df_styled

In [125]:
dfi.export(df_styled,"f.2_Population by Age Brackets 2010.png")

### Fig.9: Population by Age Brackets, 2020 Table  
All geographies: total population, under 18 years, 18 to 54, 55+ (number and percent of total population)

### Fig.10: Population 65 and Over, 2020 Table  
All geographies: total population, 65+ (number and percent of total population)

### Fig.11: Population Change by Age Bracket, 2000 to 2010 Table  
All geographies: total population both years, 2000-2010 % change, same for under 18, 18 to 54, and 55+

### Fig.12: Population Change by Age Bracket, 2000 to 2020 Table  
All geographies: total population both years, 2000-2010 % change, same for under 18, 18 to 54, and 55+

### Fig.13: Population Change by Age Bracket by Decade Graphic  
Geography of interes, bar chart with contrasting percent changes between 2000/2010, and 2010/2020

## Race and Ethnicity

### Fig.14: Race and Ethnicity Population Breakout, 2000 Table  
All geographies: total population, then percentages only for White Alone, Black or African American Alone, American Indian or Alaska Native Alone, Asian Alone, Native Hawaiian or Other Pacific Islander Alone, Other Race Alone, Two or More Races, Hispanic or Latino Origin, White Alone not Hispanic or Latino Origin, and Total Minority (Not White Alone nor of Hispanic or Latino Origin)

### Fig.15: Race and Ethnicity Population Breakout, 2010 Table  
All geographies: total population, then percentages only for White Alone, Black or African American Alone, American Indian or Alaska Native Alone, Asian Alone, Native Hawaiian or Other Pacific Islander Alone, Other Race Alone, Two or More Races, Hispanic or Latino Origin, White Alone not Hispanic or Latino Origin, and Total Minority (Not White Alone nor of Hispanic or Latino Origin)

### Fig.16: Race and Ethnicity Population Breakout, 2020 Table  
All geographies: total population, then percentages only for White Alone, Black or African American Alone, American Indian or Alaska Native Alone, Asian Alone, Native Hawaiian or Other Pacific Islander Alone, Other Race Alone, Two or More Races, Hispanic or Latino Origin, White Alone not Hispanic or Latino Origin, and Total Minority (Not White Alone nor of Hispanic or Latino Origin)

### Fig.17: Race Breakout Graphic  
Pie chart for geography of interest with race percentages

### Fig. 18: Minority Population Graphic  
Pie chart for geography of interest with minority vs. non-minority percentages

## Household Characteristics

### Fig.19: Average Household Size 2000, 2010, and 2020 Table  
All geographies except for unincorporated (weighted average for incorporated cities... even though all the other citations are for the proportional distribution based on 2010 decennial whatever?... anyway: 2000, 2010, 2020, % change in hh size 2000 to 2020, and average annual growth rate in household size 2000 to 2020

### Fig.20: Households by Household Type, 2020 Graphic  
Column of percent for composition for all geographies: Nonfam/female householder, Nonfam/male householder, Family/married-couple, Family/other family Male householder no spouse present, Family/other family Female householder no spouse present

### Fig. 21 Change in Median Household Income 2000 - 2020 Graphic  
Bar chart with percent change for state, regions, county, all places...  
#### Not from Census

### Fig. 22 Change in Median Household Income Inflation-Adjusted 2000 - 2020 Graphic  
Bar chart with percent change for state, regions, county, all places...  
#### Not from Census

### Fig. 23: Median Household Income 2000, 2010, and 2020 Table  
State, Regions, Geo of interest and places in county. 2000, 2010, 2020 w/ percent change in MHI 2000-2020

### Fig.24. MHI 2000, 2010, 2020 Graphic  
State, Regions, Geo of interest and places in county line chart all on same figure

### Fig.25: Geo of Interest Household Income Distribution, 2020 Graphic  
All Income brackets bar chart (%s)

## Poverty

### Fig.26: Population Below the Poverty Level Graphic   
All geographies % pop living below level graphic 2000, 2010, 2020

## Housing

### Fig.27-28 Residential Permit Info
### Not from Census

### Fig.29 Age of Housing Stock Graphic  
Geography of interest pie chart 2020

### Fig.30 Median Year Residential Stucture Built Graphic...  
State, regions, geo of interest, all places in county

### Fig.31 Residential Building Type Mix Graphic  
Geo of interest + all other places? Single family vs all multi family bar composition charts, 2020

### Fig.32 Residential Building Permit by Type Table  
### Not from Census

### Fig.33 Percent Change in Housing Units by Type, 2000 - 2019... Currently Awful Graphic  
weird bar chart for geo of interest